# Generated by Django 5.0.14 on 2026-01-05 13:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIModelProvider",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("openai", "OpenAI"),
                            ("anthropic", "Anthropic"),
                            ("groq", "Groq"),
                            ("huggingface", "HuggingFace"),
                            ("azure_openai", "Azure OpenAI"),
                            ("google_gemini", "Google Gemini"),
                        ],
                        max_length=32,
                    ),
                ),
                ("display_name", models.CharField(max_length=128)),
                ("key_vault_ref", models.CharField(blank=True, max_length=256)),
                ("model_name", models.CharField(max_length=128)),
                ("endpoint_url", models.URLField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                ("max_tokens", models.IntegerField(default=4096)),
                ("temperature", models.FloatField(default=0.7)),
            ],
            options={
                "verbose_name": "AI Model Provider",
                "verbose_name_plural": "AI Model Providers",
                "indexes": [
                    models.Index(
                        fields=["provider_type", "is_active"],
                        name="ai_agents_a_provide_8ebdde_idx",
                    ),
                    models.Index(
                        fields=["is_default"], name="ai_agents_a_is_defa_92c877_idx"
                    ),
                ],
                "unique_together": {("provider_type", "model_name")},
            },
        ),
        migrations.CreateModel(
            name="AIConversation",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "agent_type",
                    models.CharField(
                        choices=[
                            ("amani", "Ask Amani (General Assistant)"),
                            ("packaging", "Packaging Assistant"),
                            ("cab_evidence", "CAB Evidence Generator"),
                            ("risk_explainer", "Risk Score Explainer"),
                            ("deployment", "Deployment Advisor"),
                            ("compliance", "Compliance Analyzer"),
                            ("incident", "Incident Responder"),
                        ],
                        max_length=32,
                    ),
                ),
                ("context_type", models.CharField(blank=True, max_length=64)),
                ("context_id", models.CharField(blank=True, max_length=128)),
                ("title", models.CharField(blank=True, max_length=256)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ai_agents.aimodelprovider",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Conversation",
                "verbose_name_plural": "AI Conversations",
            },
        ),
        migrations.CreateModel(
            name="AIAgentTask",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "agent_type",
                    models.CharField(
                        choices=[
                            ("amani", "Ask Amani (General Assistant)"),
                            ("packaging", "Packaging Assistant"),
                            ("cab_evidence", "CAB Evidence Generator"),
                            ("risk_explainer", "Risk Score Explainer"),
                            ("deployment", "Deployment Advisor"),
                            ("compliance", "Compliance Analyzer"),
                            ("incident", "Incident Responder"),
                        ],
                        max_length=32,
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("description", models.TextField()),
                ("task_type", models.CharField(max_length=64)),
                ("input_data", models.JSONField(default=dict)),
                ("output_data", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("awaiting_approval", "Awaiting Human Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("executing", "Executing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("correlation_id", models.UUIDField(default=uuid.uuid4)),
                ("deployment_intent_id", models.UUIDField(blank=True, null=True)),
                ("evidence_pack_id", models.UUIDField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_ai_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ai_agents.aiconversation",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Agent Task",
                "verbose_name_plural": "AI Agent Tasks",
                "indexes": [
                    models.Index(
                        fields=["initiated_by", "created_at"],
                        name="ai_agents_a_initiat_cff512_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="ai_agents_a_status_4c116d_idx",
                    ),
                    models.Index(
                        fields=["agent_type", "status"],
                        name="ai_agents_a_agent_t_bed56a_idx",
                    ),
                    models.Index(
                        fields=["correlation_id"], name="ai_agents_a_correla_d7cb0e_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AIMessage",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("assistant", "Assistant"),
                            ("system", "System"),
                        ],
                        max_length=16,
                    ),
                ),
                ("content", models.TextField()),
                ("token_count", models.IntegerField(default=0)),
                ("model_used", models.CharField(blank=True, max_length=64)),
                ("requires_human_action", models.BooleanField(default=False)),
                ("action_taken", models.BooleanField(default=False)),
                ("action_at", models.DateTimeField(blank=True, null=True)),
                (
                    "action_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="ai_agents.aiconversation",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Message",
                "verbose_name_plural": "AI Messages",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["conversation", "created_at"],
                        name="ai_agents_a_convers_016e72_idx",
                    ),
                    models.Index(
                        fields=["requires_human_action", "action_taken"],
                        name="ai_agents_a_require_66a66f_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="aiconversation",
            index=models.Index(
                fields=["user", "created_at"], name="ai_agents_a_user_id_0c62e5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiconversation",
            index=models.Index(
                fields=["agent_type", "is_active"],
                name="ai_agents_a_agent_t_8e9cb9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aiconversation",
            index=models.Index(
                fields=["context_type", "context_id"],
                name="ai_agents_a_context_4443fe_idx",
            ),
        ),
    ]
