# Generated by Django 5.0.14 on 2026-01-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_agents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aimodelprovider",
            name="api_key_dev",
            field=models.CharField(
                blank=True, help_text="DEV ONLY: Direct API key storage", max_length=512
            ),
        ),
    ]
