# Generated by Django 5.0.14 on 2026-01-06 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_agents", "0002_add_api_key_dev"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aiagenttask",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_progress", "In Progress"),
                    ("awaiting_approval", "Awaiting Human Approval"),
                    ("revision_requested", "Revision Requested"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("executing", "Executing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=32,
            ),
        ),
    ]
