# Generated by Django 5.0.14 on 2026-01-21 18:07

import apps.core.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ai_agents", "0003_alter_aiagenttask_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aimodelprovider",
            name="api_key_dev",
            field=apps.core.encryption.EncryptedCharField(
                blank=True, help_text="DEV ONLY: Encrypted API key storage", max_length=2048
            ),
        ),
    ]
