# Generated by Django 5.0.14 on 2026-01-30 06:21

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_agents", "0004_alter_aimodelprovider_api_key_dev"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIModel",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("model_id", models.CharField(db_index=True, max_length=100, unique=True)),
                ("model_type", models.CharField(max_length=50)),
                ("version", models.CharField(max_length=50)),
                ("display_name", models.CharField(max_length=256)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("validated", "Validated"),
                            ("deployed", "Deployed"),
                            ("deprecated", "Deprecated"),
                            ("retired", "Retired"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("R1", "R1 - Low (Auto-execute allowed)"),
                            ("R2", "R2 - Medium (Policy-dependent approval)"),
                            ("R3", "R3 - High (Mandatory human approval)"),
                        ],
                        default="R2",
                        max_length=10,
                    ),
                ),
                ("dataset_version", models.CharField(blank=True, max_length=100)),
                ("training_params", models.JSONField(blank=True, default=dict)),
                ("validation_report", models.JSONField(blank=True, default=dict)),
                ("deployed_at", models.DateTimeField(blank=True, null=True)),
                ("deployment_notes", models.TextField(blank=True)),
                ("baseline_accuracy", models.FloatField(blank=True, null=True)),
                ("baseline_confidence_mean", models.FloatField(blank=True, null=True)),
                ("baseline_latency_ms", models.FloatField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_ai_models",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deployed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deployed_ai_models",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="derived_models",
                        to="ai_agents.aimodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Model",
                "verbose_name_plural": "AI Models",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentExecution",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("correlation_id", models.UUIDField(db_index=True, default=uuid.uuid4)),
                ("agent_type", models.CharField(db_index=True, max_length=100)),
                ("input_hash", models.CharField(db_index=True, max_length=64)),
                ("input_summary", models.JSONField(default=dict)),
                ("output", models.JSONField(default=dict)),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("latency_ms", models.FloatField(blank=True, null=True)),
                ("risk_level", models.CharField(default="R2", max_length=10)),
                ("approval_required", models.BooleanField(default=False)),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("not_required", "Not Required"),
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("auto_approved", "Auto-Approved (R1)"),
                        ],
                        default="not_required",
                        max_length=20,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("executed", models.BooleanField(default=False)),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                ("execution_result", models.JSONField(blank=True, null=True)),
                ("execution_error", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_executions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_executions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="executions",
                        to="ai_agents.aimodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent Execution",
                "verbose_name_plural": "Agent Executions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ModelDriftMetric",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("accuracy", "Accuracy"),
                            ("confidence_mean", "Mean Confidence"),
                            ("confidence_std", "Confidence Std Dev"),
                            ("override_rate", "Human Override Rate"),
                            ("latency_p50", "Latency P50"),
                            ("latency_p95", "Latency P95"),
                            ("error_rate", "Error Rate"),
                            ("input_drift", "Input Distribution Drift"),
                            ("output_drift", "Output Distribution Drift"),
                        ],
                        max_length=50,
                    ),
                ),
                ("value", models.FloatField()),
                ("threshold", models.FloatField()),
                ("baseline_value", models.FloatField(blank=True, null=True)),
                ("is_alert", models.BooleanField(default=False)),
                ("alert_acknowledged", models.BooleanField(default=False)),
                ("alert_acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("window_start", models.DateTimeField()),
                ("window_end", models.DateTimeField()),
                ("sample_count", models.IntegerField(default=0)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "alert_acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acknowledged_drift_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drift_metrics",
                        to="ai_agents.aimodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Model Drift Metric",
                "verbose_name_plural": "Model Drift Metrics",
                "ordering": ["-recorded_at"],
            },
        ),
        migrations.AddIndex(
            model_name="aimodel",
            index=models.Index(fields=["model_id", "version"], name="ai_agents_a_model_i_458a29_idx"),
        ),
        migrations.AddIndex(
            model_name="aimodel",
            index=models.Index(fields=["status", "risk_level"], name="ai_agents_a_status_097ab6_idx"),
        ),
        migrations.AddIndex(
            model_name="aimodel",
            index=models.Index(fields=["model_type", "status"], name="ai_agents_a_model_t_bcb5fe_idx"),
        ),
        migrations.AddIndex(
            model_name="agentexecution",
            index=models.Index(fields=["agent_type", "created_at"], name="ai_agents_a_agent_t_0cefcf_idx"),
        ),
        migrations.AddIndex(
            model_name="agentexecution",
            index=models.Index(fields=["correlation_id"], name="ai_agents_a_correla_3b3166_idx"),
        ),
        migrations.AddIndex(
            model_name="agentexecution",
            index=models.Index(fields=["approval_status", "created_at"], name="ai_agents_a_approva_9976a2_idx"),
        ),
        migrations.AddIndex(
            model_name="agentexecution",
            index=models.Index(fields=["executed", "created_at"], name="ai_agents_a_execute_72709e_idx"),
        ),
        migrations.AddIndex(
            model_name="agentexecution",
            index=models.Index(fields=["input_hash"], name="ai_agents_a_input_h_82e3b6_idx"),
        ),
        migrations.AddIndex(
            model_name="modeldriftmetric",
            index=models.Index(fields=["model", "metric_type", "recorded_at"], name="ai_agents_m_model_i_aa3365_idx"),
        ),
        migrations.AddIndex(
            model_name="modeldriftmetric",
            index=models.Index(fields=["is_alert", "alert_acknowledged"], name="ai_agents_m_is_aler_da319e_idx"),
        ),
        migrations.AddIndex(
            model_name="modeldriftmetric",
            index=models.Index(fields=["recorded_at"], name="ai_agents_m_recorde_83d627_idx"),
        ),
    ]
