# Generated by Django 5.1.15 on 2026-01-31 06:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_agents", "0006_workflow_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="workflowdefinition",
            new_name="ai_agents_w_agent_t_5c1550_idx",
            old_name="ai_agents_w_agent_t_123abc_idx",
        ),
        migrations.RenameIndex(
            model_name="workflowdefinition",
            new_name="ai_agents_w_risk_le_1a2829_idx",
            old_name="ai_agents_w_risk_le_456def_idx",
        ),
        migrations.RenameIndex(
            model_name="workflowexecution",
            new_name="ai_agents_w_initiat_855795_idx",
            old_name="ai_agents_w_initiat_789ghi_idx",
        ),
        migrations.RenameIndex(
            model_name="workflowexecution",
            new_name="ai_agents_w_status_a350ca_idx",
            old_name="ai_agents_w_status__jklmno_idx",
        ),
        migrations.RenameIndex(
            model_name="workflowexecution",
            new_name="ai_agents_w_workflo_bd812b_idx",
            old_name="ai_agents_w_workflow_pqrstu_idx",
        ),
        migrations.RenameIndex(
            model_name="workflowstep",
            new_name="ai_agents_w_executi_d5abc1_idx",
            old_name="ai_agents_w_executi_vwxyz1_idx",
        ),
        migrations.RenameIndex(
            model_name="workflowstep",
            new_name="ai_agents_w_status_7bd842_idx",
            old_name="ai_agents_w_status__234567_idx",
        ),
        migrations.AlterField(
            model_name="aiagenttask",
            name="agent_type",
            field=models.CharField(
                choices=[
                    ("amani", "Ask Amani (General Assistant)"),
                    ("packaging", "Packaging Assistant"),
                    ("cab_evidence", "CAB Evidence Generator"),
                    ("risk_explainer", "Risk Score Explainer"),
                    ("deployment", "Deployment Advisor"),
                    ("compliance", "Compliance Analyzer"),
                    ("incident", "Incident Responder"),
                    ("documentation", "Documentation Agent"),
                    ("automation_advisor", "Automation Advisor Agent"),
                    ("iam_security", "IAM Security Agent"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="aiconversation",
            name="agent_type",
            field=models.CharField(
                choices=[
                    ("amani", "Ask Amani (General Assistant)"),
                    ("packaging", "Packaging Assistant"),
                    ("cab_evidence", "CAB Evidence Generator"),
                    ("risk_explainer", "Risk Score Explainer"),
                    ("deployment", "Deployment Advisor"),
                    ("compliance", "Compliance Analyzer"),
                    ("incident", "Incident Responder"),
                    ("documentation", "Documentation Agent"),
                    ("automation_advisor", "Automation Advisor Agent"),
                    ("iam_security", "IAM Security Agent"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="workflowdefinition",
            name="agent_type",
            field=models.CharField(
                choices=[
                    ("amani", "Ask Amani (General Assistant)"),
                    ("packaging", "Packaging Assistant"),
                    ("cab_evidence", "CAB Evidence Generator"),
                    ("risk_explainer", "Risk Score Explainer"),
                    ("deployment", "Deployment Advisor"),
                    ("compliance", "Compliance Analyzer"),
                    ("incident", "Incident Responder"),
                    ("documentation", "Documentation Agent"),
                    ("automation_advisor", "Automation Advisor Agent"),
                    ("iam_security", "IAM Security Agent"),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
        migrations.AddIndex(
            model_name="workflowexecution",
            index=models.Index(fields=["correlation_id"], name="ai_agents_w_correla_fa04ce_idx"),
        ),
    ]
