# Generated by Django 5.1.15 on 2026-01-31 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_agents", "0007_add_new_agent_types_and_fixes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aiagenttask",
            name="agent_type",
            field=models.CharField(
                choices=[
                    ("amani", "Ask Amani (General Assistant)"),
                    ("packaging", "Packaging Assistant"),
                    ("cab_evidence", "CAB Evidence Generator"),
                    ("risk_explainer", "Risk Score Explainer"),
                    ("deployment", "Deployment Advisor"),
                    ("compliance", "Compliance Analyzer"),
                    ("incident", "Incident Responder"),
                    ("documentation", "Documentation Agent"),
                    ("automation_advisor", "Automation Advisor Agent"),
                    ("iam_security", "IAM Security Agent"),
                    ("request_coordination", "Request Coordination Agent"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="aiconversation",
            name="agent_type",
            field=models.CharField(
                choices=[
                    ("amani", "Ask Amani (General Assistant)"),
                    ("packaging", "Packaging Assistant"),
                    ("cab_evidence", "CAB Evidence Generator"),
                    ("risk_explainer", "Risk Score Explainer"),
                    ("deployment", "Deployment Advisor"),
                    ("compliance", "Compliance Analyzer"),
                    ("incident", "Incident Responder"),
                    ("documentation", "Documentation Agent"),
                    ("automation_advisor", "Automation Advisor Agent"),
                    ("iam_security", "IAM Security Agent"),
                    ("request_coordination", "Request Coordination Agent"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="workflowdefinition",
            name="agent_type",
            field=models.CharField(
                choices=[
                    ("amani", "Ask Amani (General Assistant)"),
                    ("packaging", "Packaging Assistant"),
                    ("cab_evidence", "CAB Evidence Generator"),
                    ("risk_explainer", "Risk Score Explainer"),
                    ("deployment", "Deployment Advisor"),
                    ("compliance", "Compliance Analyzer"),
                    ("incident", "Incident Responder"),
                    ("documentation", "Documentation Agent"),
                    ("automation_advisor", "Automation Advisor Agent"),
                    ("iam_security", "IAM Security Agent"),
                    ("request_coordination", "Request Coordination Agent"),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
    ]
