# Generated by Django 5.1.15 on 2026-01-31 12:03

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IncidentPattern",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique correlation ID for audit trail and tracing",
                        unique=True,
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                (
                    "pattern_type",
                    models.CharField(
                        choices=[("recurring", "Recurring"), ("trending", "Trending"), ("correlated", "Correlated")],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("category", models.CharField(db_index=True, max_length=255)),
                ("occurrence_count", models.IntegerField(default=0)),
                ("affected_users", models.IntegerField(default=0)),
                ("first_detected", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_detected", models.DateTimeField(default=django.utils.timezone.now)),
                ("related_change", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("investigating", "Investigating"), ("resolved", "Resolved")],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("root_cause", models.TextField(blank=True, null=True)),
                ("resolution", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Incident Pattern",
                "verbose_name_plural": "Incident Patterns",
                "indexes": [
                    models.Index(fields=["pattern_type", "status"], name="kb_triage_i_pattern_80f0b4_idx"),
                    models.Index(fields=["category", "status"], name="kb_triage_i_categor_7c09c9_idx"),
                    models.Index(fields=["correlation_id"], name="kb_triage_i_correla_fbdaff_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeSource",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("servicenow_kb", "ServiceNow KB"),
                            ("confluence", "Confluence"),
                            ("sharepoint", "SharePoint"),
                            ("vendor", "Vendor Documentation"),
                            ("custom", "Custom"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("connection_config", models.JSONField(default=dict, help_text="Source connection configuration")),
                ("sync_schedule", models.CharField(default="0 */6 * * *", help_text="Cron expression", max_length=50)),
                ("last_sync", models.DateTimeField(blank=True, null=True)),
                ("article_count", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Knowledge Source",
                "verbose_name_plural": "Knowledge Sources",
                "indexes": [models.Index(fields=["source_type", "is_active"], name="kb_triage_k_source__9f3c2d_idx")],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeArticle",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("external_id", models.CharField(db_index=True, max_length=255)),
                ("title", models.CharField(max_length=500)),
                ("content", models.TextField()),
                ("category", models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ("tags", models.JSONField(default=list)),
                ("url", models.URLField(blank=True, null=True)),
                ("author", models.CharField(blank=True, max_length=255, null=True)),
                ("published_date", models.DateTimeField(blank=True, null=True)),
                ("last_updated", models.DateTimeField(blank=True, null=True)),
                ("view_count", models.IntegerField(default=0)),
                ("helpful_count", models.IntegerField(default=0)),
                (
                    "embedding",
                    models.JSONField(blank=True, help_text="Vector embedding for semantic search", null=True),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles",
                        to="kb_triage.knowledgesource",
                    ),
                ),
            ],
            options={
                "verbose_name": "Knowledge Article",
                "verbose_name_plural": "Knowledge Articles",
            },
        ),
        migrations.CreateModel(
            name="TriageRequest",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique correlation ID for audit trail and tracing",
                        unique=True,
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("servicenow_number", models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ("caller_name", models.CharField(max_length=255)),
                ("caller_email", models.EmailField(blank=True, max_length=254, null=True)),
                ("affected_service", models.CharField(blank=True, max_length=255, null=True)),
                ("short_description", models.CharField(max_length=500)),
                ("description", models.TextField()),
                ("symptoms", models.JSONField(default=list)),
                ("suggested_category", models.CharField(blank=True, max_length=255, null=True)),
                ("suggested_subcategory", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "suggested_priority",
                    models.CharField(
                        blank=True,
                        choices=[("1", "Critical"), ("2", "High"), ("3", "Medium"), ("4", "Low")],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("suggested_assignment_group", models.CharField(blank=True, max_length=255, null=True)),
                ("confidence_score", models.FloatField(blank=True, null=True)),
                ("reasoning", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("triaged", "Triaged"),
                            ("escalated", "Escalated"),
                            ("resolved", "Resolved"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("triage_time_ms", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Triage Request",
                "verbose_name_plural": "Triage Requests",
                "indexes": [
                    models.Index(fields=["status", "created_at"], name="kb_triage_t_status_d6ae62_idx"),
                    models.Index(fields=["servicenow_number"], name="kb_triage_t_service_db3dd0_idx"),
                    models.Index(fields=["correlation_id"], name="kb_triage_t_correla_d0cbd4_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="TriageFeedback",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("category", "Category"),
                            ("priority", "Priority"),
                            ("assignment", "Assignment"),
                            ("resolution", "Resolution"),
                        ],
                        max_length=50,
                    ),
                ),
                ("was_accurate", models.BooleanField()),
                ("correct_value", models.CharField(blank=True, max_length=255, null=True)),
                ("comments", models.TextField(blank=True, null=True)),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="triage_feedback",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "triage_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="kb_triage.triagerequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Triage Feedback",
                "verbose_name_plural": "Triage Feedback",
            },
        ),
        migrations.CreateModel(
            name="ResolutionStep",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("step_number", models.IntegerField()),
                ("instruction", models.TextField()),
                ("expected_outcome", models.TextField(blank=True, null=True)),
                ("script", models.TextField(blank=True, null=True)),
                ("script_type", models.CharField(blank=True, max_length=20, null=True)),
                ("requires_approval", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("skipped", "Skipped"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "triage_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resolution_steps",
                        to="kb_triage.triagerequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resolution Step",
                "verbose_name_plural": "Resolution Steps",
                "ordering": ["step_number"],
            },
        ),
        migrations.CreateModel(
            name="TriageSuggestion",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "suggestion_type",
                    models.CharField(
                        choices=[
                            ("article", "Knowledge Article"),
                            ("script", "Script"),
                            ("escalation", "Escalation"),
                            ("workaround", "Workaround"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("content", models.TextField()),
                ("relevance_score", models.FloatField()),
                ("was_helpful", models.BooleanField(blank=True, null=True)),
                ("feedback", models.TextField(blank=True, null=True)),
                (
                    "source_article",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="suggestions",
                        to="kb_triage.knowledgearticle",
                    ),
                ),
                (
                    "triage_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suggestions",
                        to="kb_triage.triagerequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Triage Suggestion",
                "verbose_name_plural": "Triage Suggestions",
                "ordering": ["-relevance_score"],
            },
        ),
        migrations.AddIndex(
            model_name="knowledgearticle",
            index=models.Index(fields=["source", "category"], name="kb_triage_k_source__8e2062_idx"),
        ),
        migrations.AddIndex(
            model_name="knowledgearticle",
            index=models.Index(fields=["external_id", "source"], name="kb_triage_k_externa_374a23_idx"),
        ),
        migrations.AddIndex(
            model_name="triagefeedback",
            index=models.Index(fields=["triage_request", "feedback_type"], name="kb_triage_t_triage__86e3cb_idx"),
        ),
        migrations.AddIndex(
            model_name="resolutionstep",
            index=models.Index(fields=["triage_request", "step_number"], name="kb_triage_r_triage__fe3e97_idx"),
        ),
        migrations.AddIndex(
            model_name="triagesuggestion",
            index=models.Index(fields=["triage_request", "relevance_score"], name="kb_triage_t_triage__2953fd_idx"),
        ),
    ]
