# Generated by Django 5.1.15 on 2026-01-31 12:03

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("application_portfolio", "0002_alter_application_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ComplianceBaseline",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                (
                    "framework",
                    models.CharField(
                        choices=[
                            ("cis", "CIS Benchmarks"),
                            ("nist", "NIST CSF"),
                            ("soc2", "SOC 2"),
                            ("iso27001", "ISO 27001"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("version", models.CharField(max_length=50)),
                ("controls", models.JSONField(default=list, help_text="List of compliance controls")),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Compliance Baseline",
                "verbose_name_plural": "Compliance Baselines",
                "indexes": [models.Index(fields=["framework", "is_active"], name="secops_agen_framewo_90cd81_idx")],
            },
        ),
        migrations.CreateModel(
            name="SIEMConnection",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                (
                    "siem_type",
                    models.CharField(
                        choices=[
                            ("sentinel", "Microsoft Sentinel"),
                            ("splunk", "Splunk"),
                            ("qradar", "IBM QRadar"),
                            ("elastic", "Elastic SIEM"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("connection_config", models.JSONField(default=dict, help_text="SIEM connection configuration")),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "SIEM Connection",
                "verbose_name_plural": "SIEM Connections",
                "indexes": [models.Index(fields=["siem_type", "is_active"], name="secops_agen_siem_ty_6e745a_idx")],
            },
        ),
        migrations.CreateModel(
            name="Vulnerability",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("cve_id", models.CharField(db_index=True, max_length=50, unique=True)),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[("critical", "Critical"), ("high", "High"), ("medium", "Medium"), ("low", "Low")],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("cvss_score", models.FloatField(blank=True, null=True)),
                ("cvss_vector", models.CharField(blank=True, max_length=100, null=True)),
                ("exploitability_score", models.FloatField(blank=True, null=True)),
                ("published_date", models.DateField()),
                ("modified_date", models.DateField()),
                ("references", models.JSONField(default=list)),
                ("affected_products", models.JSONField(default=list)),
            ],
            options={
                "verbose_name": "Vulnerability",
                "verbose_name_plural": "Vulnerabilities",
                "ordering": ["-cvss_score", "-published_date"],
                "indexes": [
                    models.Index(fields=["severity", "cvss_score"], name="secops_agen_severit_f237cb_idx"),
                    models.Index(fields=["published_date"], name="secops_agen_publish_e31bf2_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="VulnerabilityInstance",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique correlation ID for audit trail and tracing",
                        unique=True,
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("asset_id", models.CharField(db_index=True, max_length=255)),
                ("asset_name", models.CharField(max_length=255)),
                ("detected_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("remediated", "Remediated"),
                            ("accepted", "Accepted Risk"),
                            ("false_positive", "False Positive"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=20,
                    ),
                ),
                ("remediation_due", models.DateField(blank=True, null=True)),
                ("remediated_at", models.DateTimeField(blank=True, null=True)),
                ("remediation_notes", models.TextField(blank=True, null=True)),
                (
                    "application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="application_portfolio.application",
                    ),
                ),
                (
                    "vulnerability",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instances",
                        to="secops_agent.vulnerability",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vulnerability Instance",
                "verbose_name_plural": "Vulnerability Instances",
            },
        ),
        migrations.CreateModel(
            name="RemediationPlan",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique correlation ID for audit trail and tracing",
                        unique=True,
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                (
                    "remediation_type",
                    models.CharField(
                        choices=[
                            ("patch", "Patch"),
                            ("config", "Configuration Change"),
                            ("compensating", "Compensating Control"),
                            ("upgrade", "Upgrade"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("steps", models.JSONField(default=list)),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("R1", "R1 - Low (Auto-execute allowed)"),
                            ("R2", "R2 - Medium (Policy-dependent approval)"),
                            ("R3", "R3 - High (Mandatory human approval)"),
                        ],
                        default="R2",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_approval", "Pending Approval"),
                            ("approved", "Approved"),
                            ("executing", "Executing"),
                            ("completed", "Completed"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_remediation_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vulnerability",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="remediation_plans",
                        to="secops_agent.vulnerability",
                    ),
                ),
                (
                    "affected_instances",
                    models.ManyToManyField(related_name="remediation_plans", to="secops_agent.vulnerabilityinstance"),
                ),
            ],
            options={
                "verbose_name": "Remediation Plan",
                "verbose_name_plural": "Remediation Plans",
            },
        ),
        migrations.CreateModel(
            name="VulnerabilityScanner",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                (
                    "scanner_type",
                    models.CharField(
                        choices=[
                            ("qualys", "Qualys"),
                            ("nessus", "Nessus"),
                            ("rapid7", "Rapid7"),
                            ("defender", "Microsoft Defender"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("connection_config", models.JSONField(default=dict, help_text="Scanner connection configuration")),
                ("sync_schedule", models.CharField(default="0 */6 * * *", help_text="Cron expression", max_length=50)),
                ("last_sync", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Vulnerability Scanner",
                "verbose_name_plural": "Vulnerability Scanners",
                "indexes": [models.Index(fields=["scanner_type", "is_active"], name="secops_agen_scanner_027fd4_idx")],
            },
        ),
        migrations.AddField(
            model_name="vulnerabilityinstance",
            name="scanner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="instances",
                to="secops_agent.vulnerabilityscanner",
            ),
        ),
        migrations.CreateModel(
            name="ComplianceCheck",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique correlation ID for audit trail and tracing",
                        unique=True,
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("asset_id", models.CharField(db_index=True, max_length=255)),
                ("check_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("overall_score", models.FloatField(help_text="Compliance score 0-100")),
                ("passed_controls", models.IntegerField(default=0)),
                ("failed_controls", models.IntegerField(default=0)),
                ("control_results", models.JSONField(default=dict, help_text="Detailed control check results")),
                (
                    "baseline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checks",
                        to="secops_agent.compliancebaseline",
                    ),
                ),
            ],
            options={
                "verbose_name": "Compliance Check",
                "verbose_name_plural": "Compliance Checks",
                "indexes": [
                    models.Index(fields=["baseline", "check_time"], name="secops_agen_baselin_6176ab_idx"),
                    models.Index(fields=["asset_id", "check_time"], name="secops_agen_asset_i_8c2008_idx"),
                    models.Index(fields=["correlation_id"], name="secops_agen_correla_a56688_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SecurityAlert",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique correlation ID for audit trail and tracing",
                        unique=True,
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("alert_id", models.CharField(db_index=True, max_length=255)),
                ("title", models.CharField(max_length=500)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("informational", "Informational"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("source", models.CharField(max_length=255)),
                ("affected_assets", models.JSONField(default=list)),
                ("alert_time", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("investigating", "Investigating"),
                            ("resolved", "Resolved"),
                            ("false_positive", "False Positive"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "remediation_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="security_alerts",
                        to="secops_agent.remediationplan",
                    ),
                ),
                (
                    "siem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="secops_agent.siemconnection",
                    ),
                ),
                (
                    "related_vulnerabilities",
                    models.ManyToManyField(blank=True, related_name="security_alerts", to="secops_agent.vulnerability"),
                ),
            ],
            options={
                "verbose_name": "Security Alert",
                "verbose_name_plural": "Security Alerts",
                "indexes": [
                    models.Index(fields=["siem", "status"], name="secops_agen_siem_id_27d747_idx"),
                    models.Index(fields=["severity", "status"], name="secops_agen_severit_d21bce_idx"),
                    models.Index(fields=["alert_time"], name="secops_agen_alert_t_b6ef8e_idx"),
                    models.Index(fields=["correlation_id"], name="secops_agen_correla_8feb28_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="remediationplan",
            index=models.Index(fields=["status", "risk_level"], name="secops_agen_status_97bf5e_idx"),
        ),
        migrations.AddIndex(
            model_name="remediationplan",
            index=models.Index(fields=["vulnerability", "status"], name="secops_agen_vulnera_2379b5_idx"),
        ),
        migrations.AddIndex(
            model_name="remediationplan",
            index=models.Index(fields=["correlation_id"], name="secops_agen_correla_83e446_idx"),
        ),
        migrations.AddIndex(
            model_name="vulnerabilityinstance",
            index=models.Index(fields=["vulnerability", "status"], name="secops_agen_vulnera_1ef29e_idx"),
        ),
        migrations.AddIndex(
            model_name="vulnerabilityinstance",
            index=models.Index(fields=["asset_id", "status"], name="secops_agen_asset_i_c1e03d_idx"),
        ),
        migrations.AddIndex(
            model_name="vulnerabilityinstance",
            index=models.Index(fields=["status", "remediation_due"], name="secops_agen_status_a3a8bc_idx"),
        ),
        migrations.AddIndex(
            model_name="vulnerabilityinstance",
            index=models.Index(fields=["correlation_id"], name="secops_agen_correla_548d6d_idx"),
        ),
    ]
