# Generated by Django 5.0.14 on 2026-01-23 12:01

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("hostname", models.CharField(db_index=True, max_length=255)),
                (
                    "platform",
                    models.CharField(
                        choices=[("windows", "Windows"), ("macos", "macOS"), ("linux", "Linux")], max_length=20
                    ),
                ),
                ("platform_version", models.CharField(max_length=100)),
                ("agent_version", models.CharField(max_length=50)),
                ("first_seen_at", models.DateTimeField(auto_now_add=True)),
                ("last_heartbeat_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("registration_key", models.CharField(db_index=True, max_length=255, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ONLINE", "Online"),
                            ("OFFLINE", "Offline"),
                            ("DEGRADED", "Degraded"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        db_index=True,
                        default="UNKNOWN",
                        max_length=20,
                    ),
                ),
                ("last_error", models.TextField(blank=True, null=True)),
                ("cpu_cores", models.IntegerField(default=0)),
                ("memory_mb", models.IntegerField(default=0)),
                ("disk_gb", models.IntegerField(default=0)),
                ("ip_address", models.GenericIPAddressField()),
                ("mac_address", models.CharField(max_length=17)),
                ("tags", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "agents",
                "ordering": ["-last_heartbeat_at"],
                "indexes": [
                    models.Index(fields=["platform", "status"], name="agents_platfor_94deb1_idx"),
                    models.Index(fields=["last_heartbeat_at"], name="agents_last_he_567342_idx"),
                    models.Index(fields=["hostname"], name="agents_hostnam_f647ad_idx"),
                    models.Index(fields=["status"], name="agents_status_f5ff61_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AgentTask",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("DEPLOY", "Package Deployment"),
                            ("REMEDIATE", "Remediation Script"),
                            ("COLLECT", "Telemetry Collection"),
                            ("UPDATE", "Agent Update"),
                            ("HEALTHCHECK", "Health Check"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ASSIGNED", "Assigned"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("TIMEOUT", "Timeout"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("payload", models.JSONField(default=dict)),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("timeout_seconds", models.IntegerField(default=3600)),
                ("result", models.JSONField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("exit_code", models.IntegerField(blank=True, null=True)),
                ("correlation_id", models.CharField(db_index=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="tasks", to="agent_management.agent"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "agent_tasks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentOfflineQueue",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("queued_at", models.DateTimeField(auto_now_add=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("retry_count", models.IntegerField(default=0)),
                ("max_retries", models.IntegerField(default=3)),
                ("next_retry_at", models.DateTimeField(blank=True, null=True)),
                ("correlation_id", models.CharField(db_index=True, max_length=100)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offline_queue",
                        to="agent_management.agent",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="agent_management.agenttask"),
                ),
            ],
            options={
                "db_table": "agent_offline_queue",
                "ordering": ["queued_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentTelemetry",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("cpu_usage_percent", models.FloatField()),
                ("memory_usage_percent", models.FloatField()),
                ("disk_usage_percent", models.FloatField()),
                ("network_bytes_sent", models.BigIntegerField(default=0)),
                ("network_bytes_received", models.BigIntegerField(default=0)),
                ("process_count", models.IntegerField(default=0)),
                ("installed_software", models.JSONField(blank=True, default=list)),
                ("collected_at", models.DateTimeField()),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("correlation_id", models.CharField(db_index=True, max_length=100)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telemetry",
                        to="agent_management.agent",
                    ),
                ),
            ],
            options={
                "db_table": "agent_telemetry",
                "ordering": ["-collected_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentDeploymentStatus",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("deployment_intent_id", models.UUIDField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("DOWNLOADING", "Downloading"),
                            ("INSTALLING", "Installing"),
                            ("INSTALLED", "Installed"),
                            ("FAILED", "Failed"),
                            ("ROLLED_BACK", "Rolled Back"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("progress_percent", models.IntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("exit_code", models.IntegerField(blank=True, null=True)),
                ("package_name", models.CharField(max_length=255)),
                ("package_version", models.CharField(max_length=100)),
                ("package_hash", models.CharField(max_length=64)),
                ("correlation_id", models.CharField(db_index=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deployments",
                        to="agent_management.agent",
                    ),
                ),
            ],
            options={
                "db_table": "agent_deployment_status",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["agent", "status"], name="agent_deplo_agent_i_4212d9_idx"),
                    models.Index(fields=["deployment_intent_id", "status"], name="agent_deplo_deploym_b85799_idx"),
                    models.Index(fields=["status"], name="agent_deplo_status_1f6487_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="agenttask",
            index=models.Index(fields=["agent", "status"], name="agent_tasks_agent_i_a2eef7_idx"),
        ),
        migrations.AddIndex(
            model_name="agenttask",
            index=models.Index(fields=["task_type", "status"], name="agent_tasks_task_ty_47c56b_idx"),
        ),
        migrations.AddIndex(
            model_name="agenttask",
            index=models.Index(fields=["correlation_id"], name="agent_tasks_correla_10d03a_idx"),
        ),
        migrations.AddIndex(
            model_name="agenttask",
            index=models.Index(fields=["status", "created_at"], name="agent_tasks_status_601821_idx"),
        ),
        migrations.AddIndex(
            model_name="agentofflinequeue",
            index=models.Index(fields=["agent", "delivered_at"], name="agent_offli_agent_i_9f8913_idx"),
        ),
        migrations.AddIndex(
            model_name="agentofflinequeue",
            index=models.Index(fields=["delivered_at"], name="agent_offli_deliver_440dc5_idx"),
        ),
        migrations.AddIndex(
            model_name="agentofflinequeue",
            index=models.Index(fields=["next_retry_at"], name="agent_offli_next_re_1ebbf4_idx"),
        ),
        migrations.AddIndex(
            model_name="agenttelemetry",
            index=models.Index(fields=["agent", "collected_at"], name="agent_telem_agent_i_0c7eac_idx"),
        ),
        migrations.AddIndex(
            model_name="agenttelemetry",
            index=models.Index(fields=["collected_at"], name="agent_telem_collect_666d36_idx"),
        ),
    ]
