# Generated by Django 5.1.15 on 2026-01-24 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packaging_factory', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='packagingpipeline',
            new_name='packaging_p_package_08b3f4_idx',
            old_name='packaging_p_package_idx',
        ),
        migrations.RenameIndex(
            model_name='packagingpipeline',
            new_name='packaging_p_status_4a1dc3_idx',
            old_name='packaging_p_status_idx',
        ),
        migrations.RenameIndex(
            model_name='packagingpipeline',
            new_name='packaging_p_policy__3ea73d_idx',
            old_name='packaging_p_policy_idx',
        ),
        migrations.RenameIndex(
            model_name='packagingstagelog',
            new_name='packaging_s_pipelin_3e6428_idx',
            old_name='packaging_s_pipeline_idx',
        ),
    ]
