# Generated by Django 5.1.15 on 2026-01-31 06:26

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CodeRepository",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(help_text="Display name for this repository", max_length=255)),
                (
                    "repo_type",
                    models.CharField(
                        choices=[("github", "GitHub"), ("gitlab", "GitLab"), ("local", "Local Filesystem")],
                        default="local",
                        max_length=20,
                    ),
                ),
                ("url", models.URLField(blank=True, help_text="Repository URL (for GitHub/GitLab)", null=True)),
                (
                    "local_path",
                    models.CharField(blank=True, help_text="Local filesystem path", max_length=500, null=True),
                ),
                ("default_branch", models.CharField(default="main", max_length=100)),
                (
                    "auth_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Authentication configuration (token, credentials)",
                        null=True,
                    ),
                ),
                ("last_analyzed", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "verbose_name": "Code Repository",
                "verbose_name_plural": "Code Repositories",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["is_active", "repo_type"], name="documentati_is_acti_9520e9_idx"),
                    models.Index(fields=["name"], name="documentati_name_3c8226_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="CodeAnalysis",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique correlation ID for audit trail and tracing",
                        unique=True,
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("commit_sha", models.CharField(blank=True, help_text="Git commit SHA", max_length=40)),
                ("branch", models.CharField(default="main", max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "summary",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Analysis summary: modules, classes, functions counts",
                        null=True,
                    ),
                ),
                ("errors", models.JSONField(blank=True, default=list, help_text="Analysis errors")),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to="documentation_agent.coderepository",
                    ),
                ),
            ],
            options={
                "verbose_name": "Code Analysis",
                "verbose_name_plural": "Code Analyses",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentationTemplate",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(help_text="Template name", max_length=255)),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("api", "API Documentation"),
                            ("readme", "README"),
                            ("architecture", "Architecture Diagram"),
                            ("runbook", "Runbook"),
                            ("adr", "Architecture Decision Record"),
                            ("test", "Test Documentation"),
                        ],
                        help_text="Document type this template applies to",
                        max_length=50,
                    ),
                ),
                ("template_content", models.TextField(help_text="Template content with variable placeholders")),
                ("variables", models.JSONField(blank=True, default=list, help_text="List of available variables")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "verbose_name": "Documentation Template",
                "verbose_name_plural": "Documentation Templates",
                "ordering": ["doc_type", "name"],
                "indexes": [
                    models.Index(fields=["doc_type", "is_active"], name="documentati_doc_typ_dc50f4_idx"),
                    models.Index(fields=["name"], name="documentati_name_e7d716_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="DocumentedModule",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("module_path", models.CharField(help_text="File path relative to repo root", max_length=500)),
                (
                    "module_type",
                    models.CharField(
                        choices=[
                            ("package", "Package/Module"),
                            ("class", "Class"),
                            ("function", "Function/Method"),
                            ("endpoint", "API Endpoint"),
                            ("component", "React Component"),
                            ("hook", "React Hook"),
                            ("type", "TypeScript Type"),
                        ],
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(help_text="Module/class/function name", max_length=255)),
                ("docstring", models.TextField(blank=True, help_text="Extracted docstring", null=True)),
                ("generated_doc", models.TextField(blank=True, help_text="Generated documentation", null=True)),
                ("signature", models.TextField(blank=True, help_text="Function/class signature", null=True)),
                ("dependencies", models.JSONField(blank=True, default=list, help_text="List of dependencies")),
                ("metadata", models.JSONField(blank=True, default=dict, help_text="Additional metadata")),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modules",
                        to="documentation_agent.codeanalysis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documented Module",
                "verbose_name_plural": "Documented Modules",
                "ordering": ["module_path", "name"],
            },
        ),
        migrations.CreateModel(
            name="GeneratedDocument",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique correlation ID for audit trail and tracing",
                        unique=True,
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("api", "API Documentation"),
                            ("readme", "README"),
                            ("architecture", "Architecture Diagram"),
                            ("runbook", "Runbook"),
                            ("adr", "Architecture Decision Record"),
                            ("test", "Test Documentation"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField(help_text="Document content")),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("markdown", "Markdown"),
                            ("openapi", "OpenAPI/Swagger"),
                            ("mermaid", "Mermaid Diagram"),
                        ],
                        default="markdown",
                        max_length=20,
                    ),
                ),
                (
                    "target_path",
                    models.CharField(
                        blank=True, help_text="Target file path for publishing", max_length=500, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("review", "Under Review"), ("published", "Published")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="documentation_agent.codeanalysis",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Generated Document",
                "verbose_name_plural": "Generated Documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="codeanalysis",
            index=models.Index(fields=["repository", "status"], name="documentati_reposit_ae39f4_idx"),
        ),
        migrations.AddIndex(
            model_name="codeanalysis",
            index=models.Index(fields=["correlation_id"], name="documentati_correla_9bdac4_idx"),
        ),
        migrations.AddIndex(
            model_name="codeanalysis",
            index=models.Index(fields=["status", "started_at"], name="documentati_status_ddd592_idx"),
        ),
        migrations.AddIndex(
            model_name="documentedmodule",
            index=models.Index(fields=["analysis", "module_type"], name="documentati_analysi_f7aac8_idx"),
        ),
        migrations.AddIndex(
            model_name="documentedmodule",
            index=models.Index(fields=["module_path"], name="documentati_module__cb599d_idx"),
        ),
        migrations.AddIndex(
            model_name="generateddocument",
            index=models.Index(fields=["analysis", "doc_type"], name="documentati_analysi_84a739_idx"),
        ),
        migrations.AddIndex(
            model_name="generateddocument",
            index=models.Index(fields=["correlation_id"], name="documentati_correla_240eb1_idx"),
        ),
        migrations.AddIndex(
            model_name="generateddocument",
            index=models.Index(fields=["status", "doc_type"], name="documentati_status_ae8144_idx"),
        ),
    ]
