# Generated by Django 5.1.15 on 2026-01-31 12:03

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CMDBConnection",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(help_text="Display name for this connection", max_length=255)),
                (
                    "instance_url",
                    models.URLField(help_text="ServiceNow instance URL (e.g., https://instance.service-now.com)"),
                ),
                (
                    "auth_type",
                    models.CharField(
                        choices=[("basic", "Basic Authentication"), ("oauth", "OAuth 2.0"), ("api_key", "API Key")],
                        default="basic",
                        max_length=50,
                    ),
                ),
                (
                    "credentials",
                    models.JSONField(default=dict, help_text="Authentication credentials (encrypted in production)"),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("last_sync", models.DateTimeField(blank=True, null=True)),
                ("last_sync_status", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "verbose_name": "CMDB Connection",
                "verbose_name_plural": "CMDB Connections",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["is_active", "created_at"], name="cmdb_integr_is_acti_5ac8b2_idx"),
                    models.Index(fields=["name"], name="cmdb_integr_name_7d361a_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="CMDBSyncRecord",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique correlation ID for audit trail and tracing",
                        unique=True,
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "sync_type",
                    models.CharField(
                        choices=[
                            ("full", "Full Sync"),
                            ("incremental", "Incremental Sync"),
                            ("targeted", "Targeted Sync"),
                            ("validation", "Validation Only"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("records_processed", models.IntegerField(default=0)),
                ("records_created", models.IntegerField(default=0)),
                ("records_updated", models.IntegerField(default=0)),
                ("records_skipped", models.IntegerField(default=0)),
                ("validation_errors", models.IntegerField(default=0)),
                ("errors", models.JSONField(default=list)),
                (
                    "quality_score",
                    models.FloatField(blank=True, help_text="Overall data quality score (0-100)", null=True),
                ),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_records",
                        to="cmdb_integration.cmdbconnection",
                    ),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cmdb_sync_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "CMDB Sync Record",
                "verbose_name_plural": "CMDB Sync Records",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="CMDBDiscrepancy",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("ci_sys_id", models.CharField(blank=True, help_text="ServiceNow CI sys_id", max_length=100)),
                ("ci_name", models.CharField(max_length=255)),
                ("ci_class", models.CharField(help_text="CMDB class/table", max_length=255)),
                (
                    "discrepancy_type",
                    models.CharField(
                        choices=[
                            ("missing", "Missing in CMDB"),
                            ("mismatch", "Value Mismatch"),
                            ("orphan", "Orphan Record"),
                            ("duplicate", "Duplicate Record"),
                            ("stale", "Stale Data"),
                            ("incomplete", "Incomplete Record"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("field_name", models.CharField(blank=True, max_length=255)),
                ("source_value", models.TextField(blank=True, null=True)),
                ("cmdb_value", models.TextField(blank=True, null=True)),
                ("source_system", models.CharField(blank=True, max_length=50)),
                (
                    "recommended_action",
                    models.CharField(
                        choices=[
                            ("create", "Create CI"),
                            ("update", "Update CI"),
                            ("delete", "Delete CI"),
                            ("merge", "Merge Records"),
                            ("review", "Manual Review"),
                            ("ignore", "Ignore"),
                        ],
                        max_length=50,
                    ),
                ),
                ("confidence_score", models.FloatField(default=0.0, help_text="Confidence in recommendation (0-1)")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("applied", "Applied"),
                            ("ignored", "Ignored"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True)),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_cmdb_discrepancies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sync_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discrepancies",
                        to="cmdb_integration.cmdbsyncrecord",
                    ),
                ),
            ],
            options={
                "verbose_name": "CMDB Discrepancy",
                "verbose_name_plural": "CMDB Discrepancies",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CMDBDataQualityReport",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique correlation ID for audit trail and tracing",
                        unique=True,
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("overall_score", models.FloatField(help_text="Overall quality score (0-100)")),
                ("completeness_score", models.FloatField(help_text="Data completeness score (0-100)")),
                ("accuracy_score", models.FloatField(help_text="Data accuracy score (0-100)")),
                ("consistency_score", models.FloatField(help_text="Data consistency score (0-100)")),
                ("timeliness_score", models.FloatField(help_text="Data timeliness score (0-100)")),
                ("total_cis", models.IntegerField(default=0)),
                ("cis_with_issues", models.IntegerField(default=0)),
                ("critical_issues", models.IntegerField(default=0)),
                ("warnings", models.IntegerField(default=0)),
                ("table_scores", models.JSONField(default=dict, help_text="Quality scores per CMDB table")),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quality_reports",
                        to="cmdb_integration.cmdbconnection",
                    ),
                ),
                (
                    "sync_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quality_reports",
                        to="cmdb_integration.cmdbsyncrecord",
                    ),
                ),
            ],
            options={
                "verbose_name": "CMDB Data Quality Report",
                "verbose_name_plural": "CMDB Data Quality Reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CMDBTableMapping",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("sccm", "SCCM"),
                            ("intune", "Intune"),
                            ("discovery", "ServiceNow Discovery"),
                            ("deployment", "Deployment Pipeline"),
                            ("monitoring", "Monitoring System"),
                            ("manual", "Manual Import"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("source_table", models.CharField(help_text="Source system table/entity name", max_length=255)),
                (
                    "cmdb_table",
                    models.CharField(help_text="Target CMDB table (e.g., cmdb_ci_computer)", max_length=255),
                ),
                (
                    "field_mappings",
                    models.JSONField(default=dict, help_text="Field mapping configuration: {source_field: cmdb_field}"),
                ),
                ("sync_enabled", models.BooleanField(db_index=True, default=True)),
                (
                    "sync_direction",
                    models.CharField(
                        choices=[
                            ("source_to_cmdb", "Source → CMDB"),
                            ("cmdb_to_source", "CMDB → Source"),
                            ("bidirectional", "Bidirectional"),
                        ],
                        default="source_to_cmdb",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=100, help_text="Priority for conflict resolution (lower = higher priority)"
                    ),
                ),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="table_mappings",
                        to="cmdb_integration.cmdbconnection",
                    ),
                ),
            ],
            options={
                "verbose_name": "CMDB Table Mapping",
                "verbose_name_plural": "CMDB Table Mappings",
                "ordering": ["priority", "source_type"],
            },
        ),
        migrations.CreateModel(
            name="CMDBValidationRule",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("cmdb_table", models.CharField(db_index=True, max_length=255)),
                (
                    "field_name",
                    models.CharField(blank=True, help_text="Field to validate (empty for table-level)", max_length=255),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("required", "Required Field"),
                            ("format", "Format Validation"),
                            ("reference", "Referential Integrity"),
                            ("range", "Value Range"),
                            ("regex", "Regular Expression"),
                            ("custom", "Custom Rule"),
                        ],
                        max_length=50,
                    ),
                ),
                ("rule_config", models.JSONField(default=dict, help_text="Rule configuration (depends on rule_type)")),
                (
                    "severity",
                    models.CharField(
                        choices=[("error", "Error"), ("warning", "Warning"), ("info", "Info")],
                        default="warning",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "auto_fix",
                    models.BooleanField(default=False, help_text="Whether to automatically apply fix when possible"),
                ),
            ],
            options={
                "verbose_name": "CMDB Validation Rule",
                "verbose_name_plural": "CMDB Validation Rules",
                "ordering": ["cmdb_table", "field_name", "severity"],
                "indexes": [
                    models.Index(fields=["cmdb_table", "is_active"], name="cmdb_integr_cmdb_ta_7fb6c0_idx"),
                    models.Index(fields=["rule_type"], name="cmdb_integr_rule_ty_6d2e39_idx"),
                    models.Index(fields=["severity"], name="cmdb_integr_severit_b97dce_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="cmdbsyncrecord",
            index=models.Index(fields=["connection", "status"], name="cmdb_integr_connect_14a484_idx"),
        ),
        migrations.AddIndex(
            model_name="cmdbsyncrecord",
            index=models.Index(fields=["sync_type", "started_at"], name="cmdb_integr_sync_ty_e41fc7_idx"),
        ),
        migrations.AddIndex(
            model_name="cmdbsyncrecord",
            index=models.Index(fields=["correlation_id"], name="cmdb_integr_correla_3a5d53_idx"),
        ),
        migrations.AddIndex(
            model_name="cmdbsyncrecord",
            index=models.Index(fields=["status", "started_at"], name="cmdb_integr_status_5fa4b9_idx"),
        ),
        migrations.AddIndex(
            model_name="cmdbdiscrepancy",
            index=models.Index(fields=["sync_record", "status"], name="cmdb_integr_sync_re_62b6d8_idx"),
        ),
        migrations.AddIndex(
            model_name="cmdbdiscrepancy",
            index=models.Index(fields=["discrepancy_type", "status"], name="cmdb_integr_discrep_1dbead_idx"),
        ),
        migrations.AddIndex(
            model_name="cmdbdiscrepancy",
            index=models.Index(fields=["ci_sys_id"], name="cmdb_integr_ci_sys__fc6279_idx"),
        ),
        migrations.AddIndex(
            model_name="cmdbdiscrepancy",
            index=models.Index(fields=["ci_class", "status"], name="cmdb_integr_ci_clas_8f8bfc_idx"),
        ),
        migrations.AddIndex(
            model_name="cmdbdiscrepancy",
            index=models.Index(fields=["recommended_action"], name="cmdb_integr_recomme_55cead_idx"),
        ),
        migrations.AddIndex(
            model_name="cmdbdataqualityreport",
            index=models.Index(fields=["connection", "created_at"], name="cmdb_integr_connect_81bbe4_idx"),
        ),
        migrations.AddIndex(
            model_name="cmdbdataqualityreport",
            index=models.Index(fields=["overall_score"], name="cmdb_integr_overall_439e8e_idx"),
        ),
        migrations.AddIndex(
            model_name="cmdbdataqualityreport",
            index=models.Index(fields=["correlation_id"], name="cmdb_integr_correla_a25066_idx"),
        ),
        migrations.AddIndex(
            model_name="cmdbtablemapping",
            index=models.Index(fields=["connection", "source_type"], name="cmdb_integr_connect_67973b_idx"),
        ),
        migrations.AddIndex(
            model_name="cmdbtablemapping",
            index=models.Index(fields=["cmdb_table"], name="cmdb_integr_cmdb_ta_1dba94_idx"),
        ),
        migrations.AddIndex(
            model_name="cmdbtablemapping",
            index=models.Index(fields=["sync_enabled"], name="cmdb_integr_sync_en_8b6156_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="cmdbtablemapping",
            unique_together={("connection", "source_type", "source_table", "cmdb_table")},
        ),
    ]
