# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 BuildWorks.AI
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eucora-static-pvc
  namespace: eucora
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
