# Generated by Django 5.0.14 on 2026-01-30 06:21

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("application_portfolio", "0002_alter_application_options_and_more"),
        ("license_management", "0002_alter_assignment_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        help_text="Portfolio name (e.g., 'Finance Applications', 'HR Suite')", max_length=255
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "scope",
                    models.JSONField(
                        default=dict,
                        help_text='\n        Portfolio scope definition:\n        {\n            "business_unit": "Finance",\n            "geography": ["US", "EMEA"],\n            "acquisition_boundary": "acquired_2024",\n            "site_classes": ["online", "intermittent", "air_gapped"]\n        }\n        ',  # noqa: E501
                    ),
                ),
                (
                    "budget_annual",
                    models.DecimalField(
                        decimal_places=2, default=0, help_text="Annual budget for this portfolio (USD)", max_digits=12
                    ),
                ),
                ("cost_center", models.CharField(blank=True, help_text="Finance cost center code", max_length=100)),
                ("is_active", models.BooleanField(db_index=True, default=True, help_text="Soft delete flag")),
                (
                    "total_applications",
                    models.IntegerField(default=0, help_text="Count of active applications in portfolio"),
                ),
                (
                    "total_licenses_entitled",
                    models.IntegerField(default=0, help_text="Total licenses entitled across all SKUs"),
                ),
                (
                    "total_licenses_consumed",
                    models.IntegerField(default=0, help_text="Total licenses consumed across all SKUs"),
                ),
                (
                    "total_cost_annual",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total annual cost (licenses + deployment overhead)",
                        max_digits=12,
                    ),
                ),
                ("health_score", models.FloatField(default=0.0, help_text="Aggregate health score (0-100)")),
                ("compliance_score", models.FloatField(default=0.0, help_text="Aggregate compliance score (0-100)")),
                (
                    "last_metrics_update",
                    models.DateTimeField(blank=True, help_text="Last time metrics were recomputed", null=True),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        help_text="Portfolio Manager responsible for this portfolio",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_portfolios",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "portfolio_management_portfolio",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="LicenseTrueUpForecast",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "forecast_period",
                    models.CharField(help_text="Forecast period (e.g., 'Q1_2027', 'FY2027')", max_length=20),
                ),
                (
                    "forecast_generated_at",
                    models.DateTimeField(auto_now_add=True, help_text="When forecast was generated"),
                ),
                (
                    "forecast_horizon_days",
                    models.IntegerField(default=180, help_text="Forecast horizon in days (e.g., 180 = 6 months)"),
                ),
                ("entitled_quantity_current", models.IntegerField(help_text="Current entitled licenses")),
                ("consumed_quantity_current", models.IntegerField(help_text="Current consumed licenses")),
                ("utilization_current_percent", models.FloatField(help_text="(consumed / entitled) × 100")),
                (
                    "consumed_quantity_forecast",
                    models.IntegerField(help_text="Forecasted consumption at end of period"),
                ),
                ("consumption_growth_percent", models.FloatField(help_text="Projected growth rate (%)")),
                (
                    "additional_licenses_needed",
                    models.IntegerField(help_text="Additional licenses needed (if forecast > entitled)"),
                ),
                (
                    "estimated_cost_impact",
                    models.DecimalField(
                        decimal_places=2, help_text="Estimated cost of additional licenses (USD)", max_digits=12
                    ),
                ),
                ("confidence_percent", models.FloatField(default=0.0, help_text="Forecast confidence (0-100)")),
                (
                    "mitigation_recommendations",
                    models.JSONField(
                        default=list,
                        help_text='\n        List of mitigation strategies:\n        [\n            {\n                "strategy": "right_sizing",\n                "description": "Reduce over-entitled SKUs",\n                "licenses_saved": 50,\n                "cost_savings": 25000.00\n            },\n            {\n                "strategy": "license_harvesting",\n                "description": "Reclaim unused licenses",\n                "licenses_saved": 30,\n                "cost_savings": 15000.00\n            }\n        ]\n        ',  # noqa: E501
                    ),
                ),
                (
                    "potential_savings",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total potential savings from mitigations (USD)",
                        max_digits=12,
                    ),
                ),
                ("model_version", models.CharField(default="v1.0", help_text="Forecast model version", max_length=20)),
                ("correlation_id", models.UUIDField(default=uuid.uuid4, help_text="Correlation ID for audit trail")),
                (
                    "input_data_summary",
                    models.JSONField(default=dict, help_text="Summary of input data used for forecast"),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        help_text="Vendor for this forecast",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="true_up_forecasts",
                        to="license_management.vendor",
                    ),
                ),
                (
                    "portfolio",
                    models.ForeignKey(
                        blank=True,
                        help_text="Portfolio context (null = enterprise-wide)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="true_up_forecasts",
                        to="portfolio_management.portfolio",
                    ),
                ),
            ],
            options={
                "db_table": "portfolio_management_true_up_forecast",
                "ordering": ["-forecast_generated_at"],
            },
        ),
        migrations.CreateModel(
            name="ApplicationOwnership",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ownership_type",
                    models.CharField(
                        choices=[("PRIMARY", "Primary Owner"), ("SECONDARY", "Secondary Owner / Backup")],
                        default="PRIMARY",
                        help_text="Type of ownership (PRIMARY or SECONDARY)",
                        max_length=20,
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True, help_text="When ownership was assigned")),
                ("is_active", models.BooleanField(db_index=True, default=True, help_text="Soft delete flag")),
                (
                    "application",
                    models.ForeignKey(
                        help_text="Application being owned",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ownerships",
                        to="application_portfolio.application",
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        help_text="Portfolio Manager who assigned ownership",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ownership_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Application Manager who owns this application",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="application_ownerships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "portfolio",
                    models.ForeignKey(
                        help_text="Portfolio this application belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="application_ownerships",
                        to="portfolio_management.portfolio",
                    ),
                ),
            ],
            options={
                "db_table": "portfolio_management_ownership",
                "ordering": ["-assigned_at"],
            },
        ),
        migrations.CreateModel(
            name="ApplicationManagerPerformance",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("recorded_at", models.DateTimeField(db_index=True, help_text="Snapshot timestamp")),
                ("period_start", models.DateTimeField(help_text="Start of measurement period (e.g., start of month)")),
                ("period_end", models.DateTimeField(help_text="End of measurement period (e.g., end of month)")),
                ("deployments_total", models.IntegerField(default=0, help_text="Total deployments in period")),
                (
                    "deployments_successful",
                    models.IntegerField(default=0, help_text="Successful deployments (reached Global ring)"),
                ),
                (
                    "deployments_failed",
                    models.IntegerField(default=0, help_text="Failed deployments (never reached Global)"),
                ),
                (
                    "deployments_rolled_back",
                    models.IntegerField(default=0, help_text="Deployments that were rolled back"),
                ),
                (
                    "avg_deployment_duration_days",
                    models.FloatField(default=0.0, help_text="Average days from CAB submission to Global completion"),
                ),
                ("success_rate_percent", models.FloatField(default=0.0, help_text="(successful / total) × 100")),
                ("applications_total", models.IntegerField(default=0, help_text="Total applications owned")),
                ("applications_healthy", models.IntegerField(default=0, help_text="Applications with health ≥ 90%")),
                (
                    "applications_degraded",
                    models.IntegerField(default=0, help_text="Applications with 70% ≤ health < 90%"),
                ),
                ("applications_critical", models.IntegerField(default=0, help_text="Applications with health < 70%")),
                (
                    "avg_health_score",
                    models.FloatField(default=0.0, help_text="Average health score across applications (0-100)"),
                ),
                ("licenses_entitled", models.IntegerField(default=0, help_text="Total licenses entitled")),
                ("licenses_consumed", models.IntegerField(default=0, help_text="Total licenses consumed")),
                (
                    "licenses_wasted",
                    models.IntegerField(
                        default=0, help_text="Over-entitled licenses (entitled - consumed, if positive)"
                    ),
                ),
                ("utilization_percent", models.FloatField(default=0.0, help_text="(consumed / entitled) × 100")),
                ("incidents_total", models.IntegerField(default=0, help_text="Total incidents in period")),
                ("incidents_resolved", models.IntegerField(default=0, help_text="Incidents resolved in period")),
                ("avg_mttr_hours", models.FloatField(default=0.0, help_text="Mean time to resolution (hours)")),
                (
                    "composite_score",
                    models.FloatField(
                        default=0.0,
                        help_text="\n        Composite performance score (0-100):\n        - Deployment success rate: 30%\n        - Avg health score: 25%\n        - License utilization: 20%\n        - Time-to-deployment: 15%\n        - MTTR: 10%\n        ",  # noqa: E501
                    ),
                ),
                (
                    "calculation_metadata",
                    models.JSONField(default=dict, help_text="Calculation inputs and weights for transparency"),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        help_text="Application Manager",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "portfolio",
                    models.ForeignKey(
                        help_text="Portfolio context for this performance snapshot",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manager_performance_snapshots",
                        to="portfolio_management.portfolio",
                    ),
                ),
            ],
            options={
                "db_table": "portfolio_management_performance",
                "ordering": ["-recorded_at"],
            },
        ),
        migrations.CreateModel(
            name="PackagingRequest",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "version_identifier",
                    models.CharField(help_text="Version being packaged (e.g., '2.5.1')", max_length=100),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Assignment"),
                            ("ASSIGNED", "Assigned to Engineer"),
                            ("IN_PROGRESS", "Packaging in Progress"),
                            ("VALIDATION", "Lab Validation"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="PENDING",
                        help_text="Current status of packaging request",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low Priority"),
                            ("MEDIUM", "Medium Priority"),
                            ("HIGH", "High Priority"),
                            ("URGENT", "Urgent"),
                        ],
                        default="MEDIUM",
                        help_text="Request priority",
                        max_length=20,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True, help_text="When request was submitted")),
                (
                    "assigned_at",
                    models.DateTimeField(blank=True, help_text="When request was assigned to engineer", null=True),
                ),
                ("completed_at", models.DateTimeField(blank=True, help_text="When packaging was completed", null=True)),
                (
                    "requirements",
                    models.JSONField(
                        default=dict,
                        help_text='\n        Packaging requirements:\n        {\n            "platforms": ["windows", "macos"],\n            "signing_required": true,\n            "detection_rules": {...},\n            "dependencies": [...],\n            "notes": "Special instructions"\n        }\n        ',  # noqa: E501
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Engineer notes, issues, resolutions")),
                ("correlation_id", models.UUIDField(default=uuid.uuid4, help_text="Correlation ID for audit trail")),
                (
                    "application",
                    models.ForeignKey(
                        help_text="Application being packaged",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="packaging_requests",
                        to="application_portfolio.application",
                    ),
                ),
                (
                    "artifact",
                    models.ForeignKey(
                        blank=True,
                        help_text="Completed artifact (when status=COMPLETED)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="packaging_requests",
                        to="application_portfolio.packageartifact",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="Packaging Engineer assigned to this request",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="packaging_requests_assigned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        help_text="Application Manager who requested packaging",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="packaging_requests_initiated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "portfolio_management_packaging_request",
                "ordering": ["-requested_at"],
                "indexes": [
                    models.Index(fields=["status", "priority"], name="portfolio_m_status_bb75cf_idx"),
                    models.Index(fields=["requested_by", "status"], name="portfolio_m_request_91bfa4_idx"),
                    models.Index(fields=["assigned_to", "status"], name="portfolio_m_assigne_d967f0_idx"),
                    models.Index(fields=["application"], name="portfolio_m_applica_cb6bfe_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="portfolio",
            index=models.Index(fields=["manager", "is_active"], name="portfolio_m_manager_47ad48_idx"),
        ),
        migrations.AddIndex(
            model_name="portfolio",
            index=models.Index(fields=["health_score"], name="portfolio_m_health__8ecffc_idx"),
        ),
        migrations.AddIndex(
            model_name="portfolio",
            index=models.Index(fields=["compliance_score"], name="portfolio_m_complia_9e14d4_idx"),
        ),
        migrations.AddIndex(
            model_name="licensetrueupforecast",
            index=models.Index(fields=["vendor", "forecast_period"], name="portfolio_m_vendor__303dc1_idx"),
        ),
        migrations.AddIndex(
            model_name="licensetrueupforecast",
            index=models.Index(fields=["portfolio", "forecast_period"], name="portfolio_m_portfol_395bf0_idx"),
        ),
        migrations.AddIndex(
            model_name="licensetrueupforecast",
            index=models.Index(fields=["forecast_generated_at"], name="portfolio_m_forecas_dd4d3e_idx"),
        ),
        migrations.AddIndex(
            model_name="applicationownership",
            index=models.Index(fields=["owner", "is_active"], name="portfolio_m_owner_i_837810_idx"),
        ),
        migrations.AddIndex(
            model_name="applicationownership",
            index=models.Index(fields=["portfolio", "is_active"], name="portfolio_m_portfol_84c4d0_idx"),
        ),
        migrations.AddIndex(
            model_name="applicationownership",
            index=models.Index(fields=["application", "ownership_type"], name="portfolio_m_applica_3cbc98_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="applicationownership",
            unique_together={("application", "owner", "ownership_type")},
        ),
        migrations.AddIndex(
            model_name="applicationmanagerperformance",
            index=models.Index(fields=["manager", "recorded_at"], name="portfolio_m_manager_602300_idx"),
        ),
        migrations.AddIndex(
            model_name="applicationmanagerperformance",
            index=models.Index(fields=["portfolio", "recorded_at"], name="portfolio_m_portfol_5f8abc_idx"),
        ),
        migrations.AddIndex(
            model_name="applicationmanagerperformance",
            index=models.Index(fields=["composite_score"], name="portfolio_m_composi_92ff53_idx"),
        ),
        migrations.AddIndex(
            model_name="applicationmanagerperformance",
            index=models.Index(fields=["period_start", "period_end"], name="portfolio_m_period__8ab98d_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="applicationmanagerperformance",
            unique_together={("manager", "portfolio", "period_start", "period_end")},
        ),
    ]
