# Generated by Django 5.1.15 on 2026-01-31 11:48

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KPIDefinition",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("formula", models.TextField(help_text="Formula or calculation method")),
                ("data_sources", models.JSONField(default=list, help_text="List of data sources")),
                ("unit", models.CharField(max_length=50)),
                (
                    "direction",
                    models.CharField(
                        choices=[("higher_better", "Higher is Better"), ("lower_better", "Lower is Better")],
                        default="higher_better",
                        max_length=20,
                    ),
                ),
                ("thresholds", models.JSONField(default=dict, help_text="Warning and critical thresholds")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "verbose_name": "KPI Definition",
                "verbose_name_plural": "KPI Definitions",
                "ordering": ["name"],
                "indexes": [models.Index(fields=["is_active"], name="sla_governa_is_acti_3e7c8d_idx")],
            },
        ),
        migrations.CreateModel(
            name="ServiceCatalogItem",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("category", models.CharField(db_index=True, max_length=100)),
                ("owner", models.CharField(max_length=255)),
                ("status", models.CharField(db_index=True, default="active", max_length=20)),
                ("servicenow_sys_id", models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                "verbose_name": "Service Catalog Item",
                "verbose_name_plural": "Service Catalog Items",
                "ordering": ["name"],
                "indexes": [models.Index(fields=["category", "status"], name="sla_governa_categor_fbfabd_idx")],
            },
        ),
        migrations.CreateModel(
            name="SLADefinition",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique correlation ID for audit trail and tracing",
                        unique=True,
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("version", models.CharField(max_length=50)),
                ("effective_from", models.DateField()),
                ("effective_until", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_approval", "Pending Approval"),
                            ("active", "Active"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("original_request", models.TextField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_slas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_slas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slas",
                        to="sla_governance.servicecatalogitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "SLA Definition",
                "verbose_name_plural": "SLA Definitions",
                "ordering": ["-effective_from", "name"],
            },
        ),
        migrations.CreateModel(
            name="SLACompliance",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique correlation ID for audit trail and tracing",
                        unique=True,
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("period_start", models.DateField(db_index=True)),
                ("period_end", models.DateField(db_index=True)),
                ("overall_compliance", models.FloatField(help_text="Overall compliance percentage")),
                ("target_compliances", models.JSONField(default=dict, help_text="Per-target compliance percentages")),
                ("breach_count", models.IntegerField(default=0)),
                ("near_miss_count", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[("compliant", "Compliant"), ("at_risk", "At Risk"), ("breached", "Breached")],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "sla",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compliance_records",
                        to="sla_governance.sladefinition",
                    ),
                ),
            ],
            options={
                "verbose_name": "SLA Compliance",
                "verbose_name_plural": "SLA Compliance Records",
                "ordering": ["-period_end", "-period_start"],
            },
        ),
        migrations.CreateModel(
            name="SLATarget",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("availability", "Availability"),
                            ("response_time", "Response Time"),
                            ("resolution_time", "Resolution Time"),
                            ("quality", "Quality"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("target_value", models.FloatField()),
                ("target_unit", models.CharField(max_length=20)),
                ("measurement_period", models.CharField(default="monthly", max_length=20)),
                (
                    "applies_to",
                    models.JSONField(blank=True, help_text="Time windows, customer segments, etc.", null=True),
                ),
                (
                    "sla",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="targets",
                        to="sla_governance.sladefinition",
                    ),
                ),
            ],
            options={
                "verbose_name": "SLA Target",
                "verbose_name_plural": "SLA Targets",
                "ordering": ["sla", "metric_type"],
            },
        ),
        migrations.CreateModel(
            name="SLAKPILink",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("weight", models.FloatField(default=1.0, help_text="Weight for composite calculations")),
                (
                    "kpi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sla_links",
                        to="sla_governance.kpidefinition",
                    ),
                ),
                (
                    "sla_target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kpi_links",
                        to="sla_governance.slatarget",
                    ),
                ),
            ],
            options={
                "verbose_name": "SLA-KPI Link",
                "verbose_name_plural": "SLA-KPI Links",
            },
        ),
        migrations.CreateModel(
            name="SLABreach",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique correlation ID for audit trail and tracing",
                        unique=True,
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("breach_time", models.DateTimeField(db_index=True)),
                (
                    "severity",
                    models.CharField(
                        choices=[("critical", "Critical"), ("high", "High"), ("medium", "Medium"), ("low", "Low")],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("target_value", models.FloatField()),
                ("actual_value", models.FloatField()),
                ("root_cause", models.TextField(blank=True, null=True)),
                ("remediation", models.TextField(blank=True, null=True)),
                ("servicenow_incident", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "sla",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="breaches",
                        to="sla_governance.sladefinition",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="breaches",
                        to="sla_governance.slatarget",
                    ),
                ),
            ],
            options={
                "verbose_name": "SLA Breach",
                "verbose_name_plural": "SLA Breaches",
                "ordering": ["-breach_time"],
            },
        ),
        migrations.CreateModel(
            name="SLATemplate",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("category", models.CharField(db_index=True, max_length=100)),
                ("default_targets", models.JSONField(default=list, help_text="Default SLA targets")),
                ("variables", models.JSONField(default=dict, help_text="Placeholders to fill")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "verbose_name": "SLA Template",
                "verbose_name_plural": "SLA Templates",
                "ordering": ["category", "name"],
                "indexes": [models.Index(fields=["category", "is_active"], name="sla_governa_categor_88a61b_idx")],
            },
        ),
        migrations.CreateModel(
            name="KPIMeasurement",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("measurement_time", models.DateTimeField(db_index=True)),
                ("value", models.FloatField()),
                (
                    "status",
                    models.CharField(
                        choices=[("green", "Green"), ("yellow", "Yellow"), ("red", "Red")], db_index=True, max_length=20
                    ),
                ),
                (
                    "data_points",
                    models.JSONField(blank=True, help_text="Raw data points used in calculation", null=True),
                ),
                (
                    "kpi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="measurements",
                        to="sla_governance.kpidefinition",
                    ),
                ),
            ],
            options={
                "verbose_name": "KPI Measurement",
                "verbose_name_plural": "KPI Measurements",
                "ordering": ["-measurement_time"],
                "indexes": [
                    models.Index(fields=["kpi", "measurement_time"], name="sla_governa_kpi_id_cecf03_idx"),
                    models.Index(fields=["status", "measurement_time"], name="sla_governa_status_09d922_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="sladefinition",
            index=models.Index(fields=["service", "status"], name="sla_governa_service_a91448_idx"),
        ),
        migrations.AddIndex(
            model_name="sladefinition",
            index=models.Index(fields=["status", "effective_from"], name="sla_governa_status_736ad2_idx"),
        ),
        migrations.AddIndex(
            model_name="slacompliance",
            index=models.Index(fields=["sla", "period_start", "period_end"], name="sla_governa_sla_id_929f4d_idx"),
        ),
        migrations.AddIndex(
            model_name="slacompliance",
            index=models.Index(fields=["status", "period_end"], name="sla_governa_status_6c7448_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="slakpilink",
            unique_together={("sla_target", "kpi")},
        ),
        migrations.AddIndex(
            model_name="slabreach",
            index=models.Index(fields=["sla", "breach_time"], name="sla_governa_sla_id_2250a5_idx"),
        ),
        migrations.AddIndex(
            model_name="slabreach",
            index=models.Index(fields=["severity", "breach_time"], name="sla_governa_severit_8c6eaf_idx"),
        ),
    ]
