# Generated by Django 5.0.14 on 2026-01-30 06:21

import uuid
from decimal import Decimal

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("license_management", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assignment",
            options={"ordering": ["-assigned_at"]},
        ),
        migrations.AlterModelOptions(
            name="consumptionsignal",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.AlterModelOptions(
            name="consumptionsnapshot",
            options={"ordering": ["-reconciled_at"]},
        ),
        migrations.AlterModelOptions(
            name="consumptionunit",
            options={"ordering": ["-effective_from"]},
        ),
        migrations.AlterModelOptions(
            name="entitlement",
            options={"ordering": ["-start_date", "sku__name"]},
        ),
        migrations.AlterModelOptions(
            name="importjob",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="licensealert",
            options={"ordering": ["-detected_at"]},
        ),
        migrations.AlterModelOptions(
            name="licensepool",
            options={"ordering": ["sku__name", "name"]},
        ),
        migrations.AlterModelOptions(
            name="licensesku",
            options={"ordering": ["vendor__name", "name"]},
        ),
        migrations.AlterModelOptions(
            name="reconciliationrun",
            options={"ordering": ["-started_at"]},
        ),
        migrations.AlterModelOptions(
            name="vendor",
            options={"ordering": ["name"]},
        ),
        migrations.RemoveConstraint(
            model_name="consumptionsignal",
            name="unique_source_raw_id",
        ),
        migrations.RemoveConstraint(
            model_name="consumptionunit",
            name="unique_sku_principal",
        ),
        migrations.RemoveConstraint(
            model_name="licensesku",
            name="unique_vendor_sku_code",
        ),
        migrations.RemoveIndex(
            model_name="assignment",
            name="lm_assignment_pool_principal_idx",
        ),
        migrations.RemoveIndex(
            model_name="licensealert",
            name="lm_alert_ack_severity_idx",
        ),
        migrations.RemoveIndex(
            model_name="licensepool",
            name="lm_pool_sku_scope_idx",
        ),
        migrations.RenameIndex(
            model_name="consumptionsnapshot",
            new_name="license_con_sku_id_a6010b_idx",
            old_name="lm_snapshot_sku_reconciled_idx",
        ),
        migrations.RenameIndex(
            model_name="entitlement",
            new_name="license_ent_sku_id_04d179_idx",
            old_name="lm_entitlement_sku_status_idx",
        ),
        migrations.RemoveField(
            model_name="assignment",
            name="correlation_id",
        ),
        migrations.RemoveField(
            model_name="consumptionsnapshot",
            name="allocated_quantity",
        ),
        migrations.RemoveField(
            model_name="consumptionsnapshot",
            name="available_quantity",
        ),
        migrations.RemoveField(
            model_name="consumptionsnapshot",
            name="consumed_quantity",
        ),
        migrations.RemoveField(
            model_name="consumptionsnapshot",
            name="entitled_quantity",
        ),
        migrations.RemoveField(
            model_name="consumptionsnapshot",
            name="snapshot_data",
        ),
        migrations.RemoveField(
            model_name="consumptionunit",
            name="assignment",
        ),
        migrations.RemoveField(
            model_name="consumptionunit",
            name="first_seen_at",
        ),
        migrations.RemoveField(
            model_name="consumptionunit",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="consumptionunit",
            name="last_seen_at",
        ),
        migrations.RemoveField(
            model_name="consumptionunit",
            name="signal_count",
        ),
        migrations.RemoveField(
            model_name="entitlement",
            name="contract_ref",
        ),
        migrations.RemoveField(
            model_name="entitlement",
            name="cost_center",
        ),
        migrations.RemoveField(
            model_name="entitlement",
            name="effective_date",
        ),
        migrations.RemoveField(
            model_name="entitlement",
            name="expiry_date",
        ),
        migrations.RemoveField(
            model_name="entitlement",
            name="purchase_order",
        ),
        migrations.RemoveField(
            model_name="entitlement",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="importjob",
            name="error_details",
        ),
        migrations.RemoveField(
            model_name="importjob",
            name="filename",
        ),
        migrations.RemoveField(
            model_name="importjob",
            name="records_failed",
        ),
        migrations.RemoveField(
            model_name="importjob",
            name="records_processed",
        ),
        migrations.RemoveField(
            model_name="importjob",
            name="records_succeeded",
        ),
        migrations.RemoveField(
            model_name="importjob",
            name="source_type",
        ),
        migrations.RemoveField(
            model_name="licensealert",
            name="correlation_id",
        ),
        migrations.RemoveField(
            model_name="licensealert",
            name="metadata",
        ),
        migrations.RemoveField(
            model_name="licensealert",
            name="title",
        ),
        migrations.AlterUniqueTogether(
            name="licensesku",
            unique_together={("vendor", "sku_code")},
        ),
        migrations.RemoveField(
            model_name="reconciliationrun",
            name="alerts_generated",
        ),
        migrations.RemoveField(
            model_name="reconciliationrun",
            name="error_message",
        ),
        migrations.RemoveField(
            model_name="vendor",
            name="contact_email",
        ),
        migrations.RemoveField(
            model_name="vendor",
            name="correlation_id",
        ),
        migrations.RemoveField(
            model_name="vendor",
            name="vendor_code",
        ),
        migrations.RemoveField(
            model_name="vendor",
            name="website_url",
        ),
        migrations.AddField(
            model_name="assignment",
            name="expires_at",
            field=models.DateTimeField(blank=True, help_text="When assignment expires", null=True),
        ),
        migrations.AddField(
            model_name="consumptionsignal",
            name="raw_payload_hash",
            field=models.CharField(default="", help_text="SHA-256 of raw signal payload", max_length=64),
        ),
        migrations.AddField(
            model_name="consumptionsnapshot",
            name="consumed",
            field=models.IntegerField(default=0, help_text="Total consumed quantity"),
        ),
        migrations.AddField(
            model_name="consumptionsnapshot",
            name="entitled",
            field=models.IntegerField(default=0, help_text="Total entitled quantity"),
        ),
        migrations.AddField(
            model_name="consumptionsnapshot",
            name="remaining",
            field=models.IntegerField(default=0, help_text="Remaining available (entitled - consumed - reserved)"),
        ),
        migrations.AddField(
            model_name="consumptionsnapshot",
            name="reserved",
            field=models.IntegerField(default=0, help_text="Reserved quantity"),
        ),
        migrations.AddField(
            model_name="consumptionsnapshot",
            name="ruleset_version",
            field=models.CharField(default="v1.0", help_text="Version of reconciliation rules used", max_length=50),
        ),
        migrations.AddField(
            model_name="consumptionunit",
            name="effective_from",
            field=models.DateTimeField(
                default=django.utils.timezone.now, help_text="When consumption became effective"
            ),
        ),
        migrations.AddField(
            model_name="consumptionunit",
            name="effective_to",
            field=models.DateTimeField(blank=True, help_text="When consumption ended", null=True),
        ),
        migrations.AddField(
            model_name="consumptionunit",
            name="pool",
            field=models.ForeignKey(
                blank=True,
                help_text="Allocated pool (if applicable)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="consumption_units",
                to="license_management.licensepool",
            ),
        ),
        migrations.AddField(
            model_name="consumptionunit",
            name="signals",
            field=models.ManyToManyField(
                help_text="Source signals", related_name="consumption_units", to="license_management.consumptionsignal"
            ),
        ),
        migrations.AddField(
            model_name="consumptionunit",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("revoked", "Revoked"), ("expired", "Expired"), ("pending", "Pending")],
                db_index=True,
                default="active",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="consumptionunit",
            name="unit_count",
            field=models.IntegerField(default=1, help_text="Number of license units consumed"),
        ),
        migrations.AddField(
            model_name="entitlement",
            name="contract_id",
            field=models.CharField(db_index=True, default="", help_text="Contract or PO reference", max_length=100),
        ),
        migrations.AddField(
            model_name="entitlement",
            name="document_refs",
            field=models.JSONField(
                blank=True, default=list, help_text="References to contract documents (MinIO paths)"
            ),
        ),
        migrations.AddField(
            model_name="entitlement",
            name="end_date",
            field=models.DateField(blank=True, help_text="Entitlement end date (null = perpetual)", null=True),
        ),
        migrations.AddField(
            model_name="entitlement",
            name="entitled_quantity",
            field=models.IntegerField(default=0, help_text="Number of licenses entitled"),
        ),
        migrations.AddField(
            model_name="entitlement",
            name="renewal_date",
            field=models.DateField(blank=True, help_text="Next renewal date", null=True),
        ),
        migrations.AddField(
            model_name="entitlement",
            name="start_date",
            field=models.DateField(default=django.utils.timezone.now, help_text="Entitlement start date"),
        ),
        migrations.AddField(
            model_name="entitlement",
            name="terms",
            field=models.JSONField(blank=True, default=dict, help_text="License terms and conditions"),
        ),
        migrations.AddField(
            model_name="importjob",
            name="correlation_id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                help_text="Unique correlation ID for audit trail and tracing",
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="importjob",
            name="error_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="importjob",
            name="file_name",
            field=models.CharField(default="", help_text="Original file name", max_length=255),
        ),
        migrations.AddField(
            model_name="importjob",
            name="file_ref",
            field=models.CharField(default="", help_text="MinIO path to uploaded file", max_length=500),
        ),
        migrations.AddField(
            model_name="importjob",
            name="import_errors",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="importjob",
            name="import_type",
            field=models.CharField(
                choices=[
                    ("entitlements", "Entitlements"),
                    ("vendors", "Vendors"),
                    ("skus", "SKUs"),
                    ("assignments", "Assignments"),
                ],
                db_index=True,
                default="entitlements",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="importjob",
            name="processed_rows",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="importjob",
            name="success_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="importjob",
            name="total_rows",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="importjob",
            name="validation_errors",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="licensealert",
            name="auto_resolved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="licensealert",
            name="details",
            field=models.JSONField(blank=True, default=dict, help_text="Additional alert details"),
        ),
        migrations.AddField(
            model_name="licensealert",
            name="detected_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="licensealert",
            name="resolved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="licensepool",
            name="description",
            field=models.TextField(blank=True, help_text="Pool description"),
        ),
        migrations.AddField(
            model_name="licensepool",
            name="entitled_quantity_override",
            field=models.IntegerField(
                blank=True, help_text="Override total entitled quantity for this pool", null=True
            ),
        ),
        migrations.AddField(
            model_name="licensepool",
            name="scope_value",
            field=models.CharField(blank=True, help_text="Scope value (e.g., region code, BU name)", max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name="licensepool",
            unique_together={("sku", "scope_type", "scope_value")},
        ),
        migrations.AddField(
            model_name="licensesku",
            name="cost_per_unit",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Cost per license unit (for reporting)",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="licensesku",
            name="currency",
            field=models.CharField(default="USD", help_text="Currency code for cost", max_length=3),
        ),
        migrations.AddField(
            model_name="licensesku",
            name="normalization_rules",
            field=models.JSONField(
                blank=True, default=dict, help_text="Rules for normalizing consumption signals from different sources"
            ),
        ),
        migrations.AddField(
            model_name="licensesku",
            name="requires_approval",
            field=models.BooleanField(default=False, help_text="Whether entitlement changes require CAB approval"),
        ),
        migrations.AddField(
            model_name="licensesku",
            name="unit_rules",
            field=models.JSONField(
                blank=True, default=dict, help_text="Rules for computing license units (e.g., core multipliers)"
            ),
        ),
        migrations.AddField(
            model_name="reconciliationrun",
            name="diff_summary",
            field=models.JSONField(
                blank=True, default=dict, help_text="Summary of changes from previous reconciliation"
            ),
        ),
        migrations.AddField(
            model_name="reconciliationrun",
            name="errors",
            field=models.JSONField(blank=True, default=list, help_text="List of errors encountered"),
        ),
        migrations.AddField(
            model_name="reconciliationrun",
            name="ruleset_version",
            field=models.CharField(default="v1.0", help_text="Version of reconciliation rules", max_length=50),
        ),
        migrations.AddField(
            model_name="reconciliationrun",
            name="signals_processed",
            field=models.IntegerField(default=0, help_text="Signals processed"),
        ),
        migrations.AddField(
            model_name="reconciliationrun",
            name="skus_total",
            field=models.IntegerField(default=0, help_text="Total SKUs to process"),
        ),
        migrations.AddField(
            model_name="reconciliationrun",
            name="trigger_type",
            field=models.CharField(
                default="manual", help_text="How run was triggered (manual, scheduled, signal)", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="identifier",
            field=models.CharField(
                db_index=True, default="", help_text="Unique vendor identifier (slug)", max_length=100, unique=True
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="support_contact",
            field=models.EmailField(blank=True, help_text="Support contact email", max_length=254),
        ),
        migrations.AddField(
            model_name="vendor",
            name="website",
            field=models.URLField(blank=True, help_text="Vendor website URL"),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="assigned_at",
            field=models.DateTimeField(auto_now_add=True, help_text="When assignment was made"),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="assigned_by",
            field=models.ForeignKey(
                help_text="User who made the assignment",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="license_assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="pool",
            field=models.ForeignKey(
                help_text="License pool",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assignments",
                to="license_management.licensepool",
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="principal_id",
            field=models.CharField(db_index=True, help_text="Assignee identifier", max_length=255),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="principal_name",
            field=models.CharField(blank=True, help_text="Assignee display name", max_length=255),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="principal_type",
            field=models.CharField(
                choices=[("user", "User"), ("device", "Device"), ("service", "Service Account")],
                help_text="Type of assignee",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("revoked", "Revoked"), ("expired", "Expired"), ("pending", "Pending")],
                db_index=True,
                default="active",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="consumptionsignal",
            name="confidence",
            field=models.FloatField(default=1.0, help_text="Match confidence (0.0-1.0)"),
        ),
        migrations.AlterField(
            model_name="consumptionsignal",
            name="is_processed",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="consumptionsignal",
            name="principal_type",
            field=models.CharField(
                choices=[("user", "User"), ("device", "Device"), ("service", "Service Account")], max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="consumptionsignal",
            name="raw_id",
            field=models.CharField(db_index=True, help_text="ID from source system", max_length=255),
        ),
        migrations.AlterField(
            model_name="consumptionsignal",
            name="raw_payload",
            field=models.JSONField(blank=True, default=dict, help_text="Original signal payload"),
        ),
        migrations.AlterField(
            model_name="consumptionsignal",
            name="sku",
            field=models.ForeignKey(
                help_text="Matched license SKU",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="consumption_signals",
                to="license_management.licensesku",
            ),
        ),
        migrations.AlterField(
            model_name="consumptionsignal",
            name="source_system",
            field=models.CharField(
                db_index=True, help_text="Source system identifier (intune, jamf, etc.)", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="consumptionsignal",
            name="timestamp",
            field=models.DateTimeField(db_index=True, help_text="When consumption was detected"),
        ),
        migrations.AlterField(
            model_name="consumptionsnapshot",
            name="evidence_pack_hash",
            field=models.CharField(default="", help_text="SHA-256 of evidence pack", max_length=64),
        ),
        migrations.AlterField(
            model_name="consumptionsnapshot",
            name="evidence_pack_ref",
            field=models.CharField(default="", help_text="MinIO path to evidence pack", max_length=500),
        ),
        migrations.AlterField(
            model_name="consumptionsnapshot",
            name="pool",
            field=models.ForeignKey(
                blank=True,
                help_text="License pool (null for SKU-level snapshot)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="consumption_snapshots",
                to="license_management.licensepool",
            ),
        ),
        migrations.AlterField(
            model_name="consumptionsnapshot",
            name="reconciled_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now, help_text="When snapshot was created"
            ),
        ),
        migrations.AlterField(
            model_name="consumptionsnapshot",
            name="reconciliation_run",
            field=models.ForeignKey(
                help_text="Source reconciliation run",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="snapshots",
                to="license_management.reconciliationrun",
            ),
        ),
        migrations.AlterField(
            model_name="consumptionsnapshot",
            name="sku",
            field=models.ForeignKey(
                help_text="License SKU",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="consumption_snapshots",
                to="license_management.licensesku",
            ),
        ),
        migrations.AlterField(
            model_name="consumptionsnapshot",
            name="utilization_percent",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), help_text="Utilization percentage", max_digits=5
            ),
        ),
        migrations.AlterField(
            model_name="consumptionunit",
            name="principal_type",
            field=models.CharField(
                choices=[("user", "User"), ("device", "Device"), ("service", "Service Account")], max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="consumptionunit",
            name="sku",
            field=models.ForeignKey(
                help_text="License SKU",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="consumption_units",
                to="license_management.licensesku",
            ),
        ),
        migrations.AlterField(
            model_name="entitlement",
            name="approved_at",
            field=models.DateTimeField(blank=True, help_text="When entitlement was approved", null=True),
        ),
        migrations.AlterField(
            model_name="entitlement",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who approved this entitlement",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_entitlements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="entitlement",
            name="correlation_id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                help_text="Unique correlation ID for audit trail and tracing",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="entitlement",
            name="created_by",
            field=models.ForeignKey(
                help_text="User who created this entitlement",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_entitlements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="entitlement",
            name="notes",
            field=models.TextField(blank=True, help_text="Internal notes"),
        ),
        migrations.AlterField(
            model_name="entitlement",
            name="sku",
            field=models.ForeignKey(
                help_text="License SKU",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="entitlements",
                to="license_management.licensesku",
            ),
        ),
        migrations.AlterField(
            model_name="entitlement",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("expired", "Expired"),
                    ("pending", "Pending Approval"),
                    ("suspended", "Suspended"),
                    ("terminated", "Terminated"),
                ],
                db_index=True,
                default="pending",
                help_text="Entitlement status",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="importjob",
            name="file_hash",
            field=models.CharField(default="", help_text="SHA-256 of uploaded file", max_length=64),
        ),
        migrations.AlterField(
            model_name="importjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("validating", "Validating"),
                    ("importing", "Importing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="importjob",
            name="uploaded_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="license_imports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="licensealert",
            name="acknowledged",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="licensealert",
            name="alert_type",
            field=models.CharField(
                choices=[
                    ("overconsumption", "Over Consumption"),
                    ("expiring", "Expiring Soon"),
                    ("spike", "Usage Spike"),
                    ("underutilized", "Underutilized"),
                    ("reconciliation_failed", "Reconciliation Failed"),
                    ("stale_data", "Stale Data"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="licensealert",
            name="message",
            field=models.TextField(help_text="Alert message"),
        ),
        migrations.AlterField(
            model_name="licensealert",
            name="pool",
            field=models.ForeignKey(
                blank=True,
                help_text="Related pool (if applicable)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="alerts",
                to="license_management.licensepool",
            ),
        ),
        migrations.AlterField(
            model_name="licensealert",
            name="severity",
            field=models.CharField(
                choices=[("info", "Info"), ("warning", "Warning"), ("critical", "Critical")],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="licensealert",
            name="sku",
            field=models.ForeignKey(
                help_text="Related SKU",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alerts",
                to="license_management.licensesku",
            ),
        ),
        migrations.AlterField(
            model_name="licensepool",
            name="is_active",
            field=models.BooleanField(default=True, help_text="Whether pool is active"),
        ),
        migrations.AlterField(
            model_name="licensepool",
            name="name",
            field=models.CharField(help_text="Pool display name", max_length=255),
        ),
        migrations.AlterField(
            model_name="licensepool",
            name="reserved_quantity",
            field=models.IntegerField(default=0, help_text="Quantity reserved for specific purposes"),
        ),
        migrations.AlterField(
            model_name="licensepool",
            name="scope_type",
            field=models.CharField(
                choices=[
                    ("global", "Global"),
                    ("region", "Region"),
                    ("bu", "Business Unit"),
                    ("department", "Department"),
                    ("site", "Site"),
                ],
                default="global",
                help_text="Type of scope restriction",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="licensepool",
            name="sku",
            field=models.ForeignKey(
                help_text="License SKU",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pools",
                to="license_management.licensesku",
            ),
        ),
        migrations.AlterField(
            model_name="licensesku",
            name="description",
            field=models.TextField(blank=True, help_text="SKU description"),
        ),
        migrations.AlterField(
            model_name="licensesku",
            name="is_active",
            field=models.BooleanField(default=True, help_text="Whether SKU is active for new entitlements"),
        ),
        migrations.AlterField(
            model_name="licensesku",
            name="license_model_type",
            field=models.CharField(
                choices=[
                    ("device", "Per Device"),
                    ("user", "Per User"),
                    ("concurrent", "Concurrent"),
                    ("subscription", "Subscription Seat"),
                    ("feature", "Feature Add-on"),
                    ("core", "Per Core/CPU"),
                    ("instance", "Per Instance"),
                ],
                default="user",
                help_text="How licenses are counted",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="licensesku",
            name="name",
            field=models.CharField(help_text="SKU display name", max_length=255),
        ),
        migrations.AlterField(
            model_name="licensesku",
            name="sku_code",
            field=models.CharField(db_index=True, help_text="Vendor's SKU code", max_length=100),
        ),
        migrations.AlterField(
            model_name="licensesku",
            name="vendor",
            field=models.ForeignKey(
                help_text="Software vendor",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="skus",
                to="license_management.vendor",
            ),
        ),
        migrations.AlterField(
            model_name="reconciliationrun",
            name="completed_at",
            field=models.DateTimeField(blank=True, help_text="When run completed", null=True),
        ),
        migrations.AlterField(
            model_name="reconciliationrun",
            name="correlation_id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                help_text="Unique correlation ID for audit trail and tracing",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="reconciliationrun",
            name="skus_processed",
            field=models.IntegerField(default=0, help_text="SKUs processed so far"),
        ),
        migrations.AlterField(
            model_name="reconciliationrun",
            name="snapshots_created",
            field=models.IntegerField(default=0, help_text="Snapshots created"),
        ),
        migrations.AlterField(
            model_name="reconciliationrun",
            name="started_at",
            field=models.DateTimeField(default=django.utils.timezone.now, help_text="When run started"),
        ),
        migrations.AlterField(
            model_name="reconciliationrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("running", "Running"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="running",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="reconciliationrun",
            name="triggered_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who triggered the run (null for scheduled)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reconciliation_runs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="is_active",
            field=models.BooleanField(default=True, help_text="Whether vendor is active for new entitlements"),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="name",
            field=models.CharField(db_index=True, help_text="Vendor display name", max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="notes",
            field=models.TextField(blank=True, help_text="Internal notes about the vendor"),
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(fields=["pool", "status"], name="license_ass_pool_id_db000f_idx"),
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(fields=["principal_type", "principal_id"], name="license_ass_princip_cc1bab_idx"),
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(fields=["status", "expires_at"], name="license_ass_status_63569c_idx"),
        ),
        migrations.AddIndex(
            model_name="consumptionsignal",
            index=models.Index(fields=["source_system", "raw_id"], name="license_con_source__d54206_idx"),
        ),
        migrations.AddIndex(
            model_name="consumptionsignal",
            index=models.Index(fields=["sku", "timestamp"], name="license_con_sku_id_f00b51_idx"),
        ),
        migrations.AddIndex(
            model_name="consumptionsignal",
            index=models.Index(fields=["is_processed", "timestamp"], name="license_con_is_proc_11b380_idx"),
        ),
        migrations.AddIndex(
            model_name="consumptionsignal",
            index=models.Index(fields=["principal_type", "principal_id"], name="license_con_princip_1e514c_idx"),
        ),
        migrations.AddIndex(
            model_name="consumptionsnapshot",
            index=models.Index(fields=["reconciled_at"], name="license_con_reconci_68abdd_idx"),
        ),
        migrations.AddIndex(
            model_name="consumptionsnapshot",
            index=models.Index(fields=["pool", "reconciled_at"], name="license_con_pool_id_54898e_idx"),
        ),
        migrations.AddIndex(
            model_name="consumptionunit",
            index=models.Index(fields=["sku", "status"], name="license_con_sku_id_0525cf_idx"),
        ),
        migrations.AddIndex(
            model_name="consumptionunit",
            index=models.Index(fields=["principal_type", "principal_id"], name="license_con_princip_18301d_idx"),
        ),
        migrations.AddIndex(
            model_name="consumptionunit",
            index=models.Index(fields=["effective_from", "effective_to"], name="license_con_effecti_fa684e_idx"),
        ),
        migrations.AddIndex(
            model_name="entitlement",
            index=models.Index(fields=["contract_id"], name="license_ent_contrac_679e4a_idx"),
        ),
        migrations.AddIndex(
            model_name="entitlement",
            index=models.Index(fields=["start_date", "end_date"], name="license_ent_start_d_d068c2_idx"),
        ),
        migrations.AddIndex(
            model_name="entitlement",
            index=models.Index(fields=["status", "end_date"], name="license_ent_status_459882_idx"),
        ),
        migrations.AddIndex(
            model_name="importjob",
            index=models.Index(fields=["import_type", "status"], name="license_imp_import__47de34_idx"),
        ),
        migrations.AddIndex(
            model_name="importjob",
            index=models.Index(fields=["status", "created_at"], name="license_imp_status_80a843_idx"),
        ),
        migrations.AddIndex(
            model_name="licensealert",
            index=models.Index(fields=["sku", "alert_type"], name="license_ale_sku_id_5b011d_idx"),
        ),
        migrations.AddIndex(
            model_name="licensealert",
            index=models.Index(fields=["severity", "acknowledged"], name="license_ale_severit_6dff9e_idx"),
        ),
        migrations.AddIndex(
            model_name="licensealert",
            index=models.Index(fields=["detected_at"], name="license_ale_detecte_7b66bd_idx"),
        ),
        migrations.AddIndex(
            model_name="licensepool",
            index=models.Index(fields=["sku", "scope_type"], name="license_poo_sku_id_d04ebf_idx"),
        ),
        migrations.AddIndex(
            model_name="licensepool",
            index=models.Index(fields=["is_active"], name="license_poo_is_acti_ee9163_idx"),
        ),
        migrations.AddIndex(
            model_name="licensesku",
            index=models.Index(fields=["vendor", "sku_code"], name="license_sku_vendor__7ac13d_idx"),
        ),
        migrations.AddIndex(
            model_name="licensesku",
            index=models.Index(fields=["license_model_type"], name="license_sku_license_378e60_idx"),
        ),
        migrations.AddIndex(
            model_name="licensesku",
            index=models.Index(fields=["is_active"], name="license_sku_is_acti_21e17b_idx"),
        ),
        migrations.AddIndex(
            model_name="reconciliationrun",
            index=models.Index(fields=["status", "started_at"], name="license_rec_status_851b1e_idx"),
        ),
        migrations.AddIndex(
            model_name="reconciliationrun",
            index=models.Index(fields=["started_at"], name="license_rec_started_2a8907_idx"),
        ),
        migrations.AddIndex(
            model_name="vendor",
            index=models.Index(fields=["is_active", "name"], name="license_ven_is_acti_186598_idx"),
        ),
        migrations.AlterModelTable(
            name="assignment",
            table="license_assignment",
        ),
        migrations.AlterModelTable(
            name="consumptionsignal",
            table="license_consumption_signal",
        ),
        migrations.AlterModelTable(
            name="consumptionsnapshot",
            table="license_consumption_snapshot",
        ),
        migrations.AlterModelTable(
            name="consumptionunit",
            table="license_consumption_unit",
        ),
        migrations.AlterModelTable(
            name="entitlement",
            table="license_entitlement",
        ),
        migrations.AlterModelTable(
            name="importjob",
            table="license_import_job",
        ),
        migrations.AlterModelTable(
            name="licensealert",
            table="license_alert",
        ),
        migrations.AlterModelTable(
            name="licensepool",
            table="license_pool",
        ),
        migrations.AlterModelTable(
            name="licensesku",
            table="license_sku",
        ),
        migrations.AlterModelTable(
            name="reconciliationrun",
            table="license_reconciliation_run",
        ),
        migrations.AlterModelTable(
            name="vendor",
            table="license_vendor",
        ),
        migrations.RemoveField(
            model_name="licensepool",
            name="allocated_quantity",
        ),
        migrations.RemoveField(
            model_name="licensepool",
            name="consumed_quantity",
        ),
        migrations.RemoveField(
            model_name="licensepool",
            name="correlation_id",
        ),
        migrations.RemoveField(
            model_name="licensepool",
            name="scope_id",
        ),
        migrations.RemoveField(
            model_name="licensesku",
            name="computation_rule",
        ),
        migrations.RemoveField(
            model_name="licensesku",
            name="correlation_id",
        ),
    ]
