# Generated by Django 5.1.15 on 2026-01-30 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("license_management", "0002_alter_assignment_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="licensealert",
            name="detected_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
