# Generated by Django 5.1.15 on 2026-01-31 06:44

from django.db import migrations, models

import apps.license_management.models


class Migration(migrations.Migration):

    dependencies = [
        ("license_management", "0004_fix_vendor_identifier_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendor",
            name="identifier",
            field=models.CharField(
                db_index=True,
                default=apps.license_management.models.generate_vendor_identifier,
                help_text="Unique vendor identifier (slug)",
                max_length=100,
                unique=True,
            ),
        ),
    ]
