# Generated by Django 5.1.15 on 2026-01-31 11:48

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("application_portfolio", "0002_alter_application_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChangeFreezePeriod",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("reason", models.TextField()),
                ("start_date", models.DateField(db_index=True)),
                ("end_date", models.DateField(db_index=True)),
                ("scope", models.JSONField(default=dict, help_text="Affected departments, regions")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "verbose_name": "Change Freeze Period",
                "verbose_name_plural": "Change Freeze Periods",
                "ordering": ["-start_date"],
                "indexes": [
                    models.Index(fields=["start_date", "end_date"], name="planning_ag_start_d_f5d334_idx"),
                    models.Index(fields=["is_active"], name="planning_ag_is_acti_71f437_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="DeploymentPlan",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique correlation ID for audit trail and tracing",
                        unique=True,
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("version", models.CharField(max_length=100)),
                ("target_scope", models.JSONField(default=dict, help_text="Departments, regions, groups")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_approval", "Pending Approval"),
                            ("approved", "Approved"),
                            ("executing", "Executing"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("input_request", models.TextField(help_text="Original natural language request")),
                ("reasoning", models.TextField(help_text="AI reasoning for plan decisions")),
                ("overall_risk_score", models.FloatField(help_text="Overall risk score (0-100)")),
                ("risk_factors", models.JSONField(default=dict, help_text="Risk factor breakdown")),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deployment_plans",
                        to="application_portfolio.application",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Deployment Plan",
                "verbose_name_plural": "Deployment Plans",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BlastRadiusAnalysis",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique correlation ID for audit trail and tracing",
                        unique=True,
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("total_users_affected", models.IntegerField(default=0)),
                ("vip_users_affected", models.IntegerField(default=0)),
                ("departments_affected", models.JSONField(default=list)),
                ("regions_affected", models.JSONField(default=list)),
                ("critical_systems_affected", models.JSONField(default=list)),
                ("productivity_impact_score", models.FloatField(help_text="Impact score (0-100)")),
                ("recommendations", models.JSONField(default=list)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blast_radius_analyses",
                        to="planning_agent.deploymentplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blast Radius Analysis",
                "verbose_name_plural": "Blast Radius Analyses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DeploymentWindow",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("day_of_week", models.JSONField(default=list, help_text="[0,1,2,3,4] for Mon-Fri")),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("timezone", models.CharField(default="UTC", max_length=50)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "verbose_name": "Deployment Window",
                "verbose_name_plural": "Deployment Windows",
                "ordering": ["name"],
                "indexes": [models.Index(fields=["is_active"], name="planning_ag_is_acti_41ec21_idx")],
            },
        ),
        migrations.CreateModel(
            name="RingAssignment",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("ring_number", models.IntegerField(db_index=True, help_text="Ring number (0-4)")),
                ("ring_name", models.CharField(help_text="Ring name (e.g., 'Ring 1 - IT Canary')", max_length=50)),
                ("device_count", models.IntegerField(default=0)),
                ("device_criteria", models.JSONField(default=dict, help_text="How devices were selected")),
                ("scheduled_start", models.DateTimeField()),
                ("scheduled_end", models.DateTimeField()),
                ("success_threshold", models.FloatField(default=98.0, help_text="Required % for promotion")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("paused", "Paused"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rings",
                        to="planning_agent.deploymentplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ring Assignment",
                "verbose_name_plural": "Ring Assignments",
                "ordering": ["plan", "ring_number"],
            },
        ),
        migrations.CreateModel(
            name="RingDevice",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("device_id", models.CharField(db_index=True, max_length=255)),
                ("device_name", models.CharField(max_length=255)),
                ("user_principal", models.CharField(blank=True, max_length=255, null=True)),
                ("selection_reason", models.CharField(help_text="Why this device was selected", max_length=255)),
                ("health_score", models.FloatField(blank=True, help_text="Device health score (0-100)", null=True)),
                (
                    "criticality",
                    models.CharField(
                        choices=[("vip", "VIP"), ("standard", "Standard"), ("low", "Low")],
                        default="standard",
                        max_length=20,
                    ),
                ),
                (
                    "ring",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to="planning_agent.ringassignment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ring Device",
                "verbose_name_plural": "Ring Devices",
                "ordering": ["ring", "device_name"],
            },
        ),
        migrations.CreateModel(
            name="RollbackPlan",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("trigger_conditions", models.JSONField(default=list, help_text="Conditions that trigger rollback")),
                ("rollback_steps", models.JSONField(default=list, help_text="Steps to execute rollback")),
                ("estimated_duration_minutes", models.IntegerField(help_text="Estimated rollback duration")),
                ("requires_cab_approval", models.BooleanField(default=False)),
                ("tested", models.BooleanField(default=False)),
                ("tested_at", models.DateTimeField(blank=True, null=True)),
                (
                    "deployment_plan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rollback_plan",
                        to="planning_agent.deploymentplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rollback Plan",
                "verbose_name_plural": "Rollback Plans",
            },
        ),
        migrations.AddIndex(
            model_name="deploymentplan",
            index=models.Index(fields=["application", "status"], name="planning_ag_applica_7ff0e6_idx"),
        ),
        migrations.AddIndex(
            model_name="deploymentplan",
            index=models.Index(fields=["status", "created_at"], name="planning_ag_status_c84731_idx"),
        ),
        migrations.AddIndex(
            model_name="blastradiusanalysis",
            index=models.Index(fields=["plan"], name="planning_ag_plan_id_f7e077_idx"),
        ),
        migrations.AddIndex(
            model_name="ringassignment",
            index=models.Index(fields=["plan", "ring_number"], name="planning_ag_plan_id_b3fccd_idx"),
        ),
        migrations.AddIndex(
            model_name="ringassignment",
            index=models.Index(fields=["status", "scheduled_start"], name="planning_ag_status_ee2ce2_idx"),
        ),
        migrations.AddIndex(
            model_name="ringdevice",
            index=models.Index(fields=["ring", "device_id"], name="planning_ag_ring_id_350842_idx"),
        ),
        migrations.AddIndex(
            model_name="ringdevice",
            index=models.Index(fields=["criticality"], name="planning_ag_critica_5d4d5e_idx"),
        ),
    ]
