# Generated by Django 5.1.15 on 2026-01-30 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0002_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="knowledgevector",
            new_name="knowledge_k_source__700792_idx",
            old_name="knowledgevector_source_type_source_id_idx",
        ),
        migrations.RenameIndex(
            model_name="knowledgevector",
            new_name="knowledge_k_categor_1f7e70_idx",
            old_name="knowledgevector_category_idx",
        ),
        migrations.RenameIndex(
            model_name="knowledgevector",
            new_name="knowledge_k_applica_11b62f_idx",
            old_name="knowledgevector_application_id_idx",
        ),
    ]
