# Generated by Django 5.0.14 on 2026-01-05 12:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("vendor", models.CharField(blank=True, db_index=True, max_length=255)),
                ("version", models.CharField(db_index=True, max_length=50)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("Windows", "Windows"),
                            ("macOS", "macOS"),
                            ("Linux", "Linux"),
                            ("Mobile", "Mobile"),
                            ("Multi-Platform", "Multi-Platform"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Productivity", "Productivity"),
                            ("Security", "Security"),
                            ("Development", "Development"),
                            ("Media", "Media"),
                            ("Browser", "Browser"),
                            ("Communication", "Communication"),
                            ("Utility", "Utility"),
                            ("Enterprise", "Enterprise"),
                        ],
                        db_index=True,
                        default="Utility",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("homepage_url", models.URLField(blank=True)),
                ("license_type", models.CharField(blank=True, max_length=100)),
                (
                    "default_risk_score",
                    models.IntegerField(
                        default=30, help_text="Default risk score (0-100)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Application",
                "verbose_name_plural": "Applications",
                "ordering": ["name", "version"],
                "indexes": [
                    models.Index(
                        fields=["name", "version"], name="connectors__name_bd47ca_idx"
                    ),
                    models.Index(
                        fields=["platform", "category"],
                        name="connectors__platfor_88ffe6_idx",
                    ),
                    models.Index(
                        fields=["vendor"], name="connectors__vendor_1d1e6a_idx"
                    ),
                ],
                "unique_together": {("name", "version", "platform")},
            },
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        db_index=True, help_text="Device name/hostname", max_length=255
                    ),
                ),
                (
                    "asset_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique asset identifier",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Laptop", "Laptop"),
                            ("Desktop", "Desktop"),
                            ("Virtual Machine", "Virtual Machine"),
                            ("Mobile", "Mobile"),
                            ("Server", "Server"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "os",
                    models.CharField(
                        db_index=True,
                        help_text="Operating system version",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Inactive", "Inactive"),
                            ("Retired", "Retired"),
                            ("Maintenance", "Maintenance"),
                        ],
                        db_index=True,
                        default="Active",
                        max_length=20,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        db_index=True,
                        help_text="Physical or logical location",
                        max_length=255,
                    ),
                ),
                (
                    "owner",
                    models.CharField(
                        db_index=True,
                        help_text="Asset owner/assigned user",
                        max_length=255,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(blank=True, db_index=True, null=True),
                ),
                (
                    "disk_encryption",
                    models.BooleanField(
                        default=False, help_text="Disk encryption enabled"
                    ),
                ),
                (
                    "firewall_enabled",
                    models.BooleanField(default=True, help_text="Firewall enabled"),
                ),
                (
                    "compliance_score",
                    models.IntegerField(
                        default=0, help_text="Compliance score (0-100)"
                    ),
                ),
                (
                    "last_checkin",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Last check-in timestamp",
                        null=True,
                    ),
                ),
                (
                    "dex_score",
                    models.FloatField(
                        blank=True,
                        help_text="Digital Experience Score (0-10)",
                        null=True,
                    ),
                ),
                (
                    "boot_time",
                    models.IntegerField(
                        blank=True, help_text="Boot time in seconds", null=True
                    ),
                ),
                (
                    "carbon_footprint",
                    models.FloatField(
                        blank=True,
                        help_text="Carbon footprint (kg CO2e per year)",
                        null=True,
                    ),
                ),
                (
                    "user_sentiment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Positive", "Positive"),
                            ("Neutral", "Neutral"),
                            ("Negative", "Negative"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "connector_type",
                    models.CharField(
                        blank=True,
                        help_text="Source connector (intune, jamf, sccm, landscape)",
                        max_length=20,
                    ),
                ),
                (
                    "connector_object_id",
                    models.CharField(
                        blank=True,
                        help_text="Platform-specific object ID",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name": "Asset",
                "verbose_name_plural": "Assets",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["type", "status"], name="connectors__type_5fcb0d_idx"
                    ),
                    models.Index(
                        fields=["os", "status"], name="connectors__os_bb00c2_idx"
                    ),
                    models.Index(
                        fields=["location", "status"],
                        name="connectors__locatio_7763f0_idx",
                    ),
                    models.Index(
                        fields=["owner", "status"], name="connectors__owner_bee2c8_idx"
                    ),
                    models.Index(
                        fields=["compliance_score"],
                        name="connectors__complia_c34ebd_idx",
                    ),
                    models.Index(
                        fields=["last_checkin"], name="connectors__last_ch_69d77d_idx"
                    ),
                ],
            },
        ),
    ]
