# Generated by Django 5.0.14 on 2026-01-30 06:21

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connectors", "0003_connector_reconciliation"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="connectorinstance",
            new_name="connector_i_connect_379f48_idx",
            old_name="connector_i_connect_idx",
        ),
        migrations.RenameIndex(
            model_name="connectorinstance",
            new_name="connector_i_health__349d4e_idx",
            old_name="connector_i_health__idx",
        ),
        migrations.RenameIndex(
            model_name="connectorinstance",
            new_name="connector_i_next_sy_7d8a90_idx",
            old_name="connector_i_next_sy_idx",
        ),
        migrations.RenameIndex(
            model_name="driftevent",
            new_name="connector_d_connect_ea15e4_idx",
            old_name="connector_d_connect_idx",
        ),
        migrations.RenameIndex(
            model_name="driftevent",
            new_name="connector_d_entity__97f6ca_idx",
            old_name="connector_d_entity__idx",
        ),
        migrations.RenameIndex(
            model_name="driftevent",
            new_name="connector_d_remedia_0ea75b_idx",
            old_name="connector_d_remedia_idx",
        ),
        migrations.RenameIndex(
            model_name="driftevent",
            new_name="connector_d_detecte_806bf7_idx",
            old_name="connector_d_detecte_idx",
        ),
        migrations.RenameIndex(
            model_name="driftevent",
            new_name="connector_d_resolve_b31793_idx",
            old_name="connector_d_resolve_idx",
        ),
        migrations.RenameIndex(
            model_name="driftevent",
            new_name="connector_d_severit_d1d52f_idx",
            old_name="connector_d_severit_idx",
        ),
        migrations.RenameIndex(
            model_name="syncjob",
            new_name="connector_s_connect_c00b93_idx",
            old_name="connector_s_connect_idx",
        ),
        migrations.RenameIndex(
            model_name="syncjob",
            new_name="connector_s_job_typ_66522d_idx",
            old_name="connector_s_job_typ_idx",
        ),
        migrations.RenameIndex(
            model_name="syncjob",
            new_name="connector_s_started_da40ac_idx",
            old_name="connector_s_started_idx",
        ),
        migrations.RenameIndex(
            model_name="syncjob",
            new_name="connector_s_status_c668d2_idx",
            old_name="connector_s_status_idx",
        ),
        migrations.AlterField(
            model_name="syncjob",
            name="correlation_id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                help_text="Unique correlation ID for audit trail and tracing",
                unique=True,
            ),
        ),
    ]
