# Generated by Django 5.1.15 on 2026-01-30 18:09

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import apps.core.encryption


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StorageProvider",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=128)),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("minio", "MinIO (S3-Compatible)"),
                            ("aws_s3", "AWS S3"),
                            ("azure_blob", "Azure Blob Storage"),
                        ],
                        max_length=32,
                    ),
                ),
                ("priority", models.IntegerField(default=100, help_text="Lower = higher priority")),
                ("is_primary", models.BooleanField(default=False)),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("configured", "Configured"),
                            ("testing", "Testing Connection"),
                            ("healthy", "Healthy"),
                            ("degraded", "Degraded"),
                            ("failed", "Connection Failed"),
                            ("disabled", "Disabled"),
                        ],
                        default="configured",
                        max_length=32,
                    ),
                ),
                ("last_health_check", models.DateTimeField(blank=True, null=True)),
                ("health_check_error", models.TextField(blank=True)),
                (
                    "configured_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="storage_providers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Storage Provider",
                "verbose_name_plural": "Storage Providers",
                "ordering": ["priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="StorageMetrics",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("recorded_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("total_bytes", models.BigIntegerField(default=0)),
                ("used_bytes", models.BigIntegerField(default=0)),
                ("object_count", models.BigIntegerField(default=0)),
                ("uploads", models.IntegerField(default=0)),
                ("downloads", models.IntegerField(default=0)),
                ("deletes", models.IntegerField(default=0)),
                ("bytes_uploaded", models.BigIntegerField(default=0)),
                ("bytes_downloaded", models.BigIntegerField(default=0)),
                ("failed_operations", models.IntegerField(default=0)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="storage.storageprovider",
                    ),
                ),
            ],
            options={
                "verbose_name": "Storage Metric",
                "verbose_name_plural": "Storage Metrics",
                "ordering": ["-recorded_at"],
            },
        ),
        migrations.CreateModel(
            name="MinIOConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("endpoint_url", models.URLField(help_text="e.g., http://minio.local:9000")),
                ("bucket_name", models.CharField(max_length=63)),
                ("access_key_id", apps.core.encryption.EncryptedCharField(max_length=256)),
                ("secret_access_key", apps.core.encryption.EncryptedCharField(max_length=256)),
                ("use_ssl", models.BooleanField(default=True)),
                ("region", models.CharField(default="us-east-1", max_length=64)),
                ("path_style", models.BooleanField(default=True, help_text="MinIO uses path-style URLs")),
                (
                    "provider",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="minio_config",
                        to="storage.storageprovider",
                    ),
                ),
            ],
            options={
                "verbose_name": "MinIO Configuration",
                "verbose_name_plural": "MinIO Configurations",
            },
        ),
        migrations.CreateModel(
            name="AzureBlobConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("account_name", models.CharField(max_length=24)),
                ("container_name", models.CharField(max_length=63)),
                (
                    "auth_method",
                    models.CharField(
                        choices=[
                            ("connection_string", "Connection String"),
                            ("account_key", "Account Key"),
                            ("sas_token", "SAS Token"),
                            ("managed_identity", "Managed Identity"),
                            ("service_principal", "Service Principal"),
                        ],
                        default="connection_string",
                        max_length=32,
                    ),
                ),
                ("connection_string", apps.core.encryption.EncryptedTextField(blank=True)),
                ("account_key", apps.core.encryption.EncryptedCharField(blank=True, max_length=256)),
                ("sas_token", apps.core.encryption.EncryptedTextField(blank=True)),
                ("tenant_id", models.CharField(blank=True, max_length=36)),
                ("client_id", models.CharField(blank=True, max_length=36)),
                ("client_secret", apps.core.encryption.EncryptedCharField(blank=True, max_length=256)),
                (
                    "provider",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="azure_config",
                        to="storage.storageprovider",
                    ),
                ),
            ],
            options={
                "verbose_name": "Azure Blob Configuration",
                "verbose_name_plural": "Azure Blob Configurations",
            },
        ),
        migrations.CreateModel(
            name="AWSS3Config",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("bucket_name", models.CharField(max_length=63)),
                ("region", models.CharField(max_length=64)),
                (
                    "auth_method",
                    models.CharField(
                        choices=[
                            ("access_key", "Access Key + Secret"),
                            ("iam_role", "IAM Role (EC2/ECS/EKS)"),
                            ("assume_role", "Assume Role (Cross-Account)"),
                        ],
                        default="access_key",
                        max_length=32,
                    ),
                ),
                ("access_key_id", apps.core.encryption.EncryptedCharField(blank=True, max_length=256)),
                ("secret_access_key", apps.core.encryption.EncryptedCharField(blank=True, max_length=256)),
                ("role_arn", models.CharField(blank=True, help_text="For assume_role", max_length=256)),
                ("external_id", models.CharField(blank=True, help_text="For assume_role", max_length=256)),
                ("endpoint_url", models.URLField(blank=True, help_text="For S3-compatible services", null=True)),
                (
                    "kms_key_id",
                    models.CharField(blank=True, help_text="Server-side encryption KMS key", max_length=256),
                ),
                (
                    "provider",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="s3_config",
                        to="storage.storageprovider",
                    ),
                ),
            ],
            options={
                "verbose_name": "AWS S3 Configuration",
                "verbose_name_plural": "AWS S3 Configurations",
            },
        ),
        migrations.AddConstraint(
            model_name="storageprovider",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)), fields=("is_primary",), name="unique_primary_provider"
            ),
        ),
    ]
