# Generated by Django 5.1.15 on 2026-01-31 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="awss3config",
            name="endpoint_url",
            field=models.CharField(blank=True, help_text="For S3-compatible services", max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="minioconfig",
            name="endpoint_url",
            field=models.CharField(help_text="e.g., http://minio:9000", max_length=500),
        ),
    ]
