# Generated by Django 5.1.15 on 2026-01-30 18:09

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("application_portfolio", "0002_alter_application_options_and_more"),
        ("portfolio_management", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                (
                    "resource",
                    models.CharField(
                        choices=[
                            ("platform_settings", "Platform Settings"),
                            ("storage_config", "Storage Configuration"),
                            ("ai_providers", "AI Providers"),
                            ("integrations", "External Integrations"),
                            ("users", "User Management"),
                            ("roles", "Role Management"),
                            ("applications", "Applications"),
                            ("application_versions", "Application Versions"),
                            ("artifacts", "Artifacts"),
                            ("portfolios", "Portfolios"),
                            ("portfolio_metrics", "Portfolio Metrics"),
                            ("packaging_requests", "Packaging Requests"),
                            ("sbom", "SBOM Data"),
                            ("vulnerability_scans", "Vulnerability Scans"),
                            ("license_inventory", "License Inventory"),
                            ("license_assignments", "License Assignments"),
                            ("license_forecasts", "License Forecasts"),
                            ("vendors", "Vendor Management"),
                            ("cab_requests", "CAB Requests"),
                            ("evidence_packs", "Evidence Packs"),
                            ("approval_decisions", "Approval Decisions"),
                            ("security_exceptions", "Security Exceptions"),
                            ("vulnerability_policy", "Vulnerability Policy"),
                            ("pki_management", "PKI Management"),
                            ("deployment_intents", "Deployment Intents"),
                            ("ring_promotions", "Ring Promotions"),
                            ("rollbacks", "Rollbacks"),
                            ("publishing", "Publishing Operations"),
                            ("execution_planes", "Execution Planes"),
                            ("assets", "Asset Inventory"),
                            ("dex_data", "DEX Telemetry"),
                            ("compliance_data", "Compliance Data"),
                            ("audit_trail", "Audit Trail"),
                            ("event_store", "Event Store"),
                            ("ai_agents", "AI Agents"),
                            ("ai_workflows", "AI Workflows"),
                            ("policy_documents", "Policy Documents"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("read", "Read"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("execute", "Execute"),
                            ("approve", "Approve"),
                            ("reject", "Reject"),
                            ("publish", "Publish"),
                            ("export", "Export"),
                        ],
                        max_length=32,
                    ),
                ),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Permission",
                "verbose_name_plural": "Permissions",
                "ordering": ["resource", "action"],
                "unique_together": {("resource", "action")},
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                (
                    "role_type",
                    models.CharField(
                        choices=[
                            ("platform_admin", "Platform Administrator"),
                            ("application_manager", "Application Manager"),
                            ("portfolio_manager", "Portfolio Manager"),
                            ("packaging_engineer", "Packaging Engineer"),
                            ("license_manager", "License Manager"),
                            ("cab_approver", "CAB Approver"),
                            ("security_reviewer", "Security Reviewer"),
                            ("publisher", "Publisher"),
                            ("auditor", "Auditor"),
                        ],
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("display_name", models.CharField(max_length=128)),
                ("description", models.TextField()),
                ("is_system", models.BooleanField(default=True, help_text="System roles cannot be deleted")),
                ("permissions", models.ManyToManyField(blank=True, related_name="roles", to="rbac.permission")),
            ],
            options={
                "verbose_name": "Role",
                "verbose_name_plural": "Roles",
                "ordering": ["display_name"],
            },
        ),
        migrations.CreateModel(
            name="PermissionAuditLog",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique correlation ID for audit trail and tracing",
                        unique=True,
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("role_assigned", "Role Assigned"),
                            ("role_revoked", "Role Revoked"),
                            ("scope_modified", "Scope Modified"),
                            ("permission_granted", "Permission Granted"),
                            ("permission_revoked", "Permission Revoked"),
                            ("access_denied", "Access Denied"),
                            ("access_granted", "Access Granted"),
                        ],
                        max_length=32,
                    ),
                ),
                ("resource", models.CharField(blank=True, max_length=64)),
                ("resource_id", models.CharField(blank=True, max_length=128)),
                ("action", models.CharField(blank=True, max_length=32)),
                ("details", models.JSONField(default=dict, help_text="Additional context")),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Permission Audit Log",
                "verbose_name_plural": "Permission Audit Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["actor", "created_at"], name="rbac_permis_actor_i_b1abc1_idx"),
                    models.Index(fields=["target_user", "created_at"], name="rbac_permis_target__af702f_idx"),
                    models.Index(fields=["action_type", "created_at"], name="rbac_permis_action__e830f0_idx"),
                    models.Index(fields=["correlation_id"], name="rbac_permis_correla_be92f9_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                (
                    "business_unit_scope",
                    models.CharField(
                        blank=True, help_text="Restrict to this business unit (empty = all)", max_length=128
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("valid_from", models.DateTimeField(default=django.utils.timezone.now)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                (
                    "application_scope",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Restrict to these applications (empty = all applications)",
                        related_name="role_assignments",
                        to="application_portfolio.application",
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="role_assignments_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "portfolio_scope",
                    models.ForeignKey(
                        blank=True,
                        help_text="Restrict to this portfolio (null = all portfolios)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_assignments",
                        to="portfolio_management.portfolio",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="user_assignments", to="rbac.role"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Role Assignment",
                "verbose_name_plural": "User Role Assignments",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "is_active"], name="rbac_userro_user_id_78ba5c_idx"),
                    models.Index(fields=["role", "is_active"], name="rbac_userro_role_id_a513d2_idx"),
                ],
            },
        ),
    ]
