# Generated by Django 5.1.15 on 2026-01-31 07:25

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CommunicationTemplate",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                (
                    "communication_type",
                    models.CharField(
                        choices=[
                            ("status_update", "Status Update"),
                            ("sla_warning", "SLA Warning"),
                            ("escalation", "Escalation"),
                            ("completion", "Completion"),
                            ("weekly_digest", "Weekly Digest"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("teams", "Microsoft Teams"),
                            ("slack", "Slack"),
                            ("servicenow", "ServiceNow Notification"),
                        ],
                        max_length=50,
                    ),
                ),
                ("subject_template", models.CharField(max_length=500)),
                ("body_template", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("variables", models.JSONField(default=list, help_text="List of available template variables")),
            ],
            options={
                "verbose_name": "Communication Template",
                "verbose_name_plural": "Communication Templates",
                "ordering": ["communication_type", "channel"],
                "indexes": [
                    models.Index(
                        fields=["communication_type", "channel", "is_active"], name="request_coo_communi_c3daeb_idx"
                    )
                ],
                "unique_together": {("communication_type", "channel")},
            },
        ),
        migrations.CreateModel(
            name="EscalationRule",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("request_type", models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("sla_warning", "SLA Warning"),
                            ("sla_breach", "SLA Breach"),
                            ("blocked", "Blocked"),
                            ("reassignment", "Multiple Reassignments"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "trigger_config",
                    models.JSONField(
                        default=dict, help_text="Trigger configuration (hours_before_breach, blocked_days, etc.)"
                    ),
                ),
                (
                    "escalation_actions",
                    models.JSONField(
                        default=list,
                        help_text="Actions to take when triggered (notify, escalate, update_priority, etc.)",
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "verbose_name": "Escalation Rule",
                "verbose_name_plural": "Escalation Rules",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["trigger_type", "is_active"], name="request_coo_trigger_522421_idx"),
                    models.Index(fields=["request_type", "is_active"], name="request_coo_request_e65e07_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="TrackedRequest",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique correlation ID for audit trail and tracing",
                        unique=True,
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("servicenow_number", models.CharField(db_index=True, max_length=50, unique=True)),
                ("servicenow_sys_id", models.CharField(max_length=100)),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("software_install", "Software Installation"),
                            ("access_request", "Access Request"),
                            ("hardware", "Hardware Request"),
                            ("config_change", "Configuration Change"),
                            ("exception", "Exception Request"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("short_description", models.CharField(max_length=255)),
                ("requestor_email", models.EmailField(max_length=254)),
                ("requestor_name", models.CharField(max_length=255)),
                ("assigned_to", models.CharField(blank=True, max_length=255, null=True)),
                ("assignment_group", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("in_progress", "In Progress"),
                            ("pending", "Pending"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=50,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("1", "Critical"), ("2", "High"), ("3", "Medium"), ("4", "Low")],
                        db_index=True,
                        default="3",
                        max_length=20,
                    ),
                ),
                ("sla_due", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_escalated", models.BooleanField(db_index=True, default=False)),
                ("escalation_level", models.IntegerField(default=0)),
                ("last_updated", models.DateTimeField(default=django.utils.timezone.now)),
                ("blocked_reason", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Tracked Request",
                "verbose_name_plural": "Tracked Requests",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["status", "priority"], name="request_coo_status_58606b_idx"),
                    models.Index(fields=["sla_due", "is_escalated"], name="request_coo_sla_due_368f2a_idx"),
                    models.Index(fields=["correlation_id"], name="request_coo_correla_a15f61_idx"),
                    models.Index(fields=["request_type", "status"], name="request_coo_request_1b9dc5_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="RequestStatusUpdate",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("old_status", models.CharField(max_length=50)),
                ("new_status", models.CharField(max_length=50)),
                ("update_notes", models.TextField(blank=True, null=True)),
                ("updated_by", models.CharField(max_length=255)),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_updates",
                        to="request_coordination.trackedrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Request Status Update",
                "verbose_name_plural": "Request Status Updates",
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["request", "created_at"], name="request_coo_request_852cd2_idx")],
            },
        ),
        migrations.CreateModel(
            name="RequestStakeholder",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=254)),
                ("name", models.CharField(max_length=255)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("requestor", "Requestor"),
                            ("approver", "Approver"),
                            ("watcher", "Watcher"),
                            ("manager", "Manager"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "notification_preferences",
                    models.JSONField(default=dict, help_text="Notification preferences (channels, frequency, etc.)"),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stakeholders",
                        to="request_coordination.trackedrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Request Stakeholder",
                "verbose_name_plural": "Request Stakeholders",
                "ordering": ["role", "name"],
                "indexes": [
                    models.Index(fields=["request", "role"], name="request_coo_request_426980_idx"),
                    models.Index(fields=["email"], name="request_coo_email_bfc6ed_idx"),
                ],
                "unique_together": {("request", "email")},
            },
        ),
        migrations.CreateModel(
            name="RequestCommunication",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique correlation ID for audit trail and tracing",
                        unique=True,
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "communication_type",
                    models.CharField(
                        choices=[
                            ("status_update", "Status Update"),
                            ("sla_warning", "SLA Warning"),
                            ("escalation", "Escalation"),
                            ("completion", "Completion"),
                            ("weekly_digest", "Weekly Digest"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("teams", "Microsoft Teams"),
                            ("slack", "Slack"),
                            ("servicenow", "ServiceNow Notification"),
                        ],
                        max_length=50,
                    ),
                ),
                ("recipients", models.JSONField(default=list)),
                ("subject", models.CharField(max_length=500)),
                ("body", models.TextField()),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="communications",
                        to="request_coordination.trackedrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Request Communication",
                "verbose_name_plural": "Request Communications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["request", "communication_type"], name="request_coo_request_0856ac_idx"),
                    models.Index(fields=["channel", "status"], name="request_coo_channel_0031f2_idx"),
                    models.Index(fields=["correlation_id"], name="request_coo_correla_c3a976_idx"),
                    models.Index(fields=["sent_at"], name="request_coo_sent_at_1f5536_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="EscalationEvent",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique correlation ID for audit trail and tracing",
                        unique=True,
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("trigger_reason", models.TextField()),
                ("escalation_level", models.IntegerField(default=1)),
                ("actions_taken", models.JSONField(default=list)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="request_coordination.escalationrule",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="escalation_events",
                        to="request_coordination.trackedrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Escalation Event",
                "verbose_name_plural": "Escalation Events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["request", "escalation_level"], name="request_coo_request_01cd48_idx"),
                    models.Index(fields=["correlation_id"], name="request_coo_correla_17d548_idx"),
                    models.Index(fields=["resolved_at"], name="request_coo_resolve_491fa2_idx"),
                ],
            },
        ),
    ]
