# Generated by Django 5.0.14 on 2026-01-04 19:15

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeploymentIntent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique correlation ID for audit trail and tracing",
                        unique=True,
                    ),
                ),
                (
                    "app_name",
                    models.CharField(help_text="Application name", max_length=255),
                ),
                (
                    "version",
                    models.CharField(help_text="Application version", max_length=50),
                ),
                (
                    "target_ring",
                    models.CharField(
                        choices=[
                            ("LAB", "Lab"),
                            ("CANARY", "Canary"),
                            ("PILOT", "Pilot"),
                            ("DEPARTMENT", "Department"),
                            ("GLOBAL", "Global"),
                        ],
                        help_text="Target deployment ring",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("AWAITING_CAB", "Awaiting CAB Approval"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("DEPLOYING", "Deploying"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("ROLLED_BACK", "Rolled Back"),
                        ],
                        default="PENDING",
                        help_text="Deployment status",
                        max_length=20,
                    ),
                ),
                (
                    "evidence_pack_id",
                    models.UUIDField(help_text="Evidence pack correlation ID"),
                ),
                (
                    "risk_score",
                    models.IntegerField(blank=True, help_text="Calculated risk score (0-100)", null=True),
                ),
                (
                    "requires_cab_approval",
                    models.BooleanField(default=False, help_text="Whether CAB approval is required"),
                ),
                (
                    "submitter",
                    models.ForeignKey(
                        help_text="User who submitted the deployment",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deployment_intents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Deployment Intent",
                "verbose_name_plural": "Deployment Intents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RingDeployment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ring",
                    models.CharField(
                        choices=[
                            ("LAB", "Lab"),
                            ("CANARY", "Canary"),
                            ("PILOT", "Pilot"),
                            ("DEPARTMENT", "Department"),
                            ("GLOBAL", "Global"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "connector_type",
                    models.CharField(
                        help_text="Connector type (intune, jamf, sccm, landscape, ansible)",
                        max_length=20,
                    ),
                ),
                (
                    "connector_object_id",
                    models.CharField(
                        blank=True,
                        help_text="Platform-specific object ID",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "success_count",
                    models.IntegerField(default=0, help_text="Number of successful deployments"),
                ),
                (
                    "failure_count",
                    models.IntegerField(default=0, help_text="Number of failed deployments"),
                ),
                (
                    "success_rate",
                    models.FloatField(default=0.0, help_text="Success rate (0.0 - 1.0)"),
                ),
                (
                    "promoted_at",
                    models.DateTimeField(blank=True, help_text="When promoted to next ring", null=True),
                ),
                (
                    "promotion_gate_passed",
                    models.BooleanField(default=False, help_text="Whether promotion gate criteria met"),
                ),
                (
                    "deployment_intent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ring_deployments",
                        to="deployment_intents.deploymentintent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ring Deployment",
                "verbose_name_plural": "Ring Deployments",
            },
        ),
        migrations.AddIndex(
            model_name="deploymentintent",
            index=models.Index(fields=["status", "target_ring"], name="deployment__status_acb901_idx"),
        ),
        migrations.AddIndex(
            model_name="deploymentintent",
            index=models.Index(fields=["correlation_id"], name="deployment__correla_6a02c2_idx"),
        ),
        migrations.AddIndex(
            model_name="deploymentintent",
            index=models.Index(fields=["app_name", "version"], name="deployment__app_nam_032ae3_idx"),
        ),
        migrations.AddIndex(
            model_name="ringdeployment",
            index=models.Index(
                fields=["deployment_intent", "ring"],
                name="deployment__deploym_e08807_idx",
            ),
        ),
    ]
