# Generated by Django 5.0.14 on 2026-01-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployment_intents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentintent',
            name='is_demo',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this is demo data'),
        ),
        migrations.AddField(
            model_name='ringdeployment',
            name='is_demo',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this is demo data'),
        ),
    ]
