# Generated by Django 5.0.14 on 2026-01-21 18:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deployment_intents", "0002_add_is_demo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="deploymentintent",
            constraint=models.CheckConstraint(
                check=models.Q(("risk_score__gte", 0), ("risk_score__lte", 100)), name="risk_score_between_0_and_100"
            ),
        ),
        migrations.AddConstraint(
            model_name="ringdeployment",
            constraint=models.CheckConstraint(
                check=models.Q(("success_count__gte", 0)), name="success_count_non_negative"
            ),
        ),
        migrations.AddConstraint(
            model_name="ringdeployment",
            constraint=models.CheckConstraint(
                check=models.Q(("failure_count__gte", 0)), name="failure_count_non_negative"
            ),
        ),
        migrations.AddConstraint(
            model_name="ringdeployment",
            constraint=models.CheckConstraint(
                check=models.Q(("success_rate__gte", 0.0), ("success_rate__lte", 1.0)),
                name="success_rate_between_0_and_1",
            ),
        ),
    ]
