# Generated by Django 5.1.15 on 2026-01-31 12:03

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("application_portfolio", "0002_alter_application_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthEndpoint",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("url", models.URLField()),
                ("method", models.CharField(default="GET", max_length=10)),
                ("expected_status", models.IntegerField(default=200)),
                ("timeout_seconds", models.IntegerField(default=30)),
                ("check_interval_minutes", models.IntegerField(default=5)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="application_portfolio.application",
                    ),
                ),
            ],
            options={
                "verbose_name": "Health Endpoint",
                "verbose_name_plural": "Health Endpoints",
            },
        ),
        migrations.CreateModel(
            name="HealthCheckResult",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("check_time", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                (
                    "status",
                    models.CharField(
                        choices=[("healthy", "Healthy"), ("degraded", "Degraded"), ("unhealthy", "Unhealthy")],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("response_time_ms", models.IntegerField(blank=True, null=True)),
                ("status_code", models.IntegerField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "endpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="check_results",
                        to="sre_agent.healthendpoint",
                    ),
                ),
            ],
            options={
                "verbose_name": "Health Check Result",
                "verbose_name_plural": "Health Check Results",
                "ordering": ["-check_time"],
            },
        ),
        migrations.CreateModel(
            name="MonitoringPlatform",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                (
                    "platform_type",
                    models.CharField(
                        choices=[
                            ("prometheus", "Prometheus"),
                            ("datadog", "Datadog"),
                            ("azure_monitor", "Azure Monitor"),
                            ("newrelic", "New Relic"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("connection_config", models.JSONField(default=dict, help_text="Platform connection configuration")),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Monitoring Platform",
                "verbose_name_plural": "Monitoring Platforms",
                "indexes": [models.Index(fields=["platform_type", "is_active"], name="sre_agent_m_platfor_7dc926_idx")],
            },
        ),
        migrations.CreateModel(
            name="Runbook",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("category", models.CharField(db_index=True, max_length=100)),
                ("steps", models.JSONField(default=list, help_text="List of runbook steps")),
                (
                    "automation_level",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("semi_auto", "Semi-Automated"),
                            ("full_auto", "Fully Automated"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("R1", "R1 - Low (Auto-execute allowed)"),
                            ("R2", "R2 - Medium (Policy-dependent approval)"),
                            ("R3", "R3 - High (Mandatory human approval)"),
                        ],
                        default="R2",
                        max_length=10,
                    ),
                ),
                ("estimated_duration_minutes", models.IntegerField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Runbook",
                "verbose_name_plural": "Runbooks",
                "indexes": [
                    models.Index(fields=["category", "is_active"], name="sre_agent_r_categor_22c893_idx"),
                    models.Index(fields=["risk_level", "is_active"], name="sre_agent_r_risk_le_ecbe0f_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="RunbookExecution",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique correlation ID for audit trail and tracing",
                        unique=True,
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("trigger_reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("current_step", models.IntegerField(default=0)),
                ("step_results", models.JSONField(default=list, help_text="Results for each step")),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("evidence", models.JSONField(default=list, help_text="Evidence collected during execution")),
                (
                    "executed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runbook_executions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "runbook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="executions", to="sre_agent.runbook"
                    ),
                ),
            ],
            options={
                "verbose_name": "Runbook Execution",
                "verbose_name_plural": "Runbook Executions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SelfHealingRule",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("threshold", "Threshold"),
                            ("pattern", "Pattern"),
                            ("schedule", "Schedule"),
                            ("alert", "Alert"),
                        ],
                        max_length=50,
                    ),
                ),
                ("trigger_config", models.JSONField(default=dict, help_text="Trigger configuration")),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("service", "Service"),
                            ("process", "Process"),
                            ("disk", "Disk"),
                            ("connection", "Connection"),
                        ],
                        max_length=50,
                    ),
                ),
                ("target_config", models.JSONField(default=dict, help_text="Target configuration")),
                ("remediation_script", models.TextField(help_text="Remediation script content")),
                (
                    "script_type",
                    models.CharField(
                        choices=[("powershell", "PowerShell"), ("bash", "Bash"), ("python", "Python")],
                        default="powershell",
                        max_length=20,
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("R1", "R1 - Low (Auto-execute allowed)"),
                            ("R2", "R2 - Medium (Policy-dependent approval)"),
                            ("R3", "R3 - High (Mandatory human approval)"),
                        ],
                        default="R2",
                        max_length=10,
                    ),
                ),
                ("requires_approval", models.BooleanField(default=False)),
                ("max_executions_per_hour", models.IntegerField(default=3)),
                ("cooldown_minutes", models.IntegerField(default=15)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Self-Healing Rule",
                "verbose_name_plural": "Self-Healing Rules",
                "indexes": [
                    models.Index(fields=["is_active", "trigger_type"], name="sre_agent_s_is_acti_eee749_idx"),
                    models.Index(fields=["risk_level", "is_active"], name="sre_agent_s_risk_le_e7890b_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SelfHealingExecution",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique correlation ID for audit trail and tracing",
                        unique=True,
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("trigger_event", models.JSONField(default=dict, help_text="Event that triggered execution")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("executing", "Executing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("output", models.TextField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("metrics_before", models.JSONField(blank=True, help_text="Metrics before remediation", null=True)),
                ("metrics_after", models.JSONField(blank=True, help_text="Metrics after remediation", null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_healing_executions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="sre_agent.selfhealingrule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Self-Healing Execution",
                "verbose_name_plural": "Self-Healing Executions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SLODefinition",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("service_name", models.CharField(db_index=True, max_length=255)),
                (
                    "slo_type",
                    models.CharField(
                        choices=[
                            ("availability", "Availability"),
                            ("latency", "Latency"),
                            ("error_rate", "Error Rate"),
                            ("throughput", "Throughput"),
                        ],
                        max_length=50,
                    ),
                ),
                ("target_value", models.FloatField(help_text="Target value (e.g., 99.9 for availability %)")),
                ("target_unit", models.CharField(help_text="Unit (percent, ms, per_second)", max_length=20)),
                (
                    "measurement_window",
                    models.CharField(
                        choices=[
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "error_budget_policy",
                    models.JSONField(blank=True, help_text="Error budget policy configuration", null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "SLO Definition",
                "verbose_name_plural": "SLO Definitions",
                "indexes": [
                    models.Index(fields=["service_name", "is_active"], name="sre_agent_s_service_577c0c_idx"),
                    models.Index(fields=["slo_type", "is_active"], name="sre_agent_s_slo_typ_e54cc2_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SLOMetric",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("measurement_time", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("actual_value", models.FloatField()),
                ("target_met", models.BooleanField()),
                ("error_budget_remaining", models.FloatField(blank=True, null=True)),
                ("burn_rate", models.FloatField(blank=True, null=True)),
                (
                    "slo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="sre_agent.slodefinition",
                    ),
                ),
            ],
            options={
                "verbose_name": "SLO Metric",
                "verbose_name_plural": "SLO Metrics",
                "ordering": ["-measurement_time"],
            },
        ),
        migrations.AddIndex(
            model_name="healthendpoint",
            index=models.Index(fields=["is_active", "application"], name="sre_agent_h_is_acti_d21d24_idx"),
        ),
        migrations.AddIndex(
            model_name="healthcheckresult",
            index=models.Index(fields=["endpoint", "check_time"], name="sre_agent_h_endpoin_8afc03_idx"),
        ),
        migrations.AddIndex(
            model_name="healthcheckresult",
            index=models.Index(fields=["status", "check_time"], name="sre_agent_h_status_0b34ae_idx"),
        ),
        migrations.AddIndex(
            model_name="runbookexecution",
            index=models.Index(fields=["runbook", "status"], name="sre_agent_r_runbook_e2b28e_idx"),
        ),
        migrations.AddIndex(
            model_name="runbookexecution",
            index=models.Index(fields=["status", "created_at"], name="sre_agent_r_status_063e80_idx"),
        ),
        migrations.AddIndex(
            model_name="runbookexecution",
            index=models.Index(fields=["correlation_id"], name="sre_agent_r_correla_240a48_idx"),
        ),
        migrations.AddIndex(
            model_name="selfhealingexecution",
            index=models.Index(fields=["rule", "status"], name="sre_agent_s_rule_id_4d8ccf_idx"),
        ),
        migrations.AddIndex(
            model_name="selfhealingexecution",
            index=models.Index(fields=["status", "created_at"], name="sre_agent_s_status_910ee3_idx"),
        ),
        migrations.AddIndex(
            model_name="selfhealingexecution",
            index=models.Index(fields=["correlation_id"], name="sre_agent_s_correla_aa9c8a_idx"),
        ),
        migrations.AddIndex(
            model_name="slometric",
            index=models.Index(fields=["slo", "measurement_time"], name="sre_agent_s_slo_id_89d8dc_idx"),
        ),
        migrations.AddIndex(
            model_name="slometric",
            index=models.Index(fields=["target_met", "measurement_time"], name="sre_agent_s_target__7954e4_idx"),
        ),
    ]
