# Generated by Django 5.0.14 on 2026-01-04 19:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("deployment_intents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CABApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("CONDITIONAL", "Conditional"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "comments",
                    models.TextField(
                        blank=True, help_text="Approval/rejection comments"
                    ),
                ),
                (
                    "conditions",
                    models.JSONField(
                        default=list, help_text="Conditional approval conditions"
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cab_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deployment_intent",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cab_approval",
                        to="deployment_intents.deploymentintent",
                    ),
                ),
            ],
            options={
                "verbose_name": "CAB Approval",
                "verbose_name_plural": "CAB Approvals",
            },
        ),
    ]
