# Generated by Django 5.0.14 on 2026-01-21 18:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cab_workflow", "0003_add_external_change_request_id"),
        ("deployment_intents", "0003_deploymentintent_risk_score_between_0_and_100_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="cabapproval",
            index=models.Index(fields=["decision", "created_at"], name="cab_workflo_decisio_29d224_idx"),
        ),
        migrations.AddIndex(
            model_name="cabapproval",
            index=models.Index(fields=["approver", "created_at"], name="cab_workflo_approve_926292_idx"),
        ),
        migrations.AddIndex(
            model_name="cabapproval",
            index=models.Index(fields=["deployment_intent"], name="cab_workflo_deploym_fbe2ef_idx"),
        ),
    ]
