# Generated by Django 5.0.14 on 2026-01-23 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cab_workflow', '0005_p5_cab_workflow'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cabapprovaldecision',
            new_name='cab_workflo_cab_req_129996_idx',
            old_name='cab_workflow_cab_req_idx',
        ),
        migrations.RenameIndex(
            model_name='cabapprovaldecision',
            new_name='cab_workflo_decisio_1602c7_idx',
            old_name='cab_workflow_decision_idx',
        ),
        migrations.RenameIndex(
            model_name='cabapprovalrequest',
            new_name='cab_workflo_deploym_e21db2_idx',
            old_name='cab_workflow_deploym_idx',
        ),
        migrations.RenameIndex(
            model_name='cabapprovalrequest',
            new_name='cab_workflo_status_748fd1_idx',
            old_name='cab_workflow_status_idx',
        ),
        migrations.RenameIndex(
            model_name='cabapprovalrequest',
            new_name='cab_workflo_risk_sc_b5c709_idx',
            old_name='cab_workflow_risksco_idx',
        ),
        migrations.RenameIndex(
            model_name='cabexception',
            new_name='cab_workflo_deploym_fc7365_idx',
            old_name='cab_workflow_deploym_idx2',
        ),
        migrations.RenameIndex(
            model_name='cabexception',
            new_name='cab_workflo_status_ab15a7_idx',
            old_name='cab_workflow_status_idx2',
        ),
    ]
