# Generated by Django 5.0.14 on 2026-01-08 19:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="externalsystem",
            new_name="integration_type_dbf029_idx",
            old_name="integrations_type_is_en_idx",
        ),
        migrations.RenameIndex(
            model_name="externalsystem",
            new_name="integration_last_sy_b93f5e_idx",
            old_name="integrations_last_syn_idx",
        ),
        migrations.RenameIndex(
            model_name="externalsystem",
            new_name="integration_is_demo_3ddba6_idx",
            old_name="integrations_is_demo_idx",
        ),
        migrations.RenameIndex(
            model_name="integrationsynclog",
            new_name="integration_system__0f1ce2_idx",
            old_name="integrations_system_sync_idx",
        ),
        migrations.RenameIndex(
            model_name="integrationsynclog",
            new_name="integration_status_5108e9_idx",
            old_name="integrations_status_sync_idx",
        ),
        migrations.RenameIndex(
            model_name="integrationsynclog",
            new_name="integration_correla_bbe839_idx",
            old_name="integrations_correlat_idx",
        ),
        migrations.AlterField(
            model_name="externalsystem",
            name="created_at",
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name="integrationsynclog",
            name="created_at",
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
        ),
    ]
