# Generated by Django 5.1.15 on 2026-01-30 20:38

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import apps.core.encryption


class Migration(migrations.Migration):

    dependencies = [
        ("connectors", "0004_rename_connector_i_connect_idx_connector_i_connect_379f48_idx_and_more"),
        ("integrations", "0002_rename_integrations_type_is_en_idx_integration_type_dbf029_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DEXProvider",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique correlation ID for audit trail and tracing",
                        unique=True,
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("name", models.CharField(default="1E DEX Platform", max_length=128)),
                (
                    "provider_type",
                    models.CharField(
                        choices=[("1e", "1E DEX Platform"), ("mock", "Mock Data Provider")],
                        default="mock",
                        max_length=16,
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "server_url",
                    models.URLField(
                        blank=True, help_text="1E server URL (e.g., https://1e-server.example.com)", null=True
                    ),
                ),
                (
                    "auth_method",
                    models.CharField(
                        choices=[
                            ("ntlm", "Windows Authentication (NTLM)"),
                            ("basic", "Basic Authentication"),
                            ("api_key", "API Key"),
                        ],
                        default="basic",
                        max_length=16,
                    ),
                ),
                ("username", apps.core.encryption.EncryptedCharField(blank=True, max_length=256)),
                ("password", apps.core.encryption.EncryptedCharField(blank=True, max_length=256)),
                ("api_key", apps.core.encryption.EncryptedCharField(blank=True, max_length=256)),
                ("sync_interval_minutes", models.IntegerField(default=60, help_text="Sync interval in minutes")),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("last_sync_status", models.CharField(blank=True, max_length=32)),
                ("last_sync_error", models.TextField(blank=True)),
                ("retention_days", models.IntegerField(default=90, help_text="Days to retain DEX metrics")),
            ],
            options={
                "verbose_name": "DEX Provider",
                "verbose_name_plural": "DEX Providers",
                "db_table": "integrations_dex_provider",
            },
        ),
        migrations.CreateModel(
            name="DEXAggregateMetrics",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique correlation ID for audit trail and tracing",
                        unique=True,
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("period_start", models.DateTimeField(db_index=True, help_text="Start of aggregation period")),
                ("period_end", models.DateTimeField(help_text="End of aggregation period")),
                ("aggregation_type", models.CharField(help_text="Type: 'hourly', 'daily', or 'weekly'", max_length=16)),
                ("total_devices", models.IntegerField(default=0, help_text="Total devices in period")),
                ("devices_with_dex", models.IntegerField(default=0, help_text="Devices with DEX scores")),
                ("avg_dex_score", models.FloatField(blank=True, help_text="Average DEX score", null=True)),
                ("min_dex_score", models.FloatField(blank=True, help_text="Minimum DEX score", null=True)),
                ("max_dex_score", models.FloatField(blank=True, help_text="Maximum DEX score", null=True)),
                (
                    "dex_score_std_dev",
                    models.FloatField(blank=True, help_text="Standard deviation of DEX scores", null=True),
                ),
                ("avg_boot_time", models.IntegerField(blank=True, help_text="Average boot time in seconds", null=True)),
                ("p50_boot_time", models.IntegerField(blank=True, help_text="50th percentile boot time", null=True)),
                ("p95_boot_time", models.IntegerField(blank=True, help_text="95th percentile boot time", null=True)),
                (
                    "positive_sentiment_count",
                    models.IntegerField(default=0, help_text="Devices with positive sentiment"),
                ),
                ("neutral_sentiment_count", models.IntegerField(default=0, help_text="Devices with neutral sentiment")),
                (
                    "negative_sentiment_count",
                    models.IntegerField(default=0, help_text="Devices with negative sentiment"),
                ),
                (
                    "total_carbon_kg",
                    models.FloatField(blank=True, help_text="Total carbon footprint in kg CO2", null=True),
                ),
                (
                    "total_power_kwh",
                    models.FloatField(blank=True, help_text="Total power consumption in kWh", null=True),
                ),
            ],
            options={
                "verbose_name": "DEX Aggregate Metrics",
                "verbose_name_plural": "DEX Aggregate Metrics",
                "db_table": "integrations_dex_aggregate_metrics",
                "ordering": ["-period_start"],
                "indexes": [
                    models.Index(fields=["period_start", "aggregation_type"], name="integration_period__9dd71b_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="DEXDeviceMetrics",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique correlation ID for audit trail and tracing",
                        unique=True,
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                (
                    "device_id",
                    models.CharField(db_index=True, help_text="Device identifier from 1E or mock", max_length=128),
                ),
                ("device_name", models.CharField(help_text="Human-readable device name", max_length=256)),
                ("dex_score", models.FloatField(blank=True, help_text="Overall DEX score (0-10)", null=True)),
                ("performance_score", models.FloatField(blank=True, help_text="Performance score (0-10)", null=True)),
                ("stability_score", models.FloatField(blank=True, help_text="Stability score (0-10)", null=True)),
                (
                    "responsiveness_score",
                    models.FloatField(blank=True, help_text="Responsiveness score (0-10)", null=True),
                ),
                ("boot_time_seconds", models.IntegerField(blank=True, help_text="Boot time in seconds", null=True)),
                ("login_time_seconds", models.IntegerField(blank=True, help_text="Login time in seconds", null=True)),
                (
                    "user_sentiment",
                    models.CharField(
                        blank=True, help_text="User sentiment: Positive, Neutral, or Negative", max_length=32
                    ),
                ),
                (
                    "sentiment_score",
                    models.FloatField(
                        blank=True, help_text="Sentiment score (-1 to 1, where 1 is most positive)", null=True
                    ),
                ),
                (
                    "carbon_footprint_kg",
                    models.FloatField(blank=True, help_text="Annual estimated carbon footprint in kg CO2", null=True),
                ),
                (
                    "power_consumption_kwh",
                    models.FloatField(blank=True, help_text="Monthly power consumption in kWh", null=True),
                ),
                ("collected_at", models.DateTimeField(help_text="When metrics were collected from source")),
                ("source", models.CharField(default="1e", help_text="Source: '1e' or 'mock'", max_length=16)),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        help_text="Linked asset record if device matches asset inventory",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dex_metrics",
                        to="connectors.asset",
                    ),
                ),
            ],
            options={
                "verbose_name": "DEX Device Metrics",
                "verbose_name_plural": "DEX Device Metrics",
                "db_table": "integrations_dex_device_metrics",
                "get_latest_by": "collected_at",
                "indexes": [
                    models.Index(fields=["device_id", "collected_at"], name="integration_device__c30885_idx"),
                    models.Index(fields=["asset", "collected_at"], name="integration_asset_i_4a9d89_idx"),
                    models.Index(fields=["collected_at"], name="integration_collect_ecf4d9_idx"),
                ],
            },
        ),
    ]
