# Generated by Django 5.0.14 on 2026-01-04 19:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RiskModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "version",
                    models.CharField(
                        help_text="Risk model version (e.g., v1.0)",
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "factors",
                    models.JSONField(help_text="List of risk factors with weights and rubrics"),
                ),
                (
                    "threshold",
                    models.IntegerField(default=50, help_text="CAB approval threshold (0-100)"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Active risk model (only one can be active)",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description of changes in this version"),
                ),
            ],
            options={
                "verbose_name": "Risk Model",
                "verbose_name_plural": "Risk Models",
                "ordering": ["-version"],
            },
        ),
        migrations.CreateModel(
            name="RiskAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deployment_intent_id",
                    models.UUIDField(help_text="Deployment intent correlation ID"),
                ),
                (
                    "risk_model_version",
                    models.CharField(help_text="Risk model version used", max_length=10),
                ),
                (
                    "risk_score",
                    models.IntegerField(help_text="Calculated risk score (0-100)"),
                ),
                (
                    "factor_scores",
                    models.JSONField(help_text="Detailed breakdown per factor"),
                ),
                (
                    "requires_cab_approval",
                    models.BooleanField(help_text="Whether CAB approval is required"),
                ),
            ],
            options={
                "verbose_name": "Risk Assessment",
                "verbose_name_plural": "Risk Assessments",
                "indexes": [
                    models.Index(fields=["risk_score"], name="policy_engi_risk_sc_61fe34_idx"),
                    models.Index(
                        fields=["deployment_intent_id"],
                        name="policy_engi_deploym_154037_idx",
                    ),
                ],
            },
        ),
    ]
