# Generated by Django 5.1.15 on 2026-01-30 19:37

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application_portfolio", "0002_alter_application_options_and_more"),
        ("policy_engine", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationPolicy",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique correlation ID for audit trail and tracing",
                        unique=True,
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(help_text="Policy name", max_length=128)),
                ("description", models.TextField(blank=True, help_text="Policy description")),
                (
                    "platform",
                    models.CharField(help_text="Target platform (windows, macos, linux, ios, android)", max_length=32),
                ),
                ("is_active", models.BooleanField(default=True, help_text="Whether policy is active")),
                ("is_default", models.BooleanField(default=False, help_text="Default policy for app/platform")),
                (
                    "application",
                    models.ForeignKey(
                        help_text="Target application",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policies",
                        to="application_portfolio.application",
                    ),
                ),
                (
                    "application_version",
                    models.ForeignKey(
                        blank=True,
                        help_text="Apply to specific version only (null = all versions)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policies",
                        to="application_portfolio.applicationversion",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created the policy",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_policies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Application Policy",
                "verbose_name_plural": "Application Policies",
                "ordering": ["application", "platform", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PolicySetting",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("installation", "Installation"),
                            ("uninstall", "Uninstall"),
                            ("update", "Update"),
                            ("configuration", "Configuration"),
                            ("restart", "Device Restart"),
                            ("dependency", "Dependencies"),
                            ("compliance", "Compliance"),
                        ],
                        help_text="Setting category",
                        max_length=32,
                    ),
                ),
                ("setting_key", models.CharField(help_text="Setting key", max_length=64)),
                ("setting_value", models.JSONField(help_text="Setting value (flexible JSON)")),
                ("intune_mapping", models.JSONField(blank=True, default=dict, help_text="Intune-specific mapping")),
                ("jamf_mapping", models.JSONField(blank=True, default=dict, help_text="Jamf Pro-specific mapping")),
                ("sccm_mapping", models.JSONField(blank=True, default=dict, help_text="SCCM-specific mapping")),
                (
                    "policy",
                    models.ForeignKey(
                        help_text="Parent policy",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="policy_engine.applicationpolicy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Policy Setting",
                "verbose_name_plural": "Policy Settings",
                "ordering": ["policy", "category", "setting_key"],
            },
        ),
        migrations.CreateModel(
            name="PolicyTemplate",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(help_text="Template name", max_length=128)),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("standard", "Standard Application"),
                            ("security", "Security-Critical"),
                            ("productivity", "Productivity Suite"),
                            ("browser", "Web Browser"),
                            ("development", "Development Tool"),
                            ("enterprise", "Enterprise Required"),
                            ("optional", "Optional/Self-Service"),
                            ("custom", "Custom Template"),
                        ],
                        help_text="Template type",
                        max_length=32,
                    ),
                ),
                ("description", models.TextField(help_text="Template description")),
                ("settings", models.JSONField(default=dict, help_text="Pre-configured settings dictionary")),
                (
                    "is_system",
                    models.BooleanField(default=False, help_text="Whether this is a system template (read-only)"),
                ),
                (
                    "platform",
                    models.CharField(
                        blank=True, help_text="Platform-specific template (empty = all platforms)", max_length=32
                    ),
                ),
            ],
            options={
                "verbose_name": "Policy Template",
                "verbose_name_plural": "Policy Templates",
                "ordering": ["template_type", "name"],
                "indexes": [
                    models.Index(fields=["template_type"], name="policy_engi_templat_2bc5d4_idx"),
                    models.Index(fields=["is_system"], name="policy_engi_is_syst_19ef0c_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="applicationpolicy",
            index=models.Index(fields=["application", "platform"], name="policy_engi_applica_563185_idx"),
        ),
        migrations.AddIndex(
            model_name="applicationpolicy",
            index=models.Index(fields=["is_active"], name="policy_engi_is_acti_ece4d6_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="applicationpolicy",
            unique_together={("application", "application_version", "platform")},
        ),
        migrations.AddIndex(
            model_name="policysetting",
            index=models.Index(fields=["policy", "category"], name="policy_engi_policy__b6c5ac_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="policysetting",
            unique_together={("policy", "category", "setting_key")},
        ),
    ]
