# Generated by Django 5.1.15 on 2026-01-31 06:26

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DetectionRule",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(help_text="Rule name", max_length=255)),
                ("description", models.TextField(help_text="Rule description")),
                (
                    "anomaly_type",
                    models.CharField(
                        choices=[
                            ("suspicious_login", "Suspicious Login"),
                            ("authentication_attack", "Authentication Attack"),
                            ("unusual_activity", "Unusual Activity"),
                            ("new_device", "New Device"),
                            ("privilege_change", "Privilege Change"),
                            ("dormant_activation", "Dormant Account Activation"),
                            ("service_account_abuse", "Service Account Abuse"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[("low", "Low"), ("medium", "Medium"), ("high", "High"), ("critical", "Critical")],
                        max_length=20,
                    ),
                ),
                ("rule_config", models.JSONField(default=dict, help_text="Rule configuration")),
                ("threshold_config", models.JSONField(default=dict, help_text="Threshold configuration")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("last_triggered", models.DateTimeField(blank=True, null=True)),
                ("trigger_count", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Detection Rule",
                "verbose_name_plural": "Detection Rules",
                "ordering": ["anomaly_type", "name"],
                "indexes": [
                    models.Index(fields=["anomaly_type", "is_active"], name="iam_securit_anomaly_537f5c_idx"),
                    models.Index(fields=["severity"], name="iam_securit_severit_f6cda8_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="IdentityProvider",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(help_text="Display name for this provider", max_length=255)),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("entra_id", "Microsoft Entra ID"),
                            ("okta", "Okta"),
                            ("ad", "Active Directory"),
                            ("servicenow", "ServiceNow IAM"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(blank=True, help_text="Tenant ID (for Entra ID)", max_length=255, null=True),
                ),
                (
                    "connection_config",
                    models.JSONField(default=dict, help_text="Connection configuration (credentials, endpoints)"),
                ),
                ("sync_interval_minutes", models.IntegerField(default=15, help_text="Sync interval in minutes")),
                ("last_sync", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "verbose_name": "Identity Provider",
                "verbose_name_plural": "Identity Providers",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["provider_type", "is_active"], name="iam_securit_provide_52943b_idx"),
                    models.Index(fields=["name"], name="iam_securit_name_16118a_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AnomalyDetection",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique correlation ID for audit trail and tracing",
                        unique=True,
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "anomaly_type",
                    models.CharField(
                        choices=[
                            ("suspicious_login", "Suspicious Login"),
                            ("authentication_attack", "Authentication Attack"),
                            ("unusual_activity", "Unusual Activity"),
                            ("new_device", "New Device"),
                            ("privilege_change", "Privilege Change"),
                            ("dormant_activation", "Dormant Account Activation"),
                            ("service_account_abuse", "Service Account Abuse"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[("low", "Low"), ("medium", "Medium"), ("high", "High"), ("critical", "Critical")],
                        max_length=20,
                    ),
                ),
                ("user_principal", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(help_text="Anomaly description")),
                ("evidence", models.JSONField(default=dict, help_text="Supporting evidence")),
                ("related_events", models.JSONField(default=list, help_text="Related event IDs")),
                ("detection_rule", models.CharField(help_text="Rule that triggered detection", max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("investigating", "Investigating"),
                            ("resolved", "Resolved"),
                            ("false_positive", "False Positive"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_anomalies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anomalies",
                        to="iam_security.identityprovider",
                    ),
                ),
            ],
            options={
                "verbose_name": "Anomaly Detection",
                "verbose_name_plural": "Anomaly Detections",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PermissionChange",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("event_id", models.CharField(help_text="Provider event ID", max_length=255, unique=True)),
                ("actor_principal", models.CharField(db_index=True, max_length=255)),
                ("target_principal", models.CharField(db_index=True, max_length=255)),
                (
                    "change_type",
                    models.CharField(
                        choices=[("add", "Add"), ("remove", "Remove"), ("modify", "Modify")], max_length=50
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("role", "Role"),
                            ("group", "Group"),
                            ("permission", "Permission"),
                            ("app_access", "Application Access"),
                        ],
                        max_length=50,
                    ),
                ),
                ("resource_name", models.CharField(max_length=255)),
                ("old_value", models.JSONField(blank=True, null=True)),
                ("new_value", models.JSONField(blank=True, null=True)),
                ("event_time", models.DateTimeField(db_index=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permission_changes",
                        to="iam_security.identityprovider",
                    ),
                ),
            ],
            options={
                "verbose_name": "Permission Change",
                "verbose_name_plural": "Permission Changes",
                "ordering": ["-event_time"],
            },
        ),
        migrations.CreateModel(
            name="SecurityAlert",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique correlation ID for audit trail and tracing",
                        unique=True,
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "channel",
                    models.CharField(
                        choices=[("email", "Email"), ("teams", "Microsoft Teams"), ("servicenow", "ServiceNow")],
                        max_length=50,
                    ),
                ),
                ("recipients", models.JSONField(default=list, help_text="Alert recipients")),
                ("subject", models.CharField(max_length=500)),
                ("body", models.TextField(help_text="Alert body content")),
                ("sent_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[("sent", "Sent"), ("delivered", "Delivered"), ("failed", "Failed")],
                        default="sent",
                        max_length=20,
                    ),
                ),
                (
                    "anomaly",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="iam_security.anomalydetection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Security Alert",
                "verbose_name_plural": "Security Alerts",
                "ordering": ["-sent_at"],
            },
        ),
        migrations.CreateModel(
            name="SignInEvent",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("event_id", models.CharField(help_text="Provider event ID", max_length=255, unique=True)),
                ("user_principal", models.CharField(db_index=True, max_length=255)),
                ("user_display_name", models.CharField(max_length=255)),
                ("app_display_name", models.CharField(blank=True, max_length=255, null=True)),
                ("client_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("location", models.JSONField(blank=True, help_text="Geographic location data", null=True)),
                ("device_detail", models.JSONField(blank=True, help_text="Device information", null=True)),
                ("status", models.CharField(choices=[("success", "Success"), ("failure", "Failure")], max_length=20)),
                ("failure_reason", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "risk_level",
                    models.CharField(blank=True, help_text="Provider risk assessment", max_length=20, null=True),
                ),
                ("event_time", models.DateTimeField(db_index=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sign_in_events",
                        to="iam_security.identityprovider",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sign-In Event",
                "verbose_name_plural": "Sign-In Events",
                "ordering": ["-event_time"],
            },
        ),
        migrations.AddIndex(
            model_name="anomalydetection",
            index=models.Index(fields=["provider", "severity", "status"], name="iam_securit_provide_99ee9e_idx"),
        ),
        migrations.AddIndex(
            model_name="anomalydetection",
            index=models.Index(fields=["correlation_id"], name="iam_securit_correla_93a13c_idx"),
        ),
        migrations.AddIndex(
            model_name="anomalydetection",
            index=models.Index(fields=["user_principal", "status"], name="iam_securit_user_pr_eba136_idx"),
        ),
        migrations.AddIndex(
            model_name="anomalydetection",
            index=models.Index(fields=["anomaly_type", "severity"], name="iam_securit_anomaly_8f26fa_idx"),
        ),
        migrations.AddIndex(
            model_name="permissionchange",
            index=models.Index(fields=["provider", "event_time"], name="iam_securit_provide_0a4052_idx"),
        ),
        migrations.AddIndex(
            model_name="permissionchange",
            index=models.Index(fields=["target_principal", "event_time"], name="iam_securit_target__22db84_idx"),
        ),
        migrations.AddIndex(
            model_name="permissionchange",
            index=models.Index(fields=["change_type", "resource_type"], name="iam_securit_change__b9335a_idx"),
        ),
        migrations.AddIndex(
            model_name="securityalert",
            index=models.Index(fields=["anomaly", "channel"], name="iam_securit_anomaly_129ab2_idx"),
        ),
        migrations.AddIndex(
            model_name="securityalert",
            index=models.Index(fields=["correlation_id"], name="iam_securit_correla_fa2053_idx"),
        ),
        migrations.AddIndex(
            model_name="securityalert",
            index=models.Index(fields=["status", "sent_at"], name="iam_securit_status_060c56_idx"),
        ),
        migrations.AddIndex(
            model_name="signinevent",
            index=models.Index(fields=["provider", "event_time"], name="iam_securit_provide_7af10c_idx"),
        ),
        migrations.AddIndex(
            model_name="signinevent",
            index=models.Index(fields=["user_principal", "event_time"], name="iam_securit_user_pr_278d3b_idx"),
        ),
        migrations.AddIndex(
            model_name="signinevent",
            index=models.Index(fields=["status", "event_time"], name="iam_securit_status_cb7c02_idx"),
        ),
    ]
