# Generated by Django 5.0.14 on 2026-01-30 06:21

import uuid
from decimal import Decimal

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application_portfolio", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="application",
            options={"ordering": ["name"], "verbose_name": "Application", "verbose_name_plural": "Applications"},
        ),
        migrations.AlterModelOptions(
            name="applicationdependency",
            options={
                "ordering": ["application", "depends_on"],
                "verbose_name": "Application Dependency",
                "verbose_name_plural": "Application Dependencies",
            },
        ),
        migrations.AlterModelOptions(
            name="applicationhealth",
            options={
                "get_latest_by": "recorded_at",
                "ordering": ["-recorded_at"],
                "verbose_name": "Application Health",
                "verbose_name_plural": "Application Health Records",
            },
        ),
        migrations.AlterModelOptions(
            name="applicationversion",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Application Version",
                "verbose_name_plural": "Application Versions",
            },
        ),
        migrations.AlterModelOptions(
            name="deploymentintent",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Deployment Intent",
                "verbose_name_plural": "Deployment Intents",
            },
        ),
        migrations.AlterModelOptions(
            name="deploymentmetric",
            options={
                "ordering": ["-recorded_at"],
                "verbose_name": "Deployment Metric",
                "verbose_name_plural": "Deployment Metrics",
            },
        ),
        migrations.AlterModelOptions(
            name="packageartifact",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Package Artifact",
                "verbose_name_plural": "Package Artifacts",
            },
        ),
        migrations.AlterModelOptions(
            name="publisher",
            options={"ordering": ["name"], "verbose_name": "Publisher", "verbose_name_plural": "Publishers"},
        ),
        migrations.RemoveConstraint(
            model_name="applicationdependency",
            name="unique_app_dependency",
        ),
        migrations.RemoveConstraint(
            model_name="applicationversion",
            name="unique_app_version",
        ),
        migrations.RemoveIndex(
            model_name="application",
            name="app_portfol_publish_c59c88_idx",
        ),
        migrations.RemoveIndex(
            model_name="application",
            name="app_portfol_categor_4fba91_idx",
        ),
        migrations.RemoveIndex(
            model_name="applicationversion",
            name="app_portfol_applica_36eaa7_idx",
        ),
        migrations.RemoveIndex(
            model_name="deploymentintent",
            name="app_portfol_artifac_c2a96a_idx",
        ),
        migrations.RemoveIndex(
            model_name="deploymentintent",
            name="app_portfol_status_8d0d3b_idx",
        ),
        migrations.RemoveIndex(
            model_name="packageartifact",
            name="app_portfol_scan_st_71f3e9_idx",
        ),
        migrations.RenameIndex(
            model_name="applicationhealth",
            new_name="application_applica_0c05cb_idx",
            old_name="app_portfol_applica_2eea45_idx",
        ),
        migrations.RenameIndex(
            model_name="deploymentmetric",
            new_name="application_deploym_5d35fb_idx",
            old_name="app_portfol_deploym_cff7e6_idx",
        ),
        migrations.RenameIndex(
            model_name="packageartifact",
            new_name="application_version_f47b91_idx",
            old_name="app_portfol_version_0d5c74_idx",
        ),
        migrations.AlterField(
            model_name="application",
            name="category",
            field=models.CharField(
                blank=True, help_text="Application category (e.g., Productivity, Security)", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="description",
            field=models.TextField(blank=True, help_text="Application description"),
        ),
        migrations.AlterField(
            model_name="application",
            name="documentation_url",
            field=models.URLField(blank=True, help_text="Documentation URL"),
        ),
        migrations.AlterField(
            model_name="application",
            name="homepage_url",
            field=models.URLField(blank=True, help_text="Application homepage"),
        ),
        migrations.AlterField(
            model_name="application",
            name="icon_url",
            field=models.URLField(blank=True, help_text="Application icon URL"),
        ),
        migrations.AlterField(
            model_name="application",
            name="identifier",
            field=models.CharField(
                help_text="Unique application identifier (e.g., com.vendor.appname)", max_length=255, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="application",
            name="is_internal",
            field=models.BooleanField(default=False, help_text="Whether this is an internal/LOB application"),
        ),
        migrations.AlterField(
            model_name="application",
            name="is_privileged",
            field=models.BooleanField(default=False, help_text="Whether app requires elevated privileges"),
        ),
        migrations.AlterField(
            model_name="application",
            name="name",
            field=models.CharField(help_text="Application display name", max_length=255),
        ),
        migrations.AlterField(
            model_name="application",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Application owner",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_applications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="publisher",
            field=models.ForeignKey(
                help_text="Software publisher",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="applications",
                to="application_portfolio.publisher",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="requires_cab_approval",
            field=models.BooleanField(default=False, help_text="Whether CAB approval is required for deployments"),
        ),
        migrations.AlterField(
            model_name="application",
            name="risk_score",
            field=models.IntegerField(default=0, help_text="Calculated risk score 0-100"),
        ),
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending_review", "Pending Review"),
                    ("approved", "Approved"),
                    ("published", "Published"),
                    ("deprecated", "Deprecated"),
                    ("retired", "Retired"),
                ],
                default="draft",
                help_text="Application lifecycle status",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="supported_platforms",
            field=models.JSONField(default=list, help_text="List of supported platform types"),
        ),
        migrations.AlterField(
            model_name="application",
            name="tags",
            field=models.JSONField(blank=True, default=list, help_text="Application tags for filtering"),
        ),
        migrations.AlterField(
            model_name="application",
            name="team",
            field=models.CharField(blank=True, help_text="Owning team/department", max_length=100),
        ),
        migrations.AlterField(
            model_name="applicationdependency",
            name="application",
            field=models.ForeignKey(
                help_text="Application that has the dependency",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dependencies",
                to="application_portfolio.application",
            ),
        ),
        migrations.AlterField(
            model_name="applicationdependency",
            name="dependency_type",
            field=models.CharField(
                default="runtime", help_text="Dependency type (runtime, build, optional)", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="applicationdependency",
            name="depends_on",
            field=models.ForeignKey(
                help_text="Required application",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dependents",
                to="application_portfolio.application",
            ),
        ),
        migrations.AlterField(
            model_name="applicationdependency",
            name="is_required",
            field=models.BooleanField(default=True, help_text="Whether dependency is required"),
        ),
        migrations.AlterField(
            model_name="applicationdependency",
            name="max_version",
            field=models.CharField(blank=True, help_text="Maximum compatible version", max_length=100),
        ),
        migrations.AlterField(
            model_name="applicationdependency",
            name="min_version",
            field=models.CharField(blank=True, help_text="Minimum required version", max_length=100),
        ),
        migrations.AlterField(
            model_name="applicationhealth",
            name="application",
            field=models.ForeignKey(
                help_text="Application",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="health_snapshots",
                to="application_portfolio.application",
            ),
        ),
        migrations.AlterField(
            model_name="applicationhealth",
            name="compliance_score",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), help_text="Compliance score percentage", max_digits=5
            ),
        ),
        migrations.AlterField(
            model_name="applicationhealth",
            name="compliance_status",
            field=models.CharField(
                choices=[
                    ("compliant", "Compliant"),
                    ("non_compliant", "Non-Compliant"),
                    ("pending", "Pending Assessment"),
                    ("exempt", "Exempt"),
                ],
                default="pending",
                help_text="Compliance status",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="applicationhealth",
            name="health_message",
            field=models.CharField(blank=True, help_text="Health status message", max_length=255),
        ),
        migrations.AlterField(
            model_name="applicationhealth",
            name="health_status",
            field=models.CharField(
                choices=[
                    ("healthy", "Healthy"),
                    ("degraded", "Degraded"),
                    ("critical", "Critical"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                help_text="Overall health status",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="applicationhealth",
            name="recorded_at",
            field=models.DateTimeField(default=django.utils.timezone.now, help_text="When health was recorded"),
        ),
        migrations.AlterField(
            model_name="applicationhealth",
            name="version_distribution",
            field=models.JSONField(blank=True, default=dict, help_text="Installation count per version"),
        ),
        migrations.AlterField(
            model_name="applicationversion",
            name="application",
            field=models.ForeignKey(
                help_text="Parent application",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="application_portfolio.application",
            ),
        ),
        migrations.AlterField(
            model_name="applicationversion",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who approved this version",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_app_versions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="applicationversion",
            name="dependencies",
            field=models.JSONField(blank=True, default=list, help_text="Application dependencies"),
        ),
        migrations.AlterField(
            model_name="applicationversion",
            name="deprecation_date",
            field=models.DateField(blank=True, help_text="Date when version will be deprecated", null=True),
        ),
        migrations.AlterField(
            model_name="applicationversion",
            name="end_of_life_date",
            field=models.DateField(blank=True, help_text="Date when version reaches end of life", null=True),
        ),
        migrations.AlterField(
            model_name="applicationversion",
            name="is_latest",
            field=models.BooleanField(default=False, help_text="Whether this is the latest approved version"),
        ),
        migrations.AlterField(
            model_name="applicationversion",
            name="is_security_update",
            field=models.BooleanField(default=False, help_text="Whether this version includes security fixes"),
        ),
        migrations.AlterField(
            model_name="applicationversion",
            name="min_os_versions",
            field=models.JSONField(blank=True, default=dict, help_text="Minimum OS versions per platform"),
        ),
        migrations.AlterField(
            model_name="applicationversion",
            name="release_date",
            field=models.DateField(blank=True, help_text="Official release date", null=True),
        ),
        migrations.AlterField(
            model_name="applicationversion",
            name="release_notes",
            field=models.TextField(blank=True, help_text="Version release notes"),
        ),
        migrations.AlterField(
            model_name="applicationversion",
            name="system_requirements",
            field=models.JSONField(blank=True, default=dict, help_text="System requirements (RAM, disk, etc.)"),
        ),
        migrations.AlterField(
            model_name="applicationversion",
            name="version",
            field=models.CharField(help_text="Version string (semver preferred)", max_length=100),
        ),
        migrations.AlterField(
            model_name="applicationversion",
            name="version_code",
            field=models.IntegerField(blank=True, help_text="Numeric version code for comparison", null=True),
        ),
        migrations.AlterField(
            model_name="deploymentintent",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="CAB approver",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_deployments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="deploymentintent",
            name="artifact",
            field=models.ForeignKey(
                help_text="Package artifact to deploy",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deployment_intents",
                to="application_portfolio.packageartifact",
            ),
        ),
        migrations.AlterField(
            model_name="deploymentintent",
            name="cab_request_id",
            field=models.CharField(blank=True, help_text="CAB request identifier", max_length=100),
        ),
        migrations.AlterField(
            model_name="deploymentintent",
            name="correlation_id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                help_text="Unique correlation ID for audit trail and tracing",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="deploymentintent",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created the deployment",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_deployments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="deploymentintent",
            name="deadline",
            field=models.DateTimeField(
                blank=True, help_text="Deployment deadline (after which deployment is required)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="deploymentintent",
            name="evidence_pack_hash",
            field=models.CharField(blank=True, help_text="SHA-256 hash of evidence pack", max_length=64),
        ),
        migrations.AlterField(
            model_name="deploymentintent",
            name="evidence_pack_ref",
            field=models.CharField(
                blank=True, help_text="Reference to evidence pack in artifact store", max_length=500
            ),
        ),
        migrations.AlterField(
            model_name="deploymentintent",
            name="requires_cab_approval",
            field=models.BooleanField(default=False, help_text="Whether CAB approval is required"),
        ),
        migrations.AlterField(
            model_name="deploymentintent",
            name="risk_model_version",
            field=models.CharField(default="v1.0", help_text="Risk model version used", max_length=20),
        ),
        migrations.AlterField(
            model_name="deploymentintent",
            name="risk_score",
            field=models.IntegerField(default=0, help_text="Calculated deployment risk score 0-100"),
        ),
        migrations.AlterField(
            model_name="deploymentintent",
            name="rollback_plan",
            field=models.JSONField(blank=True, default=dict, help_text="Rollback plan details"),
        ),
        migrations.AlterField(
            model_name="deploymentintent",
            name="rollout_config",
            field=models.JSONField(
                blank=True, default=dict, help_text="Rollout configuration (batch size, throttling, etc.)"
            ),
        ),
        migrations.AlterField(
            model_name="deploymentintent",
            name="scheduled_end",
            field=models.DateTimeField(
                blank=True, help_text="Scheduled deployment end time (for maintenance windows)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="deploymentintent",
            name="scheduled_start",
            field=models.DateTimeField(blank=True, help_text="Scheduled deployment start time", null=True),
        ),
        migrations.AlterField(
            model_name="deploymentintent",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending_approval", "Pending CAB Approval"),
                    ("approved", "Approved"),
                    ("scheduled", "Scheduled"),
                    ("in_progress", "In Progress"),
                    ("paused", "Paused"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("rolled_back", "Rolled Back"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                help_text="Deployment status",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="deploymentintent",
            name="target_device_count",
            field=models.IntegerField(default=0, help_text="Estimated target device count"),
        ),
        migrations.AlterField(
            model_name="deploymentintent",
            name="target_ring",
            field=models.CharField(
                choices=[
                    ("ring_0", "Ring 0 - Lab/Automation"),
                    ("ring_1", "Ring 1 - Canary"),
                    ("ring_2", "Ring 2 - Pilot"),
                    ("ring_3", "Ring 3 - Department"),
                    ("ring_4", "Ring 4 - Global"),
                ],
                help_text="Target deployment ring",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="deploymentintent",
            name="target_scope",
            field=models.JSONField(default=dict, help_text="Target scope definition (groups, sites, exclusions)"),
        ),
        migrations.AlterField(
            model_name="deploymentmetric",
            name="avg_install_time_seconds",
            field=models.IntegerField(blank=True, help_text="Average installation time", null=True),
        ),
        migrations.AlterField(
            model_name="deploymentmetric",
            name="deployment",
            field=models.ForeignKey(
                help_text="Parent deployment",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="metrics",
                to="application_portfolio.deploymentintent",
            ),
        ),
        migrations.AlterField(
            model_name="deploymentmetric",
            name="error_summary",
            field=models.JSONField(blank=True, default=dict, help_text="Error code summary"),
        ),
        migrations.AlterField(
            model_name="deploymentmetric",
            name="recorded_at",
            field=models.DateTimeField(default=django.utils.timezone.now, help_text="When metrics were recorded"),
        ),
        migrations.AlterField(
            model_name="deploymentmetric",
            name="success_rate",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), help_text="Success rate percentage", max_digits=5
            ),
        ),
        migrations.AlterField(
            model_name="deploymentmetric",
            name="time_to_compliance_avg_seconds",
            field=models.IntegerField(blank=True, help_text="Average time to compliance", null=True),
        ),
        migrations.AlterField(
            model_name="packageartifact",
            name="architecture",
            field=models.CharField(default="x64", help_text="CPU architecture (x64, arm64, universal)", max_length=20),
        ),
        migrations.AlterField(
            model_name="packageartifact",
            name="correlation_id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                help_text="Unique correlation ID for audit trail and tracing",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="packageartifact",
            name="detection_rules",
            field=models.JSONField(blank=True, default=dict, help_text="Detection rules (file, registry, script)"),
        ),
        migrations.AlterField(
            model_name="packageartifact",
            name="file_hash_sha256",
            field=models.CharField(help_text="SHA-256 hash of package file", max_length=64),
        ),
        migrations.AlterField(
            model_name="packageartifact",
            name="file_name",
            field=models.CharField(help_text="Package file name", max_length=255),
        ),
        migrations.AlterField(
            model_name="packageartifact",
            name="file_size",
            field=models.BigIntegerField(help_text="File size in bytes"),
        ),
        migrations.AlterField(
            model_name="packageartifact",
            name="install_command",
            field=models.TextField(blank=True, help_text="Silent install command"),
        ),
        migrations.AlterField(
            model_name="packageartifact",
            name="is_signed",
            field=models.BooleanField(default=False, help_text="Whether package is signed"),
        ),
        migrations.AlterField(
            model_name="packageartifact",
            name="package_type",
            field=models.CharField(
                choices=[
                    ("intunewin", "Intune Win32 (.intunewin)"),
                    ("msix", "MSIX Package"),
                    ("msi", "Windows Installer (MSI)"),
                    ("exe", "Executable (EXE)"),
                    ("pkg", "macOS Package (PKG)"),
                    ("dmg", "Disk Image (DMG)"),
                    ("app", "Application Bundle (APP)"),
                    ("deb", "Debian Package (DEB)"),
                    ("rpm", "RPM Package"),
                    ("snap", "Snap Package"),
                    ("flatpak", "Flatpak"),
                    ("appimage", "AppImage"),
                    ("ipa", "iOS App (IPA)"),
                    ("apk", "Android Package (APK)"),
                    ("aab", "Android App Bundle (AAB)"),
                    ("other", "Other"),
                ],
                help_text="Package format",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="packageartifact",
            name="platform",
            field=models.CharField(
                choices=[
                    ("windows", "Windows"),
                    ("macos", "macOS"),
                    ("linux", "Linux"),
                    ("ios", "iOS"),
                    ("ipados", "iPadOS"),
                    ("android", "Android"),
                ],
                help_text="Target platform",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="packageartifact",
            name="requirement_rules",
            field=models.JSONField(blank=True, default=dict, help_text="Requirement/applicability rules"),
        ),
        migrations.AlterField(
            model_name="packageartifact",
            name="sbom_format",
            field=models.CharField(blank=True, help_text="SBOM format (spdx, cyclonedx)", max_length=20),
        ),
        migrations.AlterField(
            model_name="packageartifact",
            name="sbom_ref",
            field=models.CharField(blank=True, help_text="Reference to SBOM in artifact store", max_length=500),
        ),
        migrations.AlterField(
            model_name="packageartifact",
            name="scan_report_ref",
            field=models.CharField(blank=True, help_text="Reference to scan report", max_length=500),
        ),
        migrations.AlterField(
            model_name="packageartifact",
            name="scan_status",
            field=models.CharField(blank=True, help_text="Vulnerability scan status", max_length=20),
        ),
        migrations.AlterField(
            model_name="packageartifact",
            name="signature_timestamp",
            field=models.DateTimeField(blank=True, help_text="Signature timestamp", null=True),
        ),
        migrations.AlterField(
            model_name="packageartifact",
            name="signature_type",
            field=models.CharField(
                blank=True, help_text="Signature type (authenticode, notarization, gpg)", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="packageartifact",
            name="signer_identity",
            field=models.CharField(blank=True, help_text="Signing certificate subject/identity", max_length=255),
        ),
        migrations.AlterField(
            model_name="packageartifact",
            name="status",
            field=models.CharField(
                choices=[
                    ("uploading", "Uploading"),
                    ("validating", "Validating"),
                    ("scanning", "Scanning"),
                    ("scan_failed", "Scan Failed"),
                    ("ready", "Ready"),
                    ("published", "Published"),
                    ("superseded", "Superseded"),
                    ("revoked", "Revoked"),
                ],
                default="uploading",
                help_text="Artifact lifecycle status",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="packageartifact",
            name="storage_ref",
            field=models.CharField(help_text="Reference to artifact in object store", max_length=500),
        ),
        migrations.AlterField(
            model_name="packageartifact",
            name="uninstall_command",
            field=models.TextField(blank=True, help_text="Silent uninstall command"),
        ),
        migrations.AlterField(
            model_name="packageartifact",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who uploaded the artifact",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_artifacts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="packageartifact",
            name="version",
            field=models.ForeignKey(
                help_text="Application version",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="artifacts",
                to="application_portfolio.applicationversion",
            ),
        ),
        migrations.AlterField(
            model_name="publisher",
            name="identifier",
            field=models.CharField(help_text="Unique identifier (e.g., reverse domain)", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="publisher",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="publisher",
            name="is_verified",
            field=models.BooleanField(default=False, help_text="Whether publisher identity is verified"),
        ),
        migrations.AlterField(
            model_name="publisher",
            name="name",
            field=models.CharField(help_text="Publisher name", max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="publisher",
            name="support_url",
            field=models.URLField(blank=True, help_text="Support portal URL"),
        ),
        migrations.AlterField(
            model_name="publisher",
            name="trust_score",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.50"), help_text="Trust score 0.00-1.00", max_digits=3
            ),
        ),
        migrations.AlterField(
            model_name="publisher",
            name="website",
            field=models.URLField(blank=True, help_text="Publisher website"),
        ),
        migrations.AlterUniqueTogether(
            name="applicationdependency",
            unique_together={("application", "depends_on")},
        ),
        migrations.AlterUniqueTogether(
            name="applicationversion",
            unique_together={("application", "version")},
        ),
        migrations.AlterUniqueTogether(
            name="packageartifact",
            unique_together={("version", "platform", "architecture", "package_type")},
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(fields=["identifier"], name="application_identif_f249cb_idx"),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(fields=["publisher"], name="application_publish_f5f98f_idx"),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(fields=["status"], name="application_status_4c39c4_idx"),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(fields=["category"], name="application_categor_898e6a_idx"),
        ),
        migrations.AddIndex(
            model_name="applicationhealth",
            index=models.Index(fields=["health_status"], name="application_health__77415d_idx"),
        ),
        migrations.AddIndex(
            model_name="applicationversion",
            index=models.Index(fields=["application", "version"], name="application_applica_cd1d19_idx"),
        ),
        migrations.AddIndex(
            model_name="applicationversion",
            index=models.Index(fields=["is_latest"], name="application_is_late_9db8d4_idx"),
        ),
        migrations.AddIndex(
            model_name="deploymentintent",
            index=models.Index(fields=["artifact"], name="application_artifac_27a4cf_idx"),
        ),
        migrations.AddIndex(
            model_name="deploymentintent",
            index=models.Index(fields=["status"], name="application_status_e48339_idx"),
        ),
        migrations.AddIndex(
            model_name="deploymentintent",
            index=models.Index(fields=["target_ring"], name="application_target__f381ce_idx"),
        ),
        migrations.AddIndex(
            model_name="deploymentintent",
            index=models.Index(fields=["scheduled_start"], name="application_schedul_8ed607_idx"),
        ),
        migrations.AddIndex(
            model_name="packageartifact",
            index=models.Index(fields=["status"], name="application_status_d8c30d_idx"),
        ),
        migrations.AddIndex(
            model_name="packageartifact",
            index=models.Index(fields=["file_hash_sha256"], name="application_file_ha_8b0eea_idx"),
        ),
        migrations.AlterModelTable(
            name="application",
            table=None,
        ),
        migrations.AlterModelTable(
            name="applicationdependency",
            table=None,
        ),
        migrations.AlterModelTable(
            name="applicationhealth",
            table=None,
        ),
        migrations.AlterModelTable(
            name="applicationversion",
            table=None,
        ),
        migrations.AlterModelTable(
            name="deploymentintent",
            table=None,
        ),
        migrations.AlterModelTable(
            name="deploymentmetric",
            table=None,
        ),
        migrations.AlterModelTable(
            name="packageartifact",
            table=None,
        ),
        migrations.AlterModelTable(
            name="publisher",
            table=None,
        ),
    ]
