# Generated by Django 5.0.14 on 2026-01-04 19:15

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EvidencePack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique correlation ID for audit trail and tracing",
                        unique=True,
                    ),
                ),
                ("app_name", models.CharField(max_length=255)),
                ("version", models.CharField(max_length=50)),
                (
                    "artifact_hash",
                    models.CharField(
                        help_text="SHA-256 hash of artifact", max_length=64
                    ),
                ),
                (
                    "artifact_path",
                    models.CharField(help_text="MinIO object path", max_length=500),
                ),
                (
                    "sbom_data",
                    models.JSONField(
                        help_text="Software Bill of Materials (SPDX/CycloneDX)"
                    ),
                ),
                (
                    "vulnerability_scan_results",
                    models.JSONField(help_text="Vulnerability scan results"),
                ),
                (
                    "rollback_plan",
                    models.TextField(help_text="Rollback plan documentation"),
                ),
                (
                    "is_validated",
                    models.BooleanField(
                        default=False, help_text="Whether evidence pack is validated"
                    ),
                ),
            ],
            options={
                "verbose_name": "Evidence Pack",
                "verbose_name_plural": "Evidence Packs",
                "indexes": [
                    models.Index(
                        fields=["app_name", "version"],
                        name="evidence_st_app_nam_464e52_idx",
                    ),
                    models.Index(
                        fields=["artifact_hash"], name="evidence_st_artifac_26082e_idx"
                    ),
                ],
            },
        ),
    ]
