# Generated by Django 5.0.14 on 2026-01-22 09:05

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evidence_store", "0002_add_is_demo"),
    ]

    operations = [
        migrations.CreateModel(
            name="EvidencePackage",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                (
                    "deployment_intent_id",
                    models.CharField(help_text="Correlation ID linking to deployment intent", max_length=255),
                ),
                (
                    "correlation_id",
                    models.CharField(help_text="Unique identifier for audit trail", max_length=255, unique=True),
                ),
                (
                    "evidence_data",
                    models.JSONField(default=dict, help_text="Complete evidence pack (artifacts, tests, scans, etc.)"),
                ),
                (
                    "risk_score",
                    models.DecimalField(
                        decimal_places=2, default=0.0, help_text="Risk score 0-100 (higher = riskier)", max_digits=5
                    ),
                ),
                (
                    "risk_factors",
                    models.JSONField(default=dict, help_text="Breakdown of all contributing risk factors"),
                ),
                (
                    "risk_model_version",
                    models.CharField(default="1.0", help_text="Version of risk scoring model used", max_length=50),
                ),
                ("is_complete", models.BooleanField(default=False, help_text="All required fields populated")),
                ("completeness_check", models.JSONField(default=dict, help_text="Field-by-field completeness status")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.CharField(
                        default="system", help_text="User or system that created this package", max_length=255
                    ),
                ),
                (
                    "content_hash",
                    models.CharField(
                        help_text="SHA-256 hash of evidence_data for immutability verification", max_length=64
                    ),
                ),
            ],
            options={
                "verbose_name": "Evidence Package",
                "verbose_name_plural": "Evidence Packages",
                "db_table": "evidence_store_evidencepackage",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["deployment_intent_id", "-created_at"], name="evidence_st_deploym_5eb0f2_idx"),
                    models.Index(fields=["risk_score"], name="evidence_st_risk_sc_3e6815_idx"),
                    models.Index(fields=["is_complete"], name="evidence_st_is_comp_9585ae_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="RiskFactor",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                (
                    "model_version",
                    models.CharField(
                        default="1.0", help_text="Risk model version this factor belongs to", max_length=50
                    ),
                ),
                (
                    "factor_type",
                    models.CharField(
                        choices=[
                            ("coverage", "Test Coverage"),
                            ("security", "Security Issues"),
                            ("testing", "Manual Testing"),
                            ("rollback", "Rollback Validation"),
                            ("scope", "Change Scope"),
                            ("complexity", "Code Complexity"),
                            ("impact", "User Impact"),
                        ],
                        help_text="Category of risk factor",
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(help_text="Human-readable name", max_length=255)),
                ("description", models.TextField(help_text="What this factor measures")),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=4, help_text="Percentage weight in overall score (0-1)", max_digits=5
                    ),
                ),
                ("rubric", models.JSONField(default=dict, help_text="Scoring rubric (e.g., {'>90%': 0, '<90%': 20})")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Risk Factor",
                "verbose_name_plural": "Risk Factors",
                "db_table": "evidence_store_riskfactor",
                "ordering": ["model_version", "factor_type"],
                "unique_together": {("model_version", "factor_type")},
            },
        ),
        migrations.CreateModel(
            name="RiskScoreBreakdown",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("correlation_id", models.CharField(help_text="Link to deployment intent", max_length=255)),
                (
                    "factors_evaluated",
                    models.JSONField(default=dict, help_text="All factors with their scores and weights"),
                ),
                (
                    "formula",
                    models.TextField(
                        default="Σ(weight_i * normalized_factor_i), clamped [0-100]",
                        help_text="Risk scoring formula used",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(default="system", max_length=255)),
                (
                    "evidence_package",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_breakdown",
                        to="evidence_store.evidencepackage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Risk Score Breakdown",
                "verbose_name_plural": "Risk Score Breakdowns",
                "db_table": "evidence_store_riskscorebreakdown",
            },
        ),
    ]
