# Generated by Django 5.0.14 on 2026-01-22 09:05

from django.db import migrations
import uuid


def seed_risk_factors_v1(apps, schema_editor):
    """Seed initial risk factors for risk model v1.0."""
    RiskFactor = apps.get_model('evidence_store', 'RiskFactor')
    
    factors = [
        {
            'id': uuid.uuid4(),
            'model_version': '1.0',
            'factor_type': 'coverage',
            'name': 'Test Coverage',
            'description': 'Percentage of code covered by automated tests',
            'weight': 0.25,
            'rubric': {
                '>90': 0,      # Excellent: 0 risk points
                '80-90': 10,   # Good: 10 risk points
                '<80': 30,     # Poor: 30 risk points
            }
        },
        {
            'id': uuid.uuid4(),
            'model_version': '1.0',
            'factor_type': 'security',
            'name': 'Security Issues',
            'description': 'Critical and high-severity vulnerabilities from security scans',
            'weight': 0.25,
            'rubric': {
                '>2': 50,      # Many issues: 50 risk points
                '1-2': 20,     # Some issues: 20 risk points
                '0': 0,        # No issues: 0 risk points
            }
        },
        {
            'id': uuid.uuid4(),
            'model_version': '1.0',
            'factor_type': 'testing',
            'name': 'Manual Testing',
            'description': 'Manual testing completion status',
            'weight': 0.15,
            'rubric': {
                'completed': 0,      # Completed: 0 risk points
                'in_progress': 30,   # In progress: 30 risk points
                'not_started': 50,   # Not started: 50 risk points
            }
        },
        {
            'id': uuid.uuid4(),
            'model_version': '1.0',
            'factor_type': 'rollback',
            'name': 'Rollback Validation',
            'description': 'Rollback strategy validation and testing',
            'weight': 0.15,
            'rubric': {
                'validated': 0,   # Validated: 0 risk points
                'missing': 50,    # Missing: 50 risk points
            }
        },
        {
            'id': uuid.uuid4(),
            'model_version': '1.0',
            'factor_type': 'scope',
            'name': 'Change Scope',
            'description': 'Number of affected components or systems',
            'weight': 0.20,
            'rubric': {
                '>10': 40,    # Large scope: 40 risk points
                '5-10': 20,   # Medium scope: 20 risk points
                '<5': 0,      # Small scope: 0 risk points
            }
        },
    ]
    
    for factor_data in factors:
        RiskFactor.objects.create(**factor_data)


def reverse_seed_risk_factors_v1(apps, schema_editor):
    """Reverse: delete seed risk factors."""
    RiskFactor = apps.get_model('evidence_store', 'RiskFactor')
    RiskFactor.objects.filter(model_version='1.0').delete()


class Migration(migrations.Migration):

    dependencies = [
        ("evidence_store", "0003_add_p5_models"),
    ]

    operations = [
        migrations.RunPython(seed_risk_factors_v1, reverse_seed_risk_factors_v1),
    ]
