# Generated by Django 5.1.15 on 2026-01-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence_store', '0006_seed_p5_5_data'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='deploymentincident',
            new_name='evidence_st_inciden_c767a0_idx',
            old_name='evidence_st_inciden_idx',
        ),
        migrations.RenameIndex(
            model_name='deploymentincident',
            new_name='evidence_st_was_aut_99045e_idx',
            old_name='evidence_st_was_aut_idx',
        ),
        migrations.RenameIndex(
            model_name='deploymentincident',
            new_name='evidence_st_blast_r_6d9f67_idx',
            old_name='evidence_st_blast_r_idx',
        ),
        migrations.RenameIndex(
            model_name='deploymentincident',
            new_name='evidence_st_risk_sc_f6f3f6_idx',
            old_name='evidence_st_risk_sc_idx',
        ),
        migrations.RenameIndex(
            model_name='riskmodelversion',
            new_name='evidence_st_is_acti_6ba1f3_idx',
            old_name='evidence_st_is_acti_idx',
        ),
        migrations.RenameIndex(
            model_name='riskmodelversion',
            new_name='evidence_st_version_4af778_idx',
            old_name='evidence_st_version_idx',
        ),
        migrations.RenameIndex(
            model_name='trustmaturityprogress',
            new_name='evidence_st_evaluat_df4e8f_idx',
            old_name='evidence_st_evaluat_idx',
        ),
        migrations.RenameIndex(
            model_name='trustmaturityprogress',
            new_name='evidence_st_current_22aeda_idx',
            old_name='evidence_st_current_idx',
        ),
        migrations.AlterField(
            model_name='blastradiusclass',
            name='example_applications',
            field=models.JSONField(default=list, help_text="Example applications in this class: ['Windows Security Update', 'Antivirus Engine']"),
        ),
        migrations.AlterField(
            model_name='riskmodelversion',
            name='auto_approve_thresholds',
            field=models.JSONField(help_text="Thresholds per blast radius class: {'CRITICAL_INFRASTRUCTURE': 0, 'BUSINESS_CRITICAL': 0, ...}"),
        ),
        migrations.AlterField(
            model_name='riskmodelversion',
            name='risk_factor_weights',
            field=models.JSONField(help_text="Risk factor weights (must sum to 1.0): {'test_coverage': 0.20, 'security_issues': 0.15, ...}"),
        ),
    ]
