# Generated by Django 5.0.14 on 2026-01-30 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("evidence_store", "0007_rename_evidence_st_inciden_idx_evidence_st_inciden_c767a0_idx_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BlastRadiusClass",
        ),
        migrations.DeleteModel(
            name="DeploymentIncident",
        ),
        migrations.DeleteModel(
            name="RiskModelVersion",
        ),
        migrations.DeleteModel(
            name="TrustMaturityLevel",
        ),
        migrations.DeleteModel(
            name="TrustMaturityProgress",
        ),
    ]
