# Generated by Django 5.1.15 on 2026-01-30 18:56

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evidence_store", "0008_delete_blastradiusclass_delete_deploymentincident_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlastRadiusClass",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("CRITICAL_INFRASTRUCTURE", "Critical Infrastructure"),
                            ("BUSINESS_CRITICAL", "Business Critical"),
                            ("PRODUCTIVITY_TOOLS", "Productivity Tools"),
                            ("NON_CRITICAL", "Non-Critical"),
                        ],
                        help_text="Blast radius classification level",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(help_text="What qualifies for this classification")),
                (
                    "user_impact_max",
                    models.IntegerField(
                        help_text="Maximum users that can be impacted (enterprise-wide, department, team)"
                    ),
                ),
                (
                    "business_criticality",
                    models.CharField(
                        choices=[("HIGH", "High"), ("MEDIUM", "Medium"), ("LOW", "Low")],
                        help_text="Business criticality level",
                        max_length=20,
                    ),
                ),
                (
                    "cab_quorum_required",
                    models.IntegerField(default=1, help_text="Minimum CAB members required for approval"),
                ),
                (
                    "auto_approve_allowed",
                    models.BooleanField(default=False, help_text="Whether auto-approve is ever allowed for this class"),
                ),
                (
                    "example_applications",
                    models.JSONField(
                        default=list,
                        help_text="Example applications in this class: ['Windows Security Update', 'Antivirus Engine']",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Blast Radius Class",
                "verbose_name_plural": "Blast Radius Classes",
                "db_table": "evidence_store_blastradiusclass",
            },
        ),
        migrations.CreateModel(
            name="TrustMaturityLevel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("LEVEL_0_BASELINE", "Level 0: Baseline (100% CAB Review)"),
                            ("LEVEL_1_CAUTIOUS", "Level 1: Cautious (Limited Auto-Approve)"),
                            ("LEVEL_2_MODERATE", "Level 2: Moderate (Balanced)"),
                            ("LEVEL_3_MATURE", "Level 3: Mature (Evidence-Based)"),
                            ("LEVEL_4_OPTIMIZED", "Level 4: Optimized (Maximum Automation)"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(help_text="What this maturity level represents")),
                ("weeks_required", models.IntegerField(help_text="Minimum weeks at previous level")),
                (
                    "max_incident_rate",
                    models.DecimalField(decimal_places=4, help_text="Maximum incident rate (0.01 = 1%)", max_digits=5),
                ),
                ("max_p1_incidents", models.IntegerField(help_text="Maximum P1 incidents allowed")),
                ("max_p2_incidents", models.IntegerField(help_text="Maximum P2 incidents allowed")),
                (
                    "risk_model_version",
                    models.CharField(
                        help_text="Risk model version to activate when reaching this level", max_length=10
                    ),
                ),
                (
                    "auto_approve_thresholds",
                    models.JSONField(help_text="Auto-approve thresholds per blast radius class"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Trust Maturity Level",
                "verbose_name_plural": "Trust Maturity Levels",
                "db_table": "evidence_store_trustmaturitylevel",
                "ordering": ["level"],
            },
        ),
        migrations.CreateModel(
            name="DeploymentIncident",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                (
                    "deployment_intent_id",
                    models.CharField(db_index=True, help_text="Deployment intent correlation ID", max_length=255),
                ),
                (
                    "evidence_package_id",
                    models.CharField(db_index=True, help_text="Evidence package ID", max_length=255),
                ),
                (
                    "cab_approval_id",
                    models.CharField(
                        blank=True, help_text="CAB approval request ID (if CAB-reviewed)", max_length=255, null=True
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("P1", "P1 - Critical (Service Down)"),
                            ("P2", "P2 - High (Major Degradation)"),
                            ("P3", "P3 - Medium (Minor Impact)"),
                            ("P4", "P4 - Low (Cosmetic)"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("incident_date", models.DateTimeField(db_index=True, help_text="When incident occurred")),
                (
                    "detection_method",
                    models.CharField(
                        choices=[
                            ("MONITORING_ALERT", "Monitoring Alert"),
                            ("USER_REPORT", "User Report"),
                            ("CAB_REVIEW", "CAB Review"),
                            ("SECURITY_SCAN", "Security Scan"),
                            ("AUTOMATED_TEST", "Automated Test"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(help_text="Incident title", max_length=255)),
                ("description", models.TextField(help_text="Detailed incident description")),
                ("root_cause", models.TextField(blank=True, help_text="Root cause analysis")),
                (
                    "was_auto_approved",
                    models.BooleanField(db_index=True, help_text="Was deployment auto-approved (vs CAB-reviewed)"),
                ),
                (
                    "risk_score_at_approval",
                    models.DecimalField(
                        decimal_places=2, help_text="Risk score when deployment was approved", max_digits=5
                    ),
                ),
                (
                    "risk_model_version",
                    models.CharField(help_text="Risk model version used for approval", max_length=10),
                ),
                (
                    "blast_radius_class",
                    models.CharField(help_text="Blast radius classification of deployment", max_length=50),
                ),
                ("affected_user_count", models.IntegerField(default=0, help_text="Number of users affected")),
                ("downtime_minutes", models.IntegerField(default=0, help_text="Total downtime in minutes")),
                (
                    "business_impact_usd",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Estimated business impact in USD",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, help_text="When incident was resolved", null=True)),
                (
                    "resolution_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ROLLBACK", "Rollback to Previous Version"),
                            ("HOTFIX", "Hotfix Deployment"),
                            ("MANUAL_REMEDIATION", "Manual Remediation"),
                            ("WORKAROUND", "Temporary Workaround"),
                        ],
                        max_length=50,
                    ),
                ),
                ("resolution_notes", models.TextField(blank=True)),
                (
                    "time_to_resolution_minutes",
                    models.IntegerField(blank=True, help_text="Time from detection to resolution", null=True),
                ),
                (
                    "was_preventable",
                    models.BooleanField(help_text="Could this have been prevented by better controls?", null=True),
                ),
                (
                    "preventability_notes",
                    models.TextField(
                        blank=True,
                        help_text="Analysis of whether CAB review or additional controls would have caught this",
                    ),
                ),
                (
                    "control_improvements",
                    models.JSONField(
                        default=dict,
                        help_text="Recommended improvements: risk factor adjustments, new controls, threshold changes",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(default="system", max_length=255)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Deployment Incident",
                "verbose_name_plural": "Deployment Incidents",
                "db_table": "evidence_store_deploymentincident",
                "ordering": ["-incident_date"],
                "indexes": [
                    models.Index(fields=["incident_date", "severity"], name="evidence_st_inciden_c767a0_idx"),
                    models.Index(fields=["was_auto_approved", "severity"], name="evidence_st_was_aut_99045e_idx"),
                    models.Index(fields=["blast_radius_class", "incident_date"], name="evidence_st_blast_r_6d9f67_idx"),
                    models.Index(fields=["risk_score_at_approval"], name="evidence_st_risk_sc_f6f3f6_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="RiskModelVersion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("version", models.CharField(help_text="e.g., '1.0', '1.1', '2.0'", max_length=10, unique=True)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("GREENFIELD_CONSERVATIVE", "Greenfield Conservative (100% CAB Review)"),
                            ("CAUTIOUS", "Cautious (Limited Auto-Approve)"),
                            ("MODERATE", "Moderate (Balanced)"),
                            ("MATURE", "Mature (Evidence-Based Automation)"),
                            ("OPTIMIZED", "Optimized (Maximum Automation)"),
                        ],
                        help_text="Operating mode",
                        max_length=50,
                    ),
                ),
                ("effective_date", models.DateTimeField(help_text="When this version becomes active")),
                ("review_date", models.DateTimeField(help_text="When to review for calibration")),
                (
                    "is_active",
                    models.BooleanField(db_index=True, default=False, help_text="Only one version can be active"),
                ),
                (
                    "approved_by_cab",
                    models.BooleanField(default=False, help_text="CAB approval required for activation"),
                ),
                ("cab_approval_date", models.DateTimeField(blank=True, null=True)),
                ("cab_approval_notes", models.TextField(blank=True)),
                (
                    "auto_approve_thresholds",
                    models.JSONField(
                        help_text="Thresholds per blast radius class: {'CRITICAL_INFRASTRUCTURE': 0, 'BUSINESS_CRITICAL': 0, ...}"  # noqa: E501
                    ),
                ),
                (
                    "risk_factor_weights",
                    models.JSONField(
                        help_text="Risk factor weights (must sum to 1.0): {'test_coverage': 0.20, 'security_issues': 0.15, ...}"  # noqa: E501
                    ),
                ),
                (
                    "calibration_data",
                    models.JSONField(
                        default=dict,
                        help_text="Incident correlation, risk score distribution, false positive/negative rates",
                    ),
                ),
                ("calibration_notes", models.TextField(blank=True, help_text="Evidence supporting this version")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(default="system", max_length=255)),
            ],
            options={
                "verbose_name": "Risk Model Version",
                "verbose_name_plural": "Risk Model Versions",
                "db_table": "evidence_store_riskmodelversion",
                "ordering": ["-version"],
                "indexes": [
                    models.Index(fields=["is_active", "effective_date"], name="evidence_st_is_acti_6ba1f3_idx"),
                    models.Index(fields=["version"], name="evidence_st_version_4af778_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="TrustMaturityProgress",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("evaluation_date", models.DateTimeField(db_index=True)),
                ("current_level", models.CharField(max_length=50)),
                ("next_level", models.CharField(blank=True, max_length=50)),
                ("evaluation_period_start", models.DateTimeField()),
                ("evaluation_period_end", models.DateTimeField()),
                ("deployments_total", models.IntegerField(help_text="Total deployments in period")),
                ("incidents_total", models.IntegerField(help_text="Total incidents in period")),
                (
                    "incident_rate",
                    models.DecimalField(
                        decimal_places=4, help_text="Incident rate (incidents / deployments)", max_digits=5
                    ),
                ),
                ("p1_incidents", models.IntegerField(default=0)),
                ("p2_incidents", models.IntegerField(default=0)),
                ("p3_incidents", models.IntegerField(default=0)),
                ("p4_incidents", models.IntegerField(default=0)),
                ("auto_approved_deployments", models.IntegerField(default=0)),
                ("auto_approved_incidents", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("EVALUATING", "Evaluating"),
                            ("CRITERIA_MET", "Criteria Met - Ready to Progress"),
                            ("CRITERIA_NOT_MET", "Criteria Not Met"),
                            ("PROGRESSED", "Progressed to Next Level"),
                            ("REGRESSED", "Regressed Due to Incidents"),
                        ],
                        max_length=50,
                    ),
                ),
                ("decision_notes", models.TextField(help_text="Rationale for progression decision")),
                (
                    "blocking_criteria",
                    models.JSONField(default=list, help_text="List of criteria that blocked progression (if any)"),
                ),
                ("requires_cab_approval", models.BooleanField(default=True)),
                ("cab_approved", models.BooleanField(default=False)),
                ("cab_approval_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Trust Maturity Progress",
                "verbose_name_plural": "Trust Maturity Progress Records",
                "db_table": "evidence_store_trustmaturityprogress",
                "ordering": ["-evaluation_date"],
                "indexes": [
                    models.Index(fields=["evaluation_date", "status"], name="evidence_st_evaluat_df4e8f_idx"),
                    models.Index(fields=["current_level"], name="evidence_st_current_22aeda_idx"),
                ],
            },
        ),
    ]
