# Generated by Django 5.1.15 on 2026-01-30 18:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("policy_documents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="documentcategory",
            options={
                "ordering": ["category_type", "name"],
                "verbose_name": "Document Category",
                "verbose_name_plural": "Document Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="documentchunk",
            options={
                "ordering": ["document", "chunk_index"],
                "verbose_name": "Document Chunk",
                "verbose_name_plural": "Document Chunks",
            },
        ),
        migrations.AlterModelOptions(
            name="policydocument",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Policy Document",
                "verbose_name_plural": "Policy Documents",
            },
        ),
        migrations.RenameIndex(
            model_name="documentchunk",
            new_name="policy_docu_documen_3b0626_idx",
            old_name="documentchu_document_chunk_idx",
        ),
        migrations.RenameIndex(
            model_name="policydocument",
            new_name="policy_docu_categor_2bd889_idx",
            old_name="policydocum_categor_idx",
        ),
        migrations.RenameIndex(
            model_name="policydocument",
            new_name="policy_docu_status_14624b_idx",
            old_name="policydocum_status_created_idx",
        ),
        migrations.AddIndex(
            model_name="policydocument",
            index=models.Index(fields=["content_hash"], name="policy_docu_content_d79890_idx"),
        ),
    ]
