# Generated by Django 5.0.14 on 2026-01-04 19:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DeploymentEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True, help_text="Deployment correlation ID"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("DEPLOYMENT_CREATED", "Deployment Created"),
                            ("RISK_ASSESSED", "Risk Assessed"),
                            ("CAB_SUBMITTED", "CAB Submitted"),
                            ("CAB_APPROVED", "CAB Approved"),
                            ("CAB_REJECTED", "CAB Rejected"),
                            ("DEPLOYMENT_STARTED", "Deployment Started"),
                            ("DEPLOYMENT_COMPLETED", "Deployment Completed"),
                            ("DEPLOYMENT_FAILED", "Deployment Failed"),
                            ("ROLLBACK_INITIATED", "Rollback Initiated"),
                            ("ROLLBACK_COMPLETED", "Rollback Completed"),
                        ],
                        max_length=30,
                    ),
                ),
                ("event_data", models.JSONField(help_text="Event payload")),
                (
                    "actor",
                    models.CharField(
                        help_text="User or system that triggered event", max_length=255
                    ),
                ),
            ],
            options={
                "verbose_name": "Deployment Event",
                "verbose_name_plural": "Deployment Events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["correlation_id", "created_at"],
                        name="event_store_correla_552470_idx",
                    ),
                    models.Index(
                        fields=["event_type", "created_at"],
                        name="event_store_event_t_610c26_idx",
                    ),
                ],
            },
        ),
    ]
