# Generated by Django 5.1.15 on 2026-01-31 12:03

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("deployment_intents", "0004_add_paused_cancelled_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChangeRecord",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique correlation ID for audit trail and tracing",
                        unique=True,
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("servicenow_number", models.CharField(help_text="CHG number", max_length=50, unique=True)),
                ("servicenow_sys_id", models.CharField(help_text="ServiceNow sys_id", max_length=100)),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("standard", "Standard (Pre-approved)"),
                            ("normal", "Normal (CAB Approval)"),
                            ("emergency", "Emergency (Expedited)"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("assess", "Assess"),
                            ("authorize", "Authorize"),
                            ("scheduled", "Scheduled"),
                            ("implement", "Implement"),
                            ("review", "Review"),
                            ("closed", "Closed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=50,
                    ),
                ),
                ("short_description", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("risk_level", models.CharField(default="moderate", max_length=20)),
                ("impact", models.CharField(default="low", max_length=20)),
                ("planned_start", models.DateTimeField()),
                ("planned_end", models.DateTimeField()),
                ("actual_start", models.DateTimeField(blank=True, null=True)),
                ("actual_end", models.DateTimeField(blank=True, null=True)),
                ("close_code", models.CharField(blank=True, max_length=50)),
                ("close_notes", models.TextField(blank=True)),
                ("success", models.BooleanField(null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deployment_intent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_records",
                        to="deployment_intents.deploymentintent",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Change Record",
                "verbose_name_plural": "Change Records",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChangeAuditEvent",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("created", "Change Created"),
                            ("state_change", "State Change"),
                            ("notification_sent", "Notification Sent"),
                            ("kb_linked", "KB Article Linked"),
                            ("evidence_attached", "Evidence Attached"),
                            ("approval_received", "Approval Received"),
                            ("closed", "Change Closed"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("old_value", models.TextField(blank=True)),
                ("new_value", models.TextField(blank=True)),
                ("metadata", models.JSONField(default=dict)),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "change_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_events",
                        to="change_communications.changerecord",
                    ),
                ),
            ],
            options={
                "verbose_name": "Change Audit Event",
                "verbose_name_plural": "Change Audit Events",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CommunicationTemplate",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("scheduled", "Change Scheduled"),
                            ("started", "Deployment Started"),
                            ("progress", "Progress Update"),
                            ("completed", "Deployment Completed"),
                            ("failed", "Deployment Failed"),
                            ("rollback", "Rollback Initiated"),
                            ("closed", "Change Closed"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("teams", "Microsoft Teams"),
                            ("slack", "Slack"),
                            ("servicenow", "ServiceNow Notification"),
                        ],
                        max_length=50,
                    ),
                ),
                ("subject_template", models.CharField(max_length=500)),
                ("body_template", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("variables", models.JSONField(default=list, help_text="List of available template variables")),
            ],
            options={
                "verbose_name": "Communication Template",
                "verbose_name_plural": "Communication Templates",
                "ordering": ["event_type", "channel"],
                "indexes": [
                    models.Index(fields=["event_type", "channel", "is_active"], name="change_comm_event_t_59c722_idx")
                ],
                "unique_together": {("event_type", "channel")},
            },
        ),
        migrations.CreateModel(
            name="KBArticleLink",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("kb_article_number", models.CharField(max_length=50)),
                ("kb_article_sys_id", models.CharField(max_length=100)),
                ("kb_article_title", models.CharField(blank=True, max_length=500)),
                (
                    "link_type",
                    models.CharField(
                        choices=[
                            ("created", "Created by Agent"),
                            ("updated", "Updated by Agent"),
                            ("referenced", "Referenced"),
                            ("linked", "Manually Linked"),
                        ],
                        max_length=50,
                    ),
                ),
                ("created_by_agent", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                (
                    "change_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kb_articles",
                        to="change_communications.changerecord",
                    ),
                ),
            ],
            options={
                "verbose_name": "KB Article Link",
                "verbose_name_plural": "KB Article Links",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StakeholderGroup",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "notification_channel",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("teams", "Microsoft Teams"),
                            ("slack", "Slack"),
                            ("servicenow", "ServiceNow Notification"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "channel_config",
                    models.JSONField(
                        default=dict, help_text="Channel-specific configuration (emails, webhook URLs, etc.)"
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "scope_filters",
                    models.JSONField(default=dict, help_text="Filters for when to notify this group (apps, BUs, etc.)"),
                ),
            ],
            options={
                "verbose_name": "Stakeholder Group",
                "verbose_name_plural": "Stakeholder Groups",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["notification_channel", "is_active"], name="change_comm_notific_427b08_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Communication",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique correlation ID for audit trail and tracing",
                        unique=True,
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("channel", models.CharField(max_length=50)),
                ("subject", models.CharField(max_length=500)),
                ("body", models.TextField()),
                ("recipients", models.JSONField(default=list)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("retry_count", models.IntegerField(default=0)),
                (
                    "change_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="communications",
                        to="change_communications.changerecord",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="change_communications.communicationtemplate",
                    ),
                ),
                (
                    "stakeholder_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="change_communications.stakeholdergroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Communication",
                "verbose_name_plural": "Communications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="changerecord",
            index=models.Index(fields=["servicenow_number"], name="change_comm_service_a13d1f_idx"),
        ),
        migrations.AddIndex(
            model_name="changerecord",
            index=models.Index(fields=["state", "created_at"], name="change_comm_state_d4f2c7_idx"),
        ),
        migrations.AddIndex(
            model_name="changerecord",
            index=models.Index(fields=["change_type"], name="change_comm_change__ac127c_idx"),
        ),
        migrations.AddIndex(
            model_name="changerecord",
            index=models.Index(fields=["correlation_id"], name="change_comm_correla_16d27f_idx"),
        ),
        migrations.AddIndex(
            model_name="changerecord",
            index=models.Index(fields=["planned_start"], name="change_comm_planned_5ec0dc_idx"),
        ),
        migrations.AddIndex(
            model_name="changeauditevent",
            index=models.Index(fields=["change_record", "created_at"], name="change_comm_change__eb171c_idx"),
        ),
        migrations.AddIndex(
            model_name="changeauditevent",
            index=models.Index(fields=["event_type"], name="change_comm_event_t_1b53e3_idx"),
        ),
        migrations.AddIndex(
            model_name="kbarticlelink",
            index=models.Index(fields=["change_record"], name="change_comm_change__ea6e7e_idx"),
        ),
        migrations.AddIndex(
            model_name="kbarticlelink",
            index=models.Index(fields=["kb_article_number"], name="change_comm_kb_arti_3922ea_idx"),
        ),
        migrations.AddIndex(
            model_name="kbarticlelink",
            index=models.Index(fields=["link_type"], name="change_comm_link_ty_98c5fc_idx"),
        ),
        migrations.AddIndex(
            model_name="communication",
            index=models.Index(fields=["change_record", "status"], name="change_comm_change__bd2f33_idx"),
        ),
        migrations.AddIndex(
            model_name="communication",
            index=models.Index(fields=["channel", "status"], name="change_comm_channel_54658e_idx"),
        ),
        migrations.AddIndex(
            model_name="communication",
            index=models.Index(fields=["correlation_id"], name="change_comm_correla_36eda7_idx"),
        ),
        migrations.AddIndex(
            model_name="communication",
            index=models.Index(fields=["sent_at"], name="change_comm_sent_at_dd6363_idx"),
        ),
    ]
