# Generated by Django 5.1.15 on 2026-01-31 06:26

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AutomationAnalysis",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique correlation ID for audit trail and tracing",
                        unique=True,
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(help_text="Analysis name", max_length=255)),
                ("date_range_start", models.DateField(help_text="Start date for analysis")),
                ("date_range_end", models.DateField(help_text="End date for analysis")),
                ("sources_analyzed", models.JSONField(default=list, help_text="List of data sources analyzed")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("patterns_detected", models.IntegerField(default=0, help_text="Number of patterns detected")),
                ("candidates_generated", models.IntegerField(default=0, help_text="Number of candidates generated")),
            ],
            options={
                "verbose_name": "Automation Analysis",
                "verbose_name_plural": "Automation Analyses",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(fields=["status", "started_at"], name="automation__status_e30daa_idx"),
                    models.Index(fields=["correlation_id"], name="automation__correla_34d569_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ROIConfiguration",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(help_text="Configuration name", max_length=255)),
                (
                    "hourly_labor_cost",
                    models.DecimalField(decimal_places=2, help_text="Hourly labor cost", max_digits=10),
                ),
                (
                    "development_hourly_rate",
                    models.DecimalField(decimal_places=2, help_text="Development hourly rate", max_digits=10),
                ),
                (
                    "complexity_multipliers",
                    models.JSONField(
                        default=dict, help_text="Complexity multipliers: {low: hours, medium: hours, high: hours}"
                    ),
                ),
                ("is_default", models.BooleanField(db_index=True, default=False)),
            ],
            options={
                "verbose_name": "ROI Configuration",
                "verbose_name_plural": "ROI Configurations",
                "ordering": ["-is_default", "name"],
                "indexes": [models.Index(fields=["is_default"], name="automation__is_defa_e8485b_idx")],
            },
        ),
        migrations.CreateModel(
            name="TaskPattern",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(help_text="Pattern name/description", max_length=255)),
                (
                    "pattern_type",
                    models.CharField(
                        choices=[
                            ("repetitive", "Repetitive Task"),
                            ("manual", "Manual Process"),
                            ("error_prone", "Error-Prone Operation"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("servicenow", "ServiceNow"), ("eucora", "EUCORA"), ("logs", "Activity Logs")],
                        max_length=50,
                    ),
                ),
                ("source_query", models.JSONField(default=dict, help_text="Query/filter used to detect this pattern")),
                ("occurrence_count", models.IntegerField(default=0, help_text="Number of occurrences detected")),
                (
                    "avg_duration_minutes",
                    models.FloatField(default=0.0, help_text="Average duration per occurrence in minutes"),
                ),
                ("error_rate", models.FloatField(default=0.0, help_text="Error rate (0.0 to 1.0)")),
                ("last_detected", models.DateTimeField(help_text="Last time this pattern was detected")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "verbose_name": "Task Pattern",
                "verbose_name_plural": "Task Patterns",
                "ordering": ["-last_detected"],
                "indexes": [
                    models.Index(fields=["pattern_type", "is_active"], name="automation__pattern_8541fe_idx"),
                    models.Index(fields=["source", "last_detected"], name="automation__source_0eebd5_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AutomationCandidate",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique correlation ID for audit trail and tracing",
                        unique=True,
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(help_text="Automation opportunity title", max_length=255)),
                ("description", models.TextField(help_text="Detailed description")),
                ("current_process", models.TextField(help_text="Current manual process description")),
                ("proposed_automation", models.TextField(help_text="Proposed automation approach")),
                ("frequency_score", models.FloatField(help_text="Frequency impact score")),
                ("time_impact_score", models.FloatField(help_text="Time impact score")),
                ("error_reduction_score", models.FloatField(help_text="Error reduction score")),
                ("complexity_score", models.FloatField(help_text="Automation complexity score (inverse)")),
                ("overall_score", models.FloatField(help_text="Overall automation score")),
                ("annual_occurrences", models.IntegerField(help_text="Expected annual occurrences")),
                ("time_saved_per_occurrence", models.FloatField(help_text="Time saved per occurrence in hours")),
                (
                    "estimated_annual_savings",
                    models.DecimalField(decimal_places=2, help_text="Estimated annual cost savings", max_digits=12),
                ),
                (
                    "development_cost_estimate",
                    models.DecimalField(decimal_places=2, help_text="Estimated development cost", max_digits=12),
                ),
                ("payback_period_months", models.FloatField(help_text="Payback period in months")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("identified", "Identified"),
                            ("reviewed", "Under Review"),
                            ("approved", "Approved"),
                            ("implemented", "Implemented"),
                            ("rejected", "Rejected"),
                        ],
                        default="identified",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("implementation_notes", models.TextField(blank=True, null=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_automations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pattern",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidates",
                        to="automation_advisor.taskpattern",
                    ),
                ),
            ],
            options={
                "verbose_name": "Automation Candidate",
                "verbose_name_plural": "Automation Candidates",
                "ordering": ["-overall_score"],
                "indexes": [
                    models.Index(fields=["status", "overall_score"], name="automation__status_6ae892_idx"),
                    models.Index(fields=["correlation_id"], name="automation__correla_298aa2_idx"),
                    models.Index(fields=["pattern", "status"], name="automation__pattern_0a4f65_idx"),
                ],
            },
        ),
    ]
